-- Seed data for fish_species table
-- Run this AFTER creating the schema

INSERT INTO fish_species (common_name, also_known_as, invasive, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, range_distribution, water_body_type, avg_adult_weight_lbs, known_for, avg_adult_length_inches, world_record, image_name_location, created_dt, updated_dt)
VALUES
-- Freshwater Fish
('Largemouth Bass', 'Black Bass, Green Trout', false, 'The largemouth bass is a freshwater game fish in the sunfish family, a species of black bass native to the eastern and central United States and Canada.', 'Centrarchidae', 'Micropterus salmoides', 'Least Concern', 'Prefers slow-moving, warm waters of lakes, ponds, and reservoirs with plenty of vegetation.', 'Plastic worms, crankbaits, spinnerbaits, live shiners', 'Spawns in spring when water temperatures reach 60-65°F. Males create nests in shallow water and guard the eggs.', 'Opportunistic predator eating fish, crayfish, frogs, and insects.', 'Native to North America, widely introduced elsewhere.', 'Lakes, ponds, rivers, reservoirs', 8.0, 'Popular game fish, known for aggressive strikes', 16.0, '22 lbs 4 oz - Lake Biwa, Japan, 2009', '/database/seeds/fish_images/Bass-Largemouth.png', NOW(), NOW()),

('Smallmouth Bass', 'Brown Bass, Smallie', false, 'Smallmouth bass are a popular freshwater gamefish known for their fierce fighting ability.', 'Centrarchidae', 'Micropterus dolomieu', 'Least Concern', 'Clear, cool streams and lakes with rocky bottoms.', 'Tube jigs, crankbaits, live crawfish', 'Spawns in spring in nests built by males in shallow water.', 'Crayfish, fish, insects', 'Great Lakes and St. Lawrence River drainage, widely introduced.', 'Streams, rivers, clear lakes', 3.0, 'Known for jumping when hooked', 12.0, '11 lbs 15 oz - Dale Hollow Reservoir, TN, 1955', '/database/seeds/fish_images/Bass-Smallmouth.png', NOW(), NOW()),

('Bluegill', 'Bream, Brim, Sunfish', false, 'Bluegill are small, colorful sunfish popular with beginning anglers.', 'Centrarchidae', 'Lepomis macrochirus', 'Least Concern', 'Warm, slow-moving waters with vegetation.', 'Worms, crickets, small spinners', 'Spawns in spring/summer in colonies of nests.', 'Insects, small crustaceans, fish eggs', 'Eastern North America, widely introduced.', 'Ponds, lakes, slow streams', 0.5, 'Great fish for beginners to catch', 6.0, '4 lbs 12 oz - Lake Warne, TX, 2021', '/database/seeds/fish_images/Bluegill.png', NOW(), NOW()),

('Channel Catfish', 'Catfish, Fiddler', false, 'Channel catfish are popular food and game fish known for their whiskers and excellent sense of smell.', 'Ictaluridae', 'Ictalurus punctatus', 'Least Concern', 'Wide variety of freshwater habitats, prefers clear, flowing water.', 'Stink baits, chicken liver, live baitfish', 'Spawns in late spring in cavities or under objects.', 'Omnivorous - fish, insects, crustaceans, plants', 'Central North America, widely introduced.', 'Rivers, lakes, reservoirs', 10.0, 'Excellent eating, popular night fishing target', 18.0, '58 lbs - Lake Hartwell, SC, 1964', '/database/seeds/fish_images/Channel-Catfish.png', NOW(), NOW()),

('Rainbow Trout', 'Steelhead', false, 'Rainbow trout are highly prized game fish known for their beautiful coloring and fighting spirit.', 'Salmonidae', 'Oncorhynchus mykiss', 'Least Concern', 'Cold, clean, well-oxygenated streams and lakes.', 'Spinners, flies, powerbait, small lures', 'Spawns in spring in gravel nests called redds.', 'Insects, small fish, crustaceans', 'Native to Pacific Northwest, widely introduced.', 'Streams, rivers, lakes', 5.0, 'Known for spectacular leaps when hooked', 20.0, '48 lbs - Lake Diefenbaker, Canada, 2009', '/database/seeds/fish_images/Rainbow-Trout.png', NOW(), NOW()),

('Walleye', 'Walleyed Pike, Yellow Pike', false, 'Walleye are prized game fish known for their excellent taste and challenging nature.', 'Percidae', 'Sander vitreus', 'Least Concern', 'Large, cool lakes and rivers with sandy or rocky bottoms.', 'Jigs, live minnows, crankbaits', 'Spawns in spring over rocky shoals.', 'Predator eating fish, especially perch and minnows', 'North America, widely distributed', 'Large lakes, rivers', 7.0, 'Famous for delicious white meat', 24.0, '25 lbs - Lake of the Woods, MN, 2020', '/database/seeds/fish_images/Walleye.png', NOW(), NOW()),

('Northern Pike', 'Pike, Jack', false, 'Northern pike are aggressive predators known for their toothy grin and explosive strikes.', 'Esocidae', 'Esox lucius', 'Least Concern', 'Weedy, shallow areas of lakes and slow rivers.', 'Large lures, live baitfish, spoons', 'Spawns in spring in shallow, vegetated water.', 'Fish (primary prey), ducks, rodents', 'Northern North America, Eurasia', 'Lakes, rivers, marshes', 15.0, 'One of the most aggressive freshwater fish', 30.0, '55 lbs - Lake of the Woods, Canada, 2019', '/database/seeds/fish_images/Northern-Pike.png', NOW(), NOW()),

('Crappie', 'White Crappie, Black Crappie', false, 'Crappie are popular panfish known for their delicious taste and schooling behavior.', 'Centrarchidae', 'Pomoxis spp.', 'Least Concern', 'Clear waters of lakes and reservoirs with submerged timber.', 'Small jigs, minnows, crappie rigs', 'Spawns in spring in shallow nests.', 'Small fish, insects, crustaceans', 'Eastern and central North America', 'Lakes, reservoirs, slow rivers', 1.0, 'Great eating, fun on light tackle', 8.0, '6 lbs 3 oz - Douglas Lake, TN, 2018', '/database/seeds/fish_images/Crappie.png', NOW(), NOW()),

-- Saltwater Fish
('Striped Bass', 'Rockfish, Striper', false, 'Striped bass are popular game fish known for their strength and migratory patterns.', 'Moronidae', 'Morone saxatilis', 'Least Concern', 'Coastal waters, bays, estuaries, and large rivers.', 'Topwater lures, live eels, bucktails', 'Spawns in spring in rivers.', 'Fish, squid, crustaceans', 'Atlantic coast, widely introduced', 'Ocean, bays, estuaries, rivers', 20.0, 'Known for long migrations and strong runs', 36.0, '78 lbs - Atlantic City, NJ, 2019', '/database/seeds/fish_images/Striped-Bass.png', NOW(), NOW()),

('Red Drum', 'Redfish, Channel Bass', false, 'Red drum are popular game fish known for their copper color and fighting ability.', 'Sciaenidae', 'Sciaenops ocellatus', 'Least Concern', 'Coastal waters, bays, and estuaries.', 'Crabs, shrimp, spoons', 'Spawns in fall near inlets and passes.', 'Crustaceans, fish', 'Western Atlantic Ocean, Gulf of Mexico', 'Coastal waters, bays', 30.0, 'Famous for black spot near tail', 45.0, '94 lbs - Hatteras, NC, 1984', '/database/seeds/fish_images/Red-Drum.png', NOW(), NOW()),

-- Invasive Species
('Carp', 'Common Carp, European Carp', true, 'Carp are invasive fish that can damage aquatic ecosystems by uprooting vegetation.', 'Cyprinidae', 'Cyprinus carpio', 'Invasive', 'Warm, slow-moving waters of lakes and rivers.', 'Corn, dough baits, bread', 'Spring spawning in shallow water.', 'Omnivorous - plants, insects, crustaceans', 'Native to Asia, introduced worldwide', 'Lakes, rivers, ponds', 20.0, 'Known for muddying water while feeding', 30.0, '88 lbs - Lake St. Lawrence, Canada, 2021', '/database/seeds/fish_images/Carp.png', NOW(), NOW()),

('Alewife', 'River Herring, Gaspereau', true, 'Alewife are invasive fish that impact native ecosystems and fisheries.', 'Clupeidae', 'Alosa pseudoharengus', 'Invasive', 'Great Lakes and inland waters.', 'Small jigs, spawn bags', 'Spawns in spring in streams and rivers.', 'Zooplankton, small invertebrates', 'Native to Atlantic coast, invasive in Great Lakes', 'Great Lakes, inland waters', 0.3, 'Major impact on native fish populations', 5.0, 'N/A', '/database/seeds/fish_images/Alewife.png', NOW(), NOW());

-- Verify seed
SELECT COUNT(*) as total_fish FROM fish_species;
SELECT common_name, invasive, family FROM fish_species ORDER BY common_name;
