-- LuckerLife Fish Database - Sample Data Matching Spreadsheet Format
-- This includes the Alewife entry and a few additional sample fish

-- Insert sample fish data matching the spreadsheet structure
INSERT INTO fish_species (
    image,
    image_name_location,
    common_name,
    also_known_as,
    invasive,
    description,
    family,
    species,
    environmental_status,
    habitat,
    fishing_techniques,
    spawning_habits_lifecycle,
    diet_feeding_habits,
    range_distribution,
    water_body_type,
    avg_adult_weight_lbs,
    known_for,
    avg_adult_length_inches,
    world_record
) VALUES 
(
    'Alewife.png',
    '/images/freshwater/alewife.png',
    'Alewife',
    'Shad, Herring, Gaspereau, Klack, Kyack, Branch Herring, Fresh Water Herring, Grayback',
    true,
    'The Alewife is a small, silvery fish with a deep, laterally compressed body. They have a dark spot behind their gills and their backs are dark blue-green to black. They are an invasive species in the Great Lakes region.',
    'Clupeidae',
    'Alosa pseudoharengus',
    'Invasive in Great Lakes',
    'Coastal streams, lakes, and oceanic waters. Prefers cool, clear waters.',
    'Small hooks, light tackle, cast nets during spawning runs',
    'Anadromous - spawns in freshwater streams in spring. Adults return to ocean or large lakes.',
    'Zooplankton, small crustaceans, insects, and fish larvae',
    'Atlantic coast from Newfoundland to North Carolina, introduced to Great Lakes',
    'Lakes, coastal streams, ocean',
    0.25,
    'Being a key forage fish and causing ecosystem disruption in Great Lakes',
    6.0,
    'Not typically targeted by anglers'
),
(
    'LargemouthBass.png',
    '/images/freshwater/largemouth_bass.png',
    'Largemouth Bass',
    'Black Bass, Bucket Mouth, Big Mouth Bass',
    false,
    'Large, aggressive gamefish with a distinctive large mouth that extends past the eye. Dark green with lighter belly and lateral line stripe.',
    'Centrarchidae',
    'Micropterus salmoides',
    'Stable',
    'Shallow, vegetated areas of lakes, ponds, and slow rivers with structure',
    'Plastic worms, crankbaits, spinnerbaits, jigs, topwater lures',
    'Spawns in shallow beds in spring when water reaches 60-65°F. Males guard nests.',
    'Fish, crayfish, frogs, insects, small mammals - opportunistic predators',
    'Originally southeastern US, now introduced throughout North America',
    'Lakes, ponds, slow rivers, reservoirs',
    4.5,
    'Premier gamefish, aggressive strikes, acrobatic fights',
    18.0,
    '22 lbs 4 oz - Montgomery Lake, Georgia (1932)'
),
(
    'RainbowTrout.png',
    '/images/freshwater/rainbow_trout.png',
    'Rainbow Trout',
    'Steelhead, Bow, Rainbow',
    false,
    'Beautiful trout with distinctive pink stripe along sides. Silver body with black spots on back, fins, and tail. Coloration varies by habitat.',
    'Salmonidae',
    'Oncorhynchus mykiss',
    'Stable',
    'Cold, clear streams and lakes with high oxygen content. Rocky or gravelly bottoms.',
    'Fly fishing, spin fishing, trolling, bait fishing with worms or salmon eggs',
    'Spawns in gravel beds in streams during spring. Some populations are anadromous (steelhead).',
    'Insects, crustaceans, small fish, worms. Opportunistic feeders.',
    'Native to Pacific coast, widely introduced throughout North America and worldwide',
    'Streams, rivers, lakes, coastal waters (steelhead)',
    2.0,
    'Excellent table fare, beautiful fish, strong fighting ability',
    12.0,
    '48 lbs - Bell Island, Alaska (1970)'
),
(
    'NorthernPike.png',
    '/images/freshwater/northern_pike.png',
    'Northern Pike',
    'Pike, Snake, Gator, Hammer Handle (small pike)',
    false,
    'Long, torpedo-shaped predator with duck-bill snout full of sharp teeth. Olive green with light oval spots along sides.',
    'Esocidae',
    'Esox lucius',
    'Stable',
    'Shallow, weedy areas of lakes and slow rivers. Ambush predators near structure.',
    'Spoons, spinnerbaits, large minnows, pike flies, deadbaits',
    'Spawns in shallow, marshy areas in early spring right after ice out.',
    'Fish, frogs, small mammals, birds, crayfish - apex predators',
    'Northern regions of North America, Europe, and Asia',
    'Lakes, rivers, marshes, brackish waters',
    8.0,
    'Aggressive predator, excellent table fare when prepared properly, trophy fishing',
    24.0,
    '55 lbs 1 oz - Lake of Grefeern, Germany (1986)'
);

-- Display summary of inserted data
SELECT 
    'Sample fish data inserted successfully!' as status,
    COUNT(*) as total_fish_inserted,
    COUNT(*) FILTER (WHERE invasive = true) as invasive_species,
    COUNT(*) FILTER (WHERE invasive = false) as native_species
FROM fish_species;