INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Jack, Talang Queenfish', 'Queenfish, Queenie, Giant Queenfish, Giant Trevally, Double-dotted Queenfish, Largemouth Queenfish, Skinny, White Fish', 'An elongated, streamlined, predatory fish of the Indian and west Pacific Oceans, the Talang queenfish (Scomberoides commersonnianus) may be recognised by its vivid, silvery body and relatively small fins. This powerful fish has rather short anal and dorsal fins, with the rear of the fins being reduced to just small spines, and a blunt snout and large mouth, armed with several rows of fine teeth. 
The attractive, bright, silver body contrasts with golden yellow streaks on the sides and dark yellow fins, while five to eight distinct dark blotches also run above the lateral line. The upperside of the Talang queenfish is sometimes tinged with dark green, and white on the underside.', 'Carangidae', 'Scomberoides commersonianus', 'Not Evaluated', 'The talang queenfish is found only in tropical waters of the Indian and west Pacific Oceans. Although it is found as far west as eastern Africa and as far east as Japan, the greatest abundance of the Talang queenfish occurs from south-east Asia to northern Australia.
Talang queenfishenerally frequent in shore lagoons, reefs, and off shore islands. They may enter estuaries, but the talang does not tolerate low salinity well, nor does it like turbid water.', 'The queenfish is extremely popular as a sport fish and is an excellent fighter on light tackle. Light graphite rods in the 3 – 6kg range, around 6’ in length matched to spin reels in the 2500 – 4000 class spooled with braided or gel spun lines with a breaking strain of 6 – 10lb are ideal for casting lures both from the shore and out in the boat for queenfish. 
Trolling for queenfish is also a popular technique and requires a light overhead or spin combo spooled with 4 – 8kg brightly colored nylon or braided line. Small lever drag reels and light rods are ideally suited for this exciting style of fishing. Queenfish do have small, sharp teeth so light nylon or fluoro carbon leaders are generally required to prevent bite offs and wire proving totally unnecessary for most fish. Queenfish are also a fantastic target species for salt water fly outfits which should be rated to between 7# – 9# depending on the size of queenfish being targeted.
Live hardy heads, small mullet and whiting will all make great live baits for fussy queen fish, try fishing them on light nylon leaders and running sinker rigs. It is also important to match your hook size to your bait. Small hard bodied lures 10 -20cm in length are ideal for both casting from shore and trolling from a boat at around 4 – 6 knots for queen fish with metal slices, soft plastics, surface lures and fly’s all proving to be incredibly effective on this veracious species. Surface lures such as poppers and stick baits are not only especially effective but also visually spectacular when launched upon by large, powerful queenies!
Polarized sunglasses will help considerably when trying to spot queenfish on shallow sand flats and in rougher conditions. Early mornings and late afternoons into evening are the preferred feeding times of most fish species including queenfish and thus the most productive times to target the species. Generally if a rising tide coincides with dawn or dusk the fishing can be red hot!
Many anglers say that the coarse flesh is rather tasteless and is better smoked, while others that it is quite good when very fresh. In any event, the leathery skin is best removed before cooking and one should avoid touching the spines of the dorsal and anal fins, as they are poisonous and can inflict very painful wounds.', 'Breeding occurs between September and March when the male and female simultaneously release thousands of sperm and eggs into the water for external fertilisation. The developing larval fish drift passively within the ocean currents, with adult Talang queenfish reaching sexual maturity at four to five years of age. Although it is not a true shoaling fish, the Talang queenfish is known to form small groups.', 'Queenfish are daytime feeders and prefer small pelagic fish, squids, and other fast moving prey. Occasionally they may also feed on crustaceans.', 'Ocean', 'Aerial Acrobatics', '39lb 7oz,
Craig Oliver,
Umkomaas, South Africa,
5/23/2010', 'Talang Queenfish WR');
INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, avg_adult_weight_lbs, known_for, world_record, world_record_link)
VALUES ('Salt', 'Leerfish', 'Akya, Garrick, Leer Fish, Leervis,  Pampano', 'Limited to the Mediterranean and tropical eastern Atlantic, the leerfish (aka garrick) is a member of the jack family and, accordingly, a powerful and determined fighter. In appearance, the species is unique and unmistakable. Like many coastal pelagics, the leerfish migrates seasonally.
Leerfish have a very distinctive body shape making them hard to confuse with other species. The body is elongated with a concave belly. The snout is slightly pointed and the caudal fin is deeply forked.
The lateral line is highly distinctive being irregular and wavy – curving over the pectoral fins then curving down to about the level of the pectorals before curving back to about the center of the body toward the rear.
The overall color of the leerfish is primarily silver. The flanks and dorsal areas are dusky to blueish grey, the belly is silvery to white. The fins are primarily gray with the edges often being quite darker than the rest of the fin. The juvenile leerfish is less than 4 in (10 cm) with an orange/yellow coloration presenting six to seven vertical dark to black bands.', 'Carangidae', 'Lichia amia', 'Least Concern', 'Leerfish or garrick fish are found in all eastern Atlantic Ocean waters along the coasts of the Iberian Peninsula and western Africa through and around the coast of South Africa and then north again along the eastern African coast to Mozambique. It can also be found in the Mediterranean Sea and the northern coast of the Arabian Sea.', 'Leerfish are a coastal species that form small schools in the surf zone off beaches and rocky promontories. This predatory fish is seasonally migratory and is a highly rated sport fish.
Leerfish will take live baits such as sardines and mullets typically and prefer surface lures as far as artificial baits go. Anglers fish live baits from shore along beaches and rocky headlands as well as from boats.
It is not uncommon to see leerfish pursuing bluefish or mullet on the surface along the coasts. It is rated fair for edibility', 'Leerfish migrate to KwaZulu-Natal from the Cape in winter and back to the Cape in summer. Migrations also coincide with the annual sardine run. Sexual maturity is reached at a fork length of 80 cm and spawning occurs off the KwaZulu-Natal coast. The eggs and larvae are distributed southwards inshore of the Agulhas Current to the estuaries in the Eastern and Southern Cape.', 'Adult leerfish feed mainly on fish with juveniles preferring crustaceans.', 'Ocean', '50-70', 'Stamina', '61 lb 4 oz,
Oriol Ribalta,
L''Ampolla, Spain,
4/30/2000', 'Leerfish WR');
INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Permit', 'Permit Fish, Yellow-wax Pampano, Pampano, Cobbler', 'The permit, Trachinotus falcatus, is a game fish of the western Atlantic Ocean belonging to the Carangidae family. Permits can be distinguished by their elongated dorsal fins and anal fin. The dorsal fin is shaped like a scythe. The tail of the permit are also deeply forked, and their bodies are compressed laterally, making the fish tall and thin when viewed from the front.
The average permit has six to seven dorsal spines, and 18 to 21 soft rays. The anal fin has two to three spines, and 16 to 18 soft rays. Both the dorsal and anal fins have dark, anterior lobes. Permits have no scutes and have a large, orange-yellow patch on their abdomens in front of their anal fins, while their pectoral fins are dark.
The permit fish can reach a maximum length of 48 in (122 cm) and can weigh up to 79 lb (36 kg), according to the Florida Museum of Natural History.', 'Carangidae', 'Trachinotus falcatus', 'Least Concern', 'Permit frequent offshore wrecks, oil platforms, and artificial reefs, as well as grass, mud and sand flats, deep channels, and holes inshore.. They are usually seen as individuals or in small schools; if approached when alone, they attempt to escape human interaction, but if approached when in a school formation, they become aggressive and can deliver dangerous bites. 
Permit are found in the western Atlantic Ocean from Massachusetts to Brazil, including most of the Caribbean islands.', 'Recreational anglers actively seek pompano because of the species'' fighting ability on light tackle and because of their excellent food quality.
When fishing for permit from a pier or the beach, look for them schooling on the far side of wave breaks and sand bars. The fish wait for sand fleas (also called mole crabs) and other small crustaceans to be washed off the beach and carried to them by the wave action. This puts them in easy reach of anglers who prefer to fish from the beach or a pier.  Use a spinning rod, fish finder rig, 2/0 circle hooks, and 12-lb (5.5 kg) monofilament line. Add a pyramid weight sufficient to keep your bait from returning to shore with the waves. You may need a bigger rod when the surf is heavy.
Catch sand fleas to use as bait. Sand fleas are the permit''s favorite food and are readily available in areas where they are. Look for v-shaped eddies when the waves roll off the beach. These are where sand fleas have washed ashore and are digging into the sand. Collect the sand fleas in a dry bucket.
If you can''t find any sand fleas, it''s likely that you won''t catch any pompano. Move to a location where sand fleas are plentiful.
Pompano will eat other crustaceans, like shrimp, and even on occasion small bait fish.
Cast right into the break of the surf and on the back sides of sand bars.
When fishing near a bridge, locate a pompano school on the down current side of a bridge. They wait for small crustaceans to be pulled off the bridge pilings by the current. The pompano will linger in one place as long as there is food coming their way, making them easy to catch by anglers who prefer to fish from a boat.
Use 20-lb test line in case you hook a larger fish. Attach an egg sinker, about 12 inches of leader, and a size 6 hook and use small crabs or sand fleas if possible. 
Anchor your boat or tie it to and up current piling. Drop your line near the down current pilings.
Permit will be on one side of the bridge when the tide comes in and the other side when the tide goes out, so you will have to move your boat if the tide changes.  Chum every 15 minutes or so. Chumming is the practice of dumping cut bait or fish parts into the water to attract fish. When fishing near a bridge, scrape barnacles and mussels from the pilings with a long-handled garden scraper and allow the current to carry them toward the pompano.  Allow your bait to sink to the bottom, pull it up slightly, and let it hit bottom again. The bait will disturb the sand on the bottom, which attracts the fish. You may have to change the weight of your sinker to accomplish this. Let your line play out as the current drags your line toward the down current pilings.', 'Although permit are found close to shore and even in some brackish areas, they spawn offshore. Life typically begins in spring or summer, though spawning in some areas may occur year-round. Permit are multiple-batch spawners, meaning one fish can produce and shed eggs more than once a season. Reproduction typically takes place offshore over reefs 33 to 100 feet deep.
Permit grow out of the larval stage and settle in their nursery habitat within 15 to 20 days of hatching.  A study in the Florida Keys found newly settled juveniles (less than 1 inch in standard length and less than 1 month old) along windward beaches in every month but July. Over the next two to three years of their lives, permit reach sexual maturity and, at an estimated 22 inches for females and 19.4 inches for males, about half of their potential size.', 'Permit primarily forage on flats and intertidal areas, entering shallow water on incoming tides from deeper adjacent channels and basins. They usually travel in schools of about ten, but may school in larger numbers; larger permit tend to be more solitary, feeding alone or in pairs. Permit also congregate around wrecks and other deeper-water structures. Like the bonefish, the permit uses its hard mouth to dig into the benthos and root up its prey. These food items usually consist of crustaceans and mollusks, which the permit crushes with its granular teeth and pharyngeal bony plates. However, as opportunistic feeders, permit will eat a variety of animals, including amphipods, copepods, mollusks, polychaetes, fish and insects. Developmentally, permit exhibit planktivorous feeding habits as juveniles, eating copepods, amphipods, mysids, larval shrimp, and fish. As they increase in size, permit begin to feed on benthic prey including mole crabs, coquin clams, flatworms, gastropods, and sessile barnacles. Larger adults feed on gastropods, sea urchins, bivalves, and crabs.', 'Ocean', 'Sight Casting Target', '60 lb,
Renato Fiedler,
Ilha do Mel, Paranagua, Brazil,
12/14/2002', 'Permit WR');
INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, avg_adult_weight_lbs, avg_adult_length_inches, known_for, world_record, world_record_link)
VALUES ('Salt', 'Shark, Blacktip', 'Black Fin Shark, Common Blacktop', 'The blacktip shark is a medium sized, stocky shark typically found inshore/nearshore in tropical and temperate waters inhabiting environments raining from muddy estuaries to  clear coral reefs. The blacktip is typically dark grey-blue to brown on top with white underneath, and has its name-sake black tipped fins. 
The blacktip shark has a stout body with a pointed snout, long gill slits, and no ridge between the dorsal fins. Most black tips have “black tips” or edges on their pectoral, dorsal, pelvic, and caudal fins. It usually attains a length of 4-5 feet.
Blacktips prefer to hunt schooling fish, often swimming quickly through a school and snapping up prey, and even breaching the water surface because of their momentum. They are generally timid sharks, but because they inhabit shallower waters (less than 100 ft), encounters with humans while they are hunting result in bites and other wounds (but no recorded fatalities).', 'Carcharhinidae', 'Carcharhinus limbatus', 'Near Threatened', 'The blacktip shark is found in warm coastal waters around the world—where it often encounters people. 
The animal frequents bays, estuaries, coral reefs, and the shallow waters off beaches and river mouths. 
During summer some blacktip sharks migrate to typically cooler waters, including those off Cape Cod, Massachusetts, while others stay put in warmer equatorial waters year-round. 
Blacktips have been observed to live in sexually segregated schools except during the mating season.', 'Blacktip sharks will aggressively strike baits, lures and flies, and they make sizzling runs when hooked, often leaping and twisting in the air (as does their close relative, the spinner shark). 
In areas such as the Florida Keys, blacktips make a popular flats target. Though on the flats they’re usually of modest size, the species can grow large: 
The all-tackle record, from Malindi May in Kenya, weighed 270 pounds, 9 ounces.', 'In 2008 DNA evidence confirmed that a female shark fertilized her own egg, impregnating herself without the help of a male. It''s not entirely known how rare this event, called parthenogenesis, is among blacktip or other sharks.
During more conventional breeding blacktips gather in aggregations to set up pup nurseries in shallow, near-shore waters. Female blacktip sharks produce four to ten live, free swimming pups per litter. They begin to reproduce at age four or five and continue to do so every other year throughout their lives, which can last longer than a decade. Young blacktips live in the coastal nurseries as juveniles, which likely helps them avoid predation from larger sharks.
But the shark''s preference for in-shore waters makes it particularly vulnerable to coastal development, which eliminates critical habitat such as nursery sites, and commercial fishing, which is particularly widespread in the southeastern United States, Mexico, and India. 
Worldwide, the blacktip is listed by the IUCN as near threatened, largely because it''s considered quite tasty and often targeted for its meat and its fins, which are used to make shark fin soup.', 'Blacktip sharks supplement their diets with skates, stingrays, squids, and some crustaceans. These sharks have also been known to follow fishing boats and feed on discarded bycatch.', 'Ocean', 220, 96, 'Stamina', '270 lb 9 oz,
Jurgen Oeder,
Malindi Bay, Kenya,
9/21/1984', 'Blacktip Shark WR');
INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Shark, Blue', 'Blue Whaler, Great Blue Shark, Bluedog', 'The blue shark (Prionace glauca) is a species of requiem shark, in the family Carcharhinidae, that inhabit deep waters in the world''s temperate and tropical oceans. Preferring cooler waters, blue sharks migrate long distances, such as from New England to South America. The species is listed as Near Threatened by the IUCN.
Blue sharks are light-bodied with long pectoral fins. Like many other sharks, blue sharks are countershaded in that the top of the body is deep blue with lighter tones on the flanks and white undersides. The male blue shark commonly grows to 6.0 to 9.3 ft (1.82 to 2.82 m) at maturity, whereas the larger females commonly grow to 7.2 to 10.8 ft (2.2 to 3.3 m) at maturity. Large specimens can grow to 12 ft ( 3.8 m). The blue shark is fairly elongated and slender in build and typically weighs from 60 to 121 lb (27 to 55 kg) in males and from 205 to 401 lb (93 to 182 kg) in large females. The blue shark is also ectothermic.', 'Carcharhinidae', 'Prionace glauca', 'Near Threatened', 'The blue shark is an oceanic and epipelagic shark found worldwide in deep temperate and tropical waters from the surface to about 1200 ft (350 m) down. 
In temperate seas, it may approach shore, where it can be observed by divers; while in tropical waters, it inhabits greater depths. 
It lives as far north as Norway and as far south as Chile. Blue sharks are found off the coasts of every continent, except Antarctica. Its greatest Pacific concentrations occur between 20° and 50° North, but with strong seasonal fluctuations. 
In the tropics, the blue shark spreads evenly between 20° N and 20° S. It prefers waters with a temperature range of 45–61 °F (7–16 °C) but will tolerate temperatures of 70 °F (21 °C ) or above. Records from the Atlantic show a regular clockwise migration within the prevailing currents.', 'Most blue sharks are caught by chumming with whole or cut fish on ocean tackle.', 'Blue Sharks are viviparous, with a yolk-sac placenta, delivering four to 135 pups per litter. The gestation period is between 9 and 12 months. Females mature at five to six years of age and males at four to five. Courtship is believed to involve biting by the male, as mature specimens can be accurately sexed according to the presence or absence of bite scarring. Female blue sharks have adapted to the rigorous mating ritual by developing skin three times as thick as male skin.', 'Squid are important prey for blue sharks, but their diet includes other invertebrates, such as cuttlefish and pelagic octopuses, as well as lobster, shrimp, crab, a large number of bony fishes, small sharks, mammalian carrion and occasional sea birds. Whale and porpoise blubber and meat have been retrieved from the stomachs of captured specimens and they are known to take cod from trawl nets.
Blue and other sharks have been observed and documented working together as a "pack" to herd prey into a concentrated group from which they can easily feed. 
Blue sharks rarely eat tuna, which have been observed taking advantage of the herding behavior to opportunistically feed on escaping prey. It is interesting to note that the observed herding behavior was undisturbed by different species of shark in the vicinity that normally would pursue the common prey.
The blue shark can swim at fast speeds, allowing it to catch up to prey easily. Its triangular teeth allow it to easily catch hold of slippery prey.', 'Ocean', 'Subpar Game Qualities', '528 lb,
Joe Seidel,
Montauk Point, New York, USA,
8/9/2001', 'Blue Shark WR');
INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Shark, Bull', 'Zambezi Shark, Zambi, Nicaragua Shark', 'Bull sharks are large and stout, with females being larger than males. The bull shark can be up to 81 cm (2.66 ft) in length at birth. Adult female bull sharks average 7.9 ft (2.4 m) long and typically weigh 290 lb (130 kg), whereas the slightly smaller adult male averages 7.4 ft (2.25 m) and 209 lb (95 kg). While a maximum size of 11 ft (3.5 m) is commonly reported, there is a questionable record of a female specimen of exactly 13 ft (4 m). The maximum recorded weight of a bull shark was 694 lb (315 kg) but they may grow larger. Bull sharks are wider and heavier than other requiem sharks of comparable length, and are grey on top and white below. The second dorsal fin is smaller than the first. The bull shark''s caudal fin is longer and lower than that of the larger sharks, and it has a small snout, and lacks an interdorsal ridge.
Bull sharks have a bite force of up to 5,914 newtons (1,330 lbf), weight for weight the highest among all investigated cartilaginous fishes.', 'Carcharhinidae', 'Carcharhinus leucas', 'Near Threatened', 'The bull shark is commonly found worldwide in coastal areas of warm oceans, in rivers and lakes, and occasionally salt and freshwater streams if they are deep enough. It is found to a depth of 490 ft (150 m), but does not usually swim deeper than 98 ft (30 m). 
In the Atlantic, the bull shark is found from Massachusetts to southern Brazil, and from Morocco to Angola. In the Indian Ocean, it is found from South Africa to Kenya, India, and Vietnam to Australia.
Populations of bull sharks are also found in several major rivers, with more than 500 bull sharks thought to be living in the Brisbane River in Queensland, Australia.
In the Pacific Ocean, the bull shark can be found from Baja California to Ecuador and has traveled 2,500 mi (4,000 km) up the Amazon River to Iquitos in Peru and north Bolivia.
Bull sharks can also thrive in fresh water lakes such as Lake Nicaragua and also fair well in the Ganges and Brahmaputra rivers of West Bengal and Assam in eastern India and adjoining Bangladesh. They can also live in water with a very high salt content such as in St. Lucia Estuary in South Africa. The bull shark is generally prolific in the warm coastal waters and estuarine systems of the Mozambique Channel and southward, including Kwa-Zulu Natal and Mozambique. The species has a distinct preference for warm currents.
After Hurricane Katrina, many bull sharks were sighted in Lake Pontchartrain. They have occasionally gone up the Mississippi River as far upstream as Alton, Illinois and have also been found in the Potomac River around Maryland and Virginia.', 'Light to medium lever drag stand up outfits are required for targeting bull sharks from a boat. They must have large line capacity and high quality drag systems capable of battling large fish in uncomfortable to rough sea conditions. Stand up outfits rated from 10 – 24kg are ideally suited for targeting bully’s to 100kg where as 24 – 37kg stand up or game chair outfits may be needed to subdue larger specimens to over 150kg. Wind on leaders of between 200 – 400lb need to be connected to plaited doubles via a cats paw knot and then attached to the bait trace with a quality stainless steel snap swivel or cork screw style snap for heavier 37kg line classes.  Shore based anglers require much longer rods and reels capable of casting long distances and handling line classes of between 15 – 24kg and plenty of it! Wire leader materials are also necessary to prevent bite offs.
Bull sharks will eat a variety of  bait fish such as mullet, mackerel, and tuna.  All rigs need to be made of wire to prevent bite offs during lengthy battles and hook points should be sharpened for extra penetration.
Always use fresh baits and ensure hook points are extra sharp.
Bull sharks prefer to feed at low light periods such as dawn and dusk as well as right through the night, high tides are also popular with this super aggressive species of shark. Deeper sections of remote river systems will also hold bull sharks during certain stages of the tide.', 'Bull sharks mate during late summer and early autumn,often in the brackish water of river mouths. After gestating for 12 months, a bull shark may give birth to four to ten live young. They are viviparous; they are born live and free-swimming. The young are about 27.6 in (70 cm) at birth and take 10 years to reach maturity. Coastal lagoons, river mouths, and other low-salinity estuaries are common nursery habitats.
70 to 90 in (175 to 235 cm) seems to be the size of a fully matured female bull shark that produce viable eggs for fertilization. The courting routine between bull sharks has not been observed in detail, but it is speculated that the male bites the females on the tail until they turn upside down at which point male copulation can occur. At some points, the harassment of the male can become violent. It is not uncommon to see scratches and other marks on a mature female from the mating ritual.
Bull sharks have an unusual migratory pattern in comparison to other sharks. They are found in rivers all over the world given their ability to go from seawater to freshwater and back again. They give birth in the brackish and freshwater portions of rivers where once born, the young bull sharks swim free of predators before they returning to the ocean to find mates.
Bull sharks are born alive in freshwater. The size range of a litter for a female bull shark is around 1 to 13 pups. The average gestation time span for a female bull shark is around 10 to 11 months. The male bull shark is able to begin reproducing around the age of 15 while the female cannot begin reproducing until the age of 18.
Young bull sharks are born into flat, protected areas where freshwater presents a natural defense against most larger predators. The shallower waters of estuaries and rivers helps protect the pups from predators, however there is still a high mortality rate for young bull sharks given that adult bull sharks do not rear or protect their young.', 'The bull shark''s diet consists mainly of bony fish and small sharks, including other bull sharks, but can also include turtles, birds, dolphins, terrestrial mammals, crustaceans, echinoderms, and stingrays. They hunt in murky waters where it is harder for the prey to see the shark coming. Bull sharks have been known to use the bump-and-bite technique to attack their prey. After the first initial contact the bull shark continues to bite and tackle its prey until they are unable to flee.
The bull shark is known to be a solitary hunter, although there are brief moments in which the bull sharks will team up with another bull shark in order to make it easier to hunt and to trick prey.
Sharks are known to be opportunistic feeders, and the bull shark is no exception to this, as it is part of the Carcharhinus family of sharks. Normally, sharks eat in short bursts, and when food is scarce, sharks digest for a much longer period of time in order to avoid starvation.As part of their survival mechanism, bull sharks will regurgitate the food in their stomachs in order to escape from a predator. This is a distraction tactic; if the predator moves to eat the regurgitated food the bull shark can use the opportunity to escape.', 'Ocean', 'Fight Dynamics', '697 lb 12 oz,
Ronald de Jager,
Malindi, Kenya,
3/24/2001', 'Bull Shark WR');
INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Shark, Lemon', 'Requium Shark', 'The lemon shark’s yellow coloring serves as camouflage while swimming over the sandy seafloor in its coastal habitat. It has a flattened head with a short, broad snout, and the second dorsal fin is almost as large as the first. Lemon sharks have electroreceptors concentrated in their heads, called the ampullae of Lorenzini. These receptors detect electrical pulses emitted by potential prey and allow these nocturnal feeders to sense their prey in the dark.
The lemon shark commonly attains a length of 7.9 to 10.2 ft (2.4 to 3.1 m) and a weight up to 200 lb (90 kg) by adulthood, although sexual maturity is attained at 7.3 ft (2.24 m) in males and 7.9 ft (2.4 m) in females.', 'Carcharhinidae', 'Negaprion brevirostris', 'Near Threatened', 'Lemon sharks are found from New Jersey to southern Brazil in the tropical western Atlantic Ocean. They also live off the coast of west Africa in the southeastern Atlantic. 
In addition, lemon sharks have been found in the eastern Pacific, from southern Baja California to Ecuador. This species of shark often occupies the subtropical shallow waters of coral reefs, mangroves, enclosed bays, and river mouths; however, lemon sharks have also been found in the open ocean down to depths of around 300 ft (90 m).
Although lemon sharks do swim up rivers, they never seem to travel very far into fresh water. They are found in open water primarily during migrations, and tend to stay along the continental and insular shelves for most of their lives.
Lemon sharks select habitats in warm and shallow water with a rocky or sandy bottom. The environmental temperature influences an individual’s body temperature, which ultimately affects physiological processes such as growth and metabolism. Lemon sharks, therefore, select warm-water habitats to maintain optimal metabolic levels. They are believed to avoid areas with thick seagrasses because they make finding prey more difficult.
Lemon sharks tend to live in or near shallow-water mangroves, which are often the nursery areas of several species of fish. One theory is that lemon sharks select mangrove habitats due to the abundance of prey that resides there, while another theory posits that mangroves provide a safe haven from adult lemon sharks that occasionally feed on juvenile sharks and are unable to enter the shallow waters. Ontogenetic niche shifts, or changes in an animal’s niche breadth or position, to deeper waters are known to occur in relation to a lemon shark’s size. These changes occur due to the dramatic decrease in the risk of predation as body size increases. Habitat selection clearly depends on a variety of biological and environmental variables.
The mangrove areas that lemon sharks inhabit are often referred to as their nursery sites. A nursery site is best defined as the most common area sharks are encountered, the location sharks tend to remain at after birth or frequently return to, and the habitat used by shark groups repeatedly for several years. The nursery ground concept has been known and studied for at least a century. In addition, fossil evidence from 320 million years ago suggests the use of shallow, coastal areas as pupping grounds is primitive.', 'Most lemon sharks are caught by chumming with whole or cut fish on ocean tackle. Being a middleweight of the shark family, it makes a good candidate for medium tackle. Like most sharks, chunks of dead fish or cutbait are one of the top choices for bait.', 'Many species of sharks, including the lemon shark, are known to actively prefer to be social and live in groups or loose aggregations. A few benefits of group living are enhanced communication, courtship, predatory behavior, and protection. Group living and a preference for social interaction is thought to be important for the survival and success of juvenile lemon sharks. Group living, though, comes with its costs. A few include increased risk of disease, ease of parasite transmission, and competition for resources.
Lemon sharks congregate for reproduction at special mating grounds. Females give birth to their young in shallow nursery waters to which they are philopatric. Lemon shark young are known as pups and they tend to remain in the nursery area for several years before venturing into deeper waters. Lemon sharks are viviparous, meaning that the mother directly transfers nutrients to her young via a yolk-sac placenta and the young are born alive. Fertilization is internal and occurs after a male lemon shark holds a female, bites her, and inserts his clasper into her cloaca. 
Female lemon sharks are polyandrous and sperm competition occurs due to their ability to store sperm in an oviducal gland for several months. Several studies suggest that polyandry in female lemon sharks has adapted out of convenience, rather than indirect genetic benefits to offspring. This type of polyandry is termed as convenience polyandry because females are believed to mate multiple times to avoid harassment by males. Lemon sharks reach sexual maturity around 12–16 years of age and have low fecundity.The maximum number of pups recorded in a litter is 18.', 'Lemon sharks feed at night and are mainly piscivorous; however, they have been known to feed on crustaceans and benthic organisms.
Intraspecific predation, or cannibalism, of juvenile lemon sharks by larger conspecifics has also been documented. Rather than feeding randomly, lemon sharks display a high degree of preference for certain species and size of prey when environmental conditions are favorable.They also tend to prefer a prey when it is more abundant and available. Lemon sharks feed selectively on species that are slower and more easily captured by using a stalking technique. For example, parrotfish and mojarras are common prey in the Bahamas because they use camouflage rather than an escape response and are vulnerable due to their stationary foraging behavior. Lemon sharks feed on prey that are intermediate in size compared to other available prey. This tendency can be explained by the tradeoff between the probability of capture and the profitability when it comes to prey size. The general trend in the foraging behavior of lemon sharks conforms to the optimal foraging theory, which suggests a positive relationship between prey selectivity and availability.
Rather than rolling on their sides to rip off chunks of prey, lemon sharks approach their victim with speed only to brake suddenly using their pectoral fins upon contact. The animal then jabs forward multiple times until it has a good grasp of its prey in its jaw and proceeds to shake its head from side to side until it tears off a chunk of flesh. A feeding frenzy, or large swarm of other sharks, then forms as the individuals sense the blood and bodily fluids released from the prey. Sounds of struggling prey also attract groups of sharks, suggesting they use sound detection for predation. Group feeding behavior such as pack hunting or communal scavenging was observed in a study in which pieces of the same stingray were found in the stomachs of several lemon shark individuals that were caught and examined.', 'Ocean', 'Fight Dynamics', '405 lb,
Colleen Harlow,
Buxton, North Carolina, USA,
11/23/1988', 'Lemon Shark WR');
INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Shark, Tiger', 'Leopard Shark, Maneater Shark, Spotted Shark', 'The tiger shark commonly attains a length of 10-13 ft (3.25–4.25 m) and weighs around 849–1,400 lb (385–635 kg). Bluish-green to dark gray or black dorsal surface with a yellowish-white to stark white underbelly. The characteristic dark spots and stripes are most prominent in young sharks and fade as the shark matures. Its snout is blunt and wide.', 'Carcharhinidae', 'Galeocerdo cuvier', 'Near Threatened', 'The tiger shark is often found close to the coast, mainly in tropical and subtropical waters throughout the world. Its behavior is primarily nomadic, but is guided by warmer currents. It stays closer to the equator throughout the colder months. 
It tends to stay in deep waters that line reefs, but it does move into channels to pursue prey in shallower waters. In the western Pacific Ocean, the shark has been found as far north as Japan and as far south as New Zealand. 
A tiger shark tagged in the Caribbean has been tracked migrating to Cape Cod; although they are a tropical species, the warm Gulf Stream brings the coast of Cape Cod to within the extreme north of its range during the summer.
Tiger sharks can be seen in the Gulf of Mexico, North American beaches, and parts of South America. It is also commonly known in the Caribbean Sea. Other locations where tiger sharks are seen include off Africa, China, Hong Kong, India, Australia, and Indonesia.
Certain tiger sharks have been recorded at depths just shy of 3,000 ft (900 m), but some sources claim they move into shallow water normally thought to be too shallow for a species of its size. 
A recent study showed the average tiger shark would be recorded at 1,100 ft (350 m), making it uncommon to see tiger sharks in shallow water. However, tiger sharks in Hawaii have been observed in depths as shallow as 10 ft (3 m) and regularly observed in coastal waters at depths of 20 to 40 ft (6 to 12 m).
Tiger sharks hava a notable tolerance for many different kinds of marine habitat but generally prefers murky waters in coastal areas. It is commonly found in river estuaries, harbors, and other inlets where runoff from the land may attract a high number of prey items. Shallow areas around large island chains and oceanic islands including lagoons, are also part of the tiger shark''s natural environment. It is often seen at the surface and has been reported to depths of 350 m (1085 ft).
Tiger sharks undergo seasonal migrations. It is well known that they move into temperate waters from the tropics for the warmer months and return during the winter. These sharks also make long oceanic migrations between islands and are capable of traveling long distances in a short amount of time.', 'Only the heaviest sporting outfits will suffice with adult tigers. Like most sharks, chunks of dead fish or cutbait are one of the top choices for bait, but large live baits have been known to work as well.', 'The tiger shark is the only species of its family that is ovoviviparous. The gestation period ranges from 14-16 months, at which time a female can give birth to anywhere from 10 to 80 pups. In the Northern Hemisphere, mating takes place between March and May and the young are born between April and June of the following year. In the Southern Hemisphere, it is believed that pupping occurs in November to January. It is believed by some scientists that because of the large size of the young at birth, uterine nutrition is supplemented by ''uterine milk'' secreted by the lining of the uterus.', 'The tiger shark is a solitary, mostly nocturnal hunter, and is notable for having the widest food spectrum of all sharks, consuming a variety of prey ranging from crustaceans, fish, seals, birds, squid, turtles, and sea snakes to dolphins and even other smaller sharks. The tiger shark has been known to eat inedible manmade objects that linger in its stomach, and it has a reputation as a "garbage eater". While the tiger shark sits atop the food chain as an apex predator, killer whales have been known on occasion to prey on them.The tiger shark is considered a near threatened species due to finning and fishing by humans.', 'Ocean', 'Stamina', '1785 lb 11 oz,
Kevin James Clapson,
Ulladulla, Australia,
3/28/2004', 'Tiger Shark WR');
INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, avg_adult_weight_lbs, avg_adult_length_inches, known_for, world_record, world_record_link)
VALUES ('Salt', 'Snook', 'Robalo, Saltwater Pike, Sergeant Fish', 'Snook are a large vigorous bony fish of coastal and brackish waters that is an important food and sport fish. 
Snook have long, concave snouts with jutting under jaws. The lateral line is pigmented and distinct, extending well into the tail. Coloration ranges from dark brown on the back to silvery on the sides and white below. The two dorsal fins are well separated.
Snook are opportunistic predators whose feeding habits indicate that there is a positive relationship between their size and the size of their prey, meaning that as the snook grows it feeds on larger and larger prey. Snook cannot tolerate water temperatures below 60 degrees F for long.
Common snook have been found to occasionally engage in cannibalistic activities, though this behavior is rare. This usually occurs during the winter months when adult and juvenile common snook are in close proximity to one another within their estuarine habitats. This form of cannibalism where the juveniles are fed on by the adults is referred to as intercohort cannibalism. The adult common snook who do cannibalize juveniles most likely target them due to the fact that the juveniles may be the largest of the available prey, and are therefore more nutritionally efficient to prey upon.', 'Centropomidae', 'Centropomus undecimalis', 'Least Concern', 'The Common Snook is widespread throughout the tropical waters of the western Atlantic Ocean from the coast of the North Carolina to Brazil including the Gulf of Mexico and the Caribbean Sea. 
Occurring in shallow coastal waters (up to 20 metres (66 ft) depth), estuaries, and lagoons, the fish often enters fresh water. It is carnivorous, with a diet dominated by smaller fishes, and crustaceans such as shrimps, and occasionally crabs.
Usually inshore in coastal and brackish or fresh waters, along mangrove shorelines, seawalls, and bridges; also on reefs and pilings nearshore. As juveniles, they prefer brackish water or freshwater habitats, but they must spawn in seawater.
The common snook is an estuarine-dependent fish species. Within estuaries, juvenile common snook are most often found inhabiting areas such as coastal wetland ponds, island networks, and creeks. 
The range of snook is largely determined by water temperature. Adults concentrate in Gulf passes and around pilings or other underwater structures and sometimes run up rivers and into lakes. Periodic blizzards decimate populations of this tropical species and the presence of young fish is revealed by stunted individuals struggling at the surface.
Despite being a euryhaline species of fish, common snook do show a tendency to gravitate towards lower salinity conditions in the early stages of their life. By being able to adapt and thrive in both high and low salinity conditions through osmoregulation, common snook display a high level of habitat plasticity.', 'The snook is a verocious feeder and a strong fighter when hooked.
There are many ways to target snook, from casting under dock lights at night, to sight-fishing along beaches at dusk and dawn, to shooting flies under vegetation and into mangrove roots. They feed most actively at night, but any period of low light can be productive.
 Experienced anglers make good catches by using long poles and dangling live shrimp along pilings in clear water. 
Snook orient themselves to face moving water and wait for prey to be carried down the current so targeting these areas can prove productive. 
Use live pinfish, small mullet, shrimp, or sardines free-lined or fished off the bottom with a fish finder rig. 
Snook also take a large variety of lures based on water conditions and often jump clear out of the water, fight ferociously and burst into long runs. 
The snook has razor-sharp gill covers so be careful when handling! Snook make excellent table fare.', 'Spawning occurs in June or July in the Gulf and probably around passes. Snook Are tropical fish that visit when Texas water are warm enough. They spend time in both fresh and saltwater, never far from seawater when they''re up river and never far from freshwater water when they''re in the Gulf.', 'Snook primarily eat other fish, crabs and shrimp, but have been known to attack and eat just about anything that breaks the surface in many rivers, estuaries and back waters.', 'Ocean', 30, 45, 'Sight Casting Target', '53 lb 10 oz,
Gilbert Ponzi,
Parismina Ranch, Costa Rica
10/18/1978', 'Common Snook WR');
INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Mahi-mahi', 'Dolphinfish, Dolphin, Dorado', 'The mahi-mahi (or dolphinfish) is bright greenish-blue above and yellow on the flanks with the capability of flashing purple, chartreuse, and a wide range of other colors. The body tapers sharply from head to tai. Irregular blue or golden blotches are often scattered over the sides. The anterior profile of the head on adult males is nearly vertical while the head of females is generally more sloping. A single dark dorsal fin extends from just behind the head to the tail and the anal fin margin is concave, extending from anus to tail. Mahi-mahi grow up to almost 7 feet and 88 pounds and live up to 5 years.', 'Coryphaenidae', 'Coryphaena hippurus', 'Least Concern', 'Atlantic mahi-mahi are found in the Atlantic Ocean, Gulf of Mexico, and Caribbean, and are caught from Massachusetts to Texas.
About one-third of U.S. commercial harvest of mahimahi comes from the Atlantic, Gulf of Mexico, and Caribbean. The rest comes from the Pacific, mainly Hawaii.
Pacific mahi-mahi are found in the Pacific and Western Pacific and are caught from California to Hawaii and the U.S. Pacific Island territories.
Mahi-mahi live near the surface in tropical and subtropical waters around the world. They swim together in schools as juveniles, but older fish are usually found alone. They travel seasonally as adults with changes in water temperature.', 'Mahi-mahi are highly sought for sport fishing and commercial purposes. Sport fishermen seek them due to their beauty, size, food quality, and healthy population. Mahi-mahi is popular in many restaurants.
Fishing charters most often look for floating debris and frigatebirds near the edge of the reef in about 120 feet (37 m) of water. Mahi-mahi (and many other fish) often swim near debris such as floating wood, five gallon bucket lids, palm trees and fronds, or sargasso weed lines and around fish buoys. Sargasso is floating seaweed that sometimes holds a complete ecosystem from microscopic creatures to seahorses and baitfish. Frigatebirds dive for food accompanying the debris or sargasso. Experienced fishing guides can tell what species are likely around the debris by the birds'' behavior.
Thirty- to fifty-pound gear is more than adequate when trolling for mahi-mahi. Fly-casters may especially seek frigatebirds to find big mahi-mahis, and then use a bait-and-switch technique. Ballyhoo or a net full of live sardines tossed into the water can excite the mahi-mahis into a feeding frenzy. Hookless teaser lures can have the same effect. After tossing the teasers or live chum, fishermen throw the fly to the feeding mahi-mahi. Once on a line, mahi-mahi are fast, flashy and acrobatic, with beautiful blue, yellow, green and even red dots of color.', 'Mahi-mahi are capable of reproducing at 4 to 5 months old. Believed to spawn every 2 to 3 days during the spawning season, releasing between 33,000 and 66,000 eggs each time. In the Atlantic, mahi-mahi spawn under patches of floating brown algae called Sargassum.', 'Mahi-mahi are top predators that feed in surface waters during the day. They eat a wide variety of species, including small pelagic fish, juvenile tuna, invertebrates, billfish, jacks, pompano, and pelagic larvae or nearshore, bottom-living species.
Predators include large tuna, marine mammals, marlin, sailfish, and swordfish.', 'Ocean', '01 Aerial Acrobatics', '87 lb,
Manuel Salazar,
Papagayo Gulf, Costa Rica,
9/25/1976', 'Mahi Mahi WR');