INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Kahawai', 'Giant Kahawai, Kermadec Kahawai, Northern Kahawai, Australian Salmon, Australian Herring', 'The kawawai is a streamlined, in-shore, pelagic species. It is a firm, silvery fish ranging from grey-blue to blue-green on top and silver below. They have rows of black spots along their flanks. While they can grow up to around 30in (75 cm) and 20lb (9kg), they average around 15-20in (40-50cm) and 2-3lb (1-2kg).

The kahawai (or Australian salmon) is unique to Australia and New Zealand. It resembles a trout or salmon in shape and appearance, but is of no relation. It and when properly bled can make for great eating. It is particularly good smoked.', 'Arripidae', 'Arripis trutta', 'Not Evaluated', 'Kahawai are found off the southern coast of Australia from western Victoria to New Zealand, including the islands of Tasmania, Lord Howe, and Norfolk.

Kahawai and other Australian salmon stay within the upper layers of relatively shallow (1–80 m), open and clear coastal waters (although the western Australian salmon may prefer deeper water). The turbulent surf zone of beaches, rocky reefs, bays, and brackish waters such as estuaries are also frequented, and some species may also enter rivers. Juveniles inhabit estuaries and mangroves, as well as sheltered bays with soft bottoms carpeted with seagrasses. Adults undertake seasonal migrations over vast distances, moving into deeper water during winter months. The evolutionary history of the species of Arripis has been shaped by changes to oceanographic conditions and land-bridges that occurred during glacial cycles.', 'Kahawai is the traditional maori name which when translated means "brave" or "strong" (kaha) water (wai). This in reference to the kahawi''s tendency to jump and fight when caught. In New Zealand it is often caught in abundance at river mouths and is a highly popular sports fish that is widely regarded to "punch above its weight" in terms of challenge to land.

It can often be caught on a spinning or surf casting reel, although it is not unheard of for fishermen to use lighter lines and fly fishing rods for a real challenge.

The kahawai is often associated with the white fronted tern, as the bird often congregates above the bait balls associated with a shoal of kahawai hunting. As such the tern is colloquially known as the "kahawai bird"', 'Although their reproduction is poorly studied, all Australian salmon including kahawai are known to be "pelagic spawners";