INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Jack, California Yellowtail', 'Yellowtail Amberjack, Asian Yellowtail,
Southern Yellowtail, Kingy, Cape Yellowtail, Forktail, Mossback, White Salmon', 'The body of the California yellowtail is elongated, fusiform and compressed. The upper and lower body profiles are similar and the snout is long and pointed with the mouth ending under front edge of pupil 

The California yellowtail is most often blue on the upper back with sides and belly coloration ranging from silvery to white. The California yellowtail presents  a narrow yellow-bronze stripe along the middle of body running down the lateral line and arching over the pectoral region, becoming yellow posteriorly on most fins including the tail. Juvenile present with numerous narrow dark bars (a little wider than pale interspaces) that do not extend onto the dorsal and anal fins.', 'Carangidae', 'Seriola lalandi dorsalis', 'Not Evaluated', 'The yellowtail''s range is circumglobal, in subtropical waters. It can be found near Catalina Island, San Clemente Island, and Santa Monica Bay, as well as in Mexican waters such as Baja California Peninsula and Gulf of California, congregating at certain areas in mass numbers like Cedros Island and Benitos Island. 

During the summer months yellowtails can also be found in association with floating kelp paddies off the coast of southern California and Baja California. 

Yellowtail populations have also been found in waters off South Africa, the Walter Shoals, Amsterdam Island, Japan, Australia, New Zealand, New Caledonia, Hawaii, Rapa, Pitcairn Island, Jeju Island, and Easter Island. In the Eastern Pacific, they can be found in waters off British Columbia, as well as from Canada to Chile. They are usually found around offshore islands, rocky reefs, and kelp beds. They are also found in increasing numbers off the Islands of the Tristan Da Cunha archipelago in the South Atlantic.', 'Angling for yellowtail requires tackle heavy enough to insure a fair chance of landing the fish. Yellowtail like to head for rocks or kelp as soon as they''re hooked so line should test 20-30 pounds, hooks should be small (size 6 or 4) but strong, and the angler must make sure the fish is played out before it nears the pier and the pilings otherwise tangling is likely inevitably ending in a broken line. 

Although an assortment of lures work well when fishing for California Yellowtail on boats, almost all of the pier-caught yellowtail are taken on live bait. The most effective live and cut baits are small jack mackerel, Pacific mackerel or Pacific sardines.', 'California yellowtail spawn in warm waters 100–300 miles off the California coast and return in May or June until September or December. They spawn slowly, but may live in excess of 30 years. 

Spawning usually begins at three years of age. One major spawning ground is at Cedros Island, where large numbers of 15- to 20-pound yellowtail can be caught. Yellowtail are aggressive towards other fish. 

They will often feed more frequently during spawning, which makes them an easy target for commercial fishing boats. They are currently not on the endangered list.', 'The California Yellowtail is carnivorous and feeds on a variety of fish. Mackerel, sardines, anchovies, squid, and crab are common in the yellowtail''s diet. Often, the California Yellowtail are found in schools feeding at the surface of the water, but also feed deeper down in the water column.', 'Ocean', 'Stamina', '109 lb 2 oz,
Masakazu Taniwaki,
Ohara, Chiba, Japan,
10/24/2009', 'Yellowtail WR');