INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, avg_adult_weight_lbs, avg_adult_length_inches, known_for, world_record, world_record_link)
VALUES ('Salt', 'Jack, Bluefin Trevally', 'Bluefin Jack, Bluefin Kingfish, Bluefinned Crevalle, Blue Ulua, Omilu, Spotted Trevally', 'The bluefin trevally is a species of large, widely distributed marine fish classified in the jack family, Carangidae. Bluefin trevally are easily recognized by their electric blue fins, tapered snout and numerous blue and black spots on their sides. Juveniles lack these obvious colors, and must be identified by more detailed anatomical features such as fin ray and scute counts. The species grows to a maximum known length of 46 inches and a weight of 95 pounds, however is rare above 32 inches.

It is similar in shape to a number of other large jacks and trevallies, having an oblong, compressed body with the dorsal profile slightly more convex than the ventral profile, particularly anteriorly. This slight convexity leads to the species having a much more pointed snout than most other members of Caranx. 

The dorsal fin is in two parts, the first consisting of 8 spines and the second of 1 spine followed by 21 to 24 soft rays. The anal fin consists of 2 anteriorly detached spines followed by 1 spine and 17 to 20 soft rays. The pelvic fins contain 1 spine and 20 soft rays. The caudal fin is strongly forked, and the pectoral fins are falcate, being longer than the length of the head. 

The lateral line has a pronounced and moderately long anterior arch, with the curved section intersecting the straight section below the lobe of the second dorsal fin. The curved section of the lateral line contains 55-70 scales while the straight section contains 0 to 10 scales followed by 27 to 42 strong scutes. The chest is completely covered in scales. 

The upper jaw contains a series of strong outer canines with an inner band of smaller teeth, while the lower jaw contains a single row of widely spaced conical teeth. The species has 25 to 29 gill rakers in total and there are 24 vertebrae present. The eye is covered by a moderately weakly developed adipose eyelid, and the posterior extremity of the jaw is vertically under or just past the anterior margin of the eye. Despite their wide range, the only geographical variation in the species is the depth of the body in smaller specimens.

The upper body of the bluefin trevally is a silver-brassy colour, fading to silvery white on the underside of the fish, often with blue hues. After they reach lengths greater than 16 cm, blue-black spots appear on the upper flanks of the fish, with these becoming more prolific with age. There is no dark spot on the operculum. The species takes its name from the colour of its dorsal, anal and caudal fins, which are a diagnostic electric blue. The pelvic and pectoral fins are white, with the pectoral fin having a yellow tinge. Juvenile fish do not have the bright blue fins, instead have dark fins with the exception of a yellow pectoral fin. Some juvenile fish have also been recorded as having up to five dark vertical bars on their sides.

The IGFA all-tackle world record is 29 pounds, 3 ounces from Clipperton Atoll (2012);