INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, avg_adult_weight_lbs, avg_adult_length_inches, known_for, world_record, world_record_link)
VALUES ('Salt', 'Bonefish', 'Banana,Bananafish, Indo-Pacific Bonefish, Ladyfish, Round Jaw, Salmon Peel, Tarpon, Tenny, Tenpounder', 'One of the most distinctive characteristics of the bonefish is the inferior mouth and conical nose that protrudes a third of its length beyond the mandible. The body is slender, round, and compressed, more so in large specimens than in young adults. The dorsal profile is more convex than the ventral profile. The first few rays of the dorsal fin are higher than the following rays and this lends a somewhat triangular shape to the dorsal fin when erect. The caudal fin is deeply forked, with the upper lobe slightly larger than the lower. 

Bonefish appear blue-greenish above, with bright silver scales on the sides and below. Dark streaks run in between the rows of scales, predominantly on the dorsal side of the body. The dorsal and caudal fins have dusky margins. Bonefish have no spines. Juvenile bonefish exhibit a series of nine dark crossbands on their backs. These bands extend nearly to the lateral line, with the third band crossing at the origin of the dorsal fin. Bands four and five are found under the posterior base of the dorsal fin. As the juvenile bonefish age the bands begin to disappear with the posterior bands the first to fade. Beyond about 3 inches (7.5 cm) the dark longitudinal streaks characteristic of the adults begin to appear and the last of the crossbands become obscured. 

Granular teeth, forming specialized dental plates, cover the tongue and upper jaw of the bonefish. Similar grinders are also present in the throat. The bonefish uses these modified teeth to grind its mollusk and crustacean prey. 

The IGFA all-tackle record of 19 pounds has held since 1962, when it was caught from the surf off South Africa (though not A. vulpes — another species).', 'Albulidae', 'Albula vulpes', 'Near Threatened', 'Bonefish are predominately a coastal species, commonly found in intertidal flats, mangrove areas, river mouths, and deeper adjacent waters. The flats vary in composition from sand or grass to rocky substrates. 

Bonefish can tolerate the oxygen-poor water they sometimes encounter in coastal habitats by inhaling air into a lung-like air bladder. Bonefish typically school, sometimes in groups of up to 100 individuals. Studies in the Bahamas using ultrasonic telemetry demonstrated the daily patterns of bonefish consist of a movement to shallow water during the rising tide, and a retreat into deeper water during a falling tide. Bonefish are also known to move from particular sites (creek, channel, bay, etc.) after inhabiting the location for a maximum period of several days. Over the long-term movements between such "favorite" sites seem to occur without any discernable pattern. During summer months, larger individuals tend to remain in deep water, rarely moving onto the flats;