INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Shark, Whitetip Reef', 'Brown Milbert''s Sand Bar Shark, Brown Shark, Nigano Shark, Oceanic White-Tipped Whaler, Silvertip Shark', 'A relatively small species, few whitetip reef sharks are longer than 5.2 ft (1.6 m). The maximum length this species attains is often given as 6.9 ft (2.1 m), though this was originally based on visual observations and may be dubious. The maximum reported weight is 40 lb (18.3 kg). The whitetip reef shark has a slim body and a short, broad head. The snout is flattened and blunt, with large flaps of skin in front of the nares that are furled into tubes. The eyes are small and oval with vertical pupils and prominent ridges above, and are often followed by a small notch. The mouth has a distinct downward slant (imparting a disgruntled expression to the shark), with short furrows at the corners. There are 42–50 tooth rows in the upper jaw and 42–48 tooth rows in the lower jaw. Each tooth has a single narrow, smooth-edged cusp at the center, flanked by a pair of much smaller cusplets.

The first dorsal fin is positioned well back on the body, closer to the pelvic than the pectoral fins. The second dorsal and anal fins are large, about half to three-quarters as high as the first dorsal fin. The broad, triangular pectoral fins originate at or slightly before the level of the fifth gill slit. There is no ridge between the first and second dorsal fins. The lower lobe of the caudal fin is half the length of the upper, which has a strong notch near the tip. The dermal denticles are small and overlapping, usually with 7 horizontal ridges, giving the skin a smooth feel. The coloration is grayish to brownish above and white below, with a pattern of scattered small, dark spots unique to each individual. The tips of the first dorsal fin and upper caudal fin lobe, and sometimes also the second dorsal fin and lower caudal fin lobe, are bright white.', 'Carcharhinidae', 'Carcharhinus longimanus', 'Vulnerable', 'The Whitetip Reef Shark is distributed widely across the entire Indo-Pacific region. It was once thought to have formerly existed in the Atlantic Ocean, based on fossil teeth found in North Carolina dating to the Miocene epoch. However, more recent research indicates that the teeth belonged to a mackerel shark, and that this species has never colonized the Atlantic.

In the Indian Ocean, it occurs from northern KwaZulu-Natal, South Africa to the Red Sea and the Indian subcontinent, including Madagascar, Mauritius, the Comoros, the Aldabra Group, the Seychelles, Sri Lanka, and the Chagos Archipelago. In the western and central Pacific, it occurs from off southern China, Taiwan, and the Ryukyu Islands, to the Philippines, Southeast Asia, and Indonesia, to northern Australia, and is also found around numerous islands in Melanesia, Micronesia, and Polynesia, as far as Hawaii to the north and the Pitcairn Islands to the southeast. In the eastern Pacific, it occurs from Costa Rica to Panama, and off the Galápagos Islands.

Associated almost exclusively with coral reef habitats, whitetip reef sharks are most often encountered around coral heads and ledges with high vertical relief, and additionally over sandy flats, in lagoons, and near drop-offs to deeper water. They prefer very clear water and rarely swim far from the bottom. This species is most common at a depth of 26–131 ft (8–40 m).

On occasion, whitetips may enter water less than 3 ft (1 m) deep, and there is an exceptional record of a whitetip reef shark being captured from a depth of 1,080 ft (330 m) in the Ryukyu Islands.', 'Whitetip sharks are small in size, but will strike baits, lures and flies fairly aggressively.', 'Like other members of its family, the whitetip reef shark is viviparous;