-- Import batch from saltwater_batch_05.json
-- Total records: 10

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Snapper, Mutton', 'Mangrove Snapper, Mango Snapper', 'The mutton snapper has an olive-tinted back and red sides with a black spot between the lateral line and the dorsal fin and blue stripes on the head. This species can reach a length of 37 in (94 cm), though most do not exceed 20 in (50 cm). The greatest known weight recorded for this species is 34 lb (15.6 kg).', 'Lutjanidae', 'Lutjanus analis', 'Vulnerable', 'Mutton snapper are native to the Atlantic coastal waters of the Americas from Massachusetts to southern Brazil, including the Caribbean Sea and the Gulf of Mexico. They are particularly common in the Caribbean. 

They inhabit reef environments, with adults found in areas with rock or coral, while juveniles occur in sandy habitats with plentiful weed growth. They can be found at depths of from 82 to 295 ft (25 to 90 m), though most often between 130 and 230 ft (40 and 70 m).', 'Mutton snapper are a highly prized fish by saltwater anglers; they can be caught on a variety of baits, but are most commonly caught on live or frozen shrimp, whole or cut squid, minnows, and smaller bait fish (such as live or dead pinfish). 

Mutton snapper have been caught on artificial baits, but seem to prefer live bait. They can generally be found in deeper water, although catches (generally of juveniles and smaller fish) are not uncommon in more shallow water. They are also caught on the surface during night-fishing expeditions. 

Mutton snapper are typically known as great fighters relative to other snapper species, so are harder to land on lighter tackle. Many are often landed as a bycatch of anglers targeting other species of snapper or grouper.', 'Male mutton snappers reach sexual maturity at about 38 to 43 cm (FL) while female snappers mature at about 45 to 47 cm (FL). The species is a gonochorist (i.e. separate sexes throughout life).

Like many snapper species, eggs of mutton snapper are pelagic and are hatched after approximately 20 hours.  At lengths of less than 10 mm, the larvae tend to be planktonic. They can be found in both brackish and marine waters at depths of 25-95 m. Juveniles are most common in inshore waterways where the substrate consists of sand, seagrass, or coral rubble.  Adults are typically found in deeper waters, at depths of 40 - 70 m, where they often form small schools during daylight hours, but disband at night.  Adults tend to remain in an area once they have become established and are most common in the open waters of shelf areas and around islands.  Larger adults inhabit coral reefs and rocky, hard bottom areas. 

As with most larger snappers, L. analis spawns offshore in groups in which spawning typically occurs in summer.  The snapper is a solitary species, and rarely seen in groups outside of the spawning season. The snapper spawns throughout their range, though most record is obtained in the north-eastern Caribbean. They form large, transient aggregations in which spawning may last for several weeks in a month for several months each year. Spawning aggregations occur from April to September, at outer reef slopes, and on reef promontories and drop-offs. Mutton snapper exhibit high site-fidelity, spawning at the same site and on the same lunar calendar days (during full moon or in the third lunar quarter), year after year. The snapper is oviparous, releasing pelagic eggs that move freely with the water currents. As is typical of pelagic spawners, the number of eggs is dependent upon the size of the female, with larger fish containing more eggs. After spawning, the adult fish moves offshore to deeper waters', 'The feeding habits of mutton snapper change during its life. Larval snapper feeds on plankton near the surface of water; as it settles out into shallow grass beds, it begins to feed on larger plankton and small invertebrates. The diet then switches to shrimps, snails, crabs, and small fishes including mullets and small grunts.', 'Ocean', 'Fight Dynamics', '30 lb 4 oz,
Richard Casey,
Dry Tortugas, Florida, USA	,
11/29/1998', 'Mutton Snapper WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Snapper, Red', 'American Reds, Genuine Red Snapper, Northern Red Snapper, Snapper, Spot Snapper', 'Red snapper are pinkish to red color and sharply pointed anal fin (rather than rounded) distinguishes the red snapper from most other Gulf of Mexico snappers. The snout is long and triangular and the eyes are a distinctive red. Adults have no dark lateral spot, but juveniles have a dark spot on the upper sides below the anterior soft dorsal fin. 

The Red Snapper is sometimes confused with the Southern Red Snapper, L. purpureus, found throughout Caribbean Sea from Cuba southward to northeast Brazil. There are differences, however, in scale and anal fin ray counts. The Red Snapper usually has fewer scales in a row along the midside (usually 47-49 not 50-51 and fewer scales between the beginning of the dorsal fin and the lateral line, (usually 8-9, not 10-11). The Norther Red Snapper has more soft rays in the anal fins (usually 9 instead of 8). 

Red snapper grow at a moderate rate, up to about 40 inches long and 50 pounds.
They can live a long time—red snapper as old as 57 have been reported in the Gulf of Mexico and as old as 51 in the South Atlantic.

The Red Snapper is one of the most valuable and heavily exploited snappers in American waters. It is now closely protected; shrimp fishing, accused of destroying young snappers, is currently restricted.', 'Lutjanidae', 'Lutjanus campechanus', 'Vulnerable', 'Red Snapper occur in the Gulf of Mexico and in the western Atlantic along the eastern coast of the USA as far north as Massachusetts, but rarely north of the Carolinas. They are absent from the Bahamas and the Caribbean. Juveniles occur in shallow water over sandy or mud bottoms. Adults are more plentiful offshore in 60 to 440 ft of water associated with rough, rocky bottoms and wrecks.', 'Red snappers tend to be nibblers and pickers and soft touch is needed when angling. Red snanpper seem to prefer a still or slowly moving bait. Squid, whole fish and cut bait can be used to entice red snapper to bite. By chumming them up to the surface, flies can also be used.', 'Females are able to reproduce as early as age 2. Males and females spawn from May to October, depending on their location. The red snapper spawning season in many waters begins in May and ends in late September (about 120 days); peak spawning months appear to be May, June and July. Unlike many fish species that spawn between dusk and midnight, red snappers begin their spawning activities in the early afternoon and stop at dusk. There is no evidence that red snappers form spawning aggregations at specific sites year after year as do some other species of snappers and many species of groupers. Red snappers seem to spawn wherever and whenever they are capable of doing so.

Red snappers, like many other marine fish species, are batch (or serial) spawners. This means they are capable of repeatedly spawning batches of eggs every few days over the course of the entire spawning season, a strategy that allows them to produce and spawn many times more eggs than if they only spawned a single time per season. The number of eggs spawned in each batch varies with the size of the individual and can be as few as a 1000 for a small female to as many as 2.5 million for a large, healthy female. Given that the average time between successive spawning is four days, female red snappers will spawn about 30 times (some more, some fewer) during the spawning season. Even a small red snapper will produce a seemingly respectable 30,000 eggs in a season while a large female might spawn an incredible 75 million or more eggs each season! And if it should survive to the known maximum of its longevity, a female could potentially spawn nearly 4 billion eggs in her lifetime.', 'Red snappers feed primarily on fish, crustaceans, worms, cephalopods (octopus or squid) and some plankton (tiny floating plants and animals).', 'Ocean', 'Fight Dynamics', '50 lb 4 oz,
Captain Doc Kennedy,
Gulf of Mexico, Louisiana, USA,
6/23/1996', 'Red Snapper WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Tilefish', 'Golden Tilefish, Golden Bass, Golden Snapper, Great Northern Tilefish, Rainbow Tilefish', 'Tilefish, sometimes known as “the clown of the sea,” are colorful. They are iridescent blue-green on the back, with numerous spots of bright yellow and gold. Their bellies are white, and their heads are rosy with blue under the eyes. Their pectoral fins are sepia-colored, and the edge of their anal fins is purplish-blue. Golden tilefish are easily distinguishable from other members of the tilefish family by the large crest on their head. Males can be distinguished from females by their larger crest.

Tilefish grow slowly, up to 3 ¾ feet, although the average size harvested is 2 feet. They have a long life span, up to 46 years (females) and 39 years (males). These are the oldest tilefish on record, but radiometric dating techniques indicate tilefish may live as long as 50 years.', 'Malacanthidae', 'Lopholatilus chamaeleonticeps', 'Endangered', 'Tilefish sometimes concentrate in small groups and are found along the outer continental shelf and upper continental slope of the entire U.S. East Coast and in the Gulf of Mexico. They are most abundant from Nantucket Island, Massachusetts, south to Cape May, New Jersey.

Tilefish live in water from 250 to 1,500 feet deep where bottom temperatures range from 49 to 58 ° F. Individual tilefish are found in and around submarine canyons, where they burrow in mud or sand sediment. They also exist near rocks and boulders in vertical burrows. Vertical burrows are the most common type of habitat.', 'Tilefishing is a fast growing sport and produces exceptional table fare. Not long ago, tilefish were pretty much unheard of as a rod and reel fish. 

Tilefish are probably the easiest of all the deep water fish to target. The golden tilefish is most commonly found in the 900–1,250 foot range. Smaller tiles, averaging 2–10 pounds, can be targeted on the continental shelf wall without any special areas or specific “numbers.” Muddy areas anywhere from 900–1,000 feet of open water will hold tilefish.

Finding better average sized fish will take a little more work. Tilefish will typically get bigger off the shelf, or in valleys against the shelf. Drop on the down current side of small dips and slopes in 1,000–1,250 feet of water. Tilefish tend to feed right on the bottom, so try to stop your bait and hold the boat on an area as tight as possible.

However, slow drifting will also produce tilefish and is great for covering ground. Drag the bait against the bottom, stopping often, and then continuing the drift to explore new areas.

Finding bigger tilefish is a different story altogether with the biggest ones typically holding against ridges at around 1,200 feet. They are bold enough to follow baits headed for deep water. Drop your bait near the edge of a ridge that looks over 1,500–1,600 feet of water and be ready. 

The biggest tiles, those from 35–50 pounds, seem to live alone. Many anglers catch these big fish away from the schools and many times, several feet off the bottom feeding in schools of squid or dragonfish. 

The big tilefish really don’t seem to like a lot of leader in their face. Single rigs with the weight above the bait seem to work best. A whole squid, about 14-inches-long, works very well. Use a large hook and bait to avoid the smaller fish when targeting big tiles.', 'Tilefish are able to reproduce when they reach 13 inches long and 3 pounds (approximately 2 to 4 years old). Although they were thought to be gonochoristic (staying one sex throughout their entire lifetime), recent research has concluded that tilefish off the East Coast of Florida and in the Gulf of Mexico are protogynous hermaphrodites (beginning as females and transitioning into males), like many grouper species.

Tilefish spawn from March to November in the Mid-Atlantic and South Atlantic and from January to June in the Gulf of Mexico. Spawning peaks in June (Mid-Atlantic) and from April to June (South Atlantic and Gulf of Mexico). Females release 2 to 8 million eggs when they spawn.', 'Tilefish feed during the day on the bottom, eating shrimp, crabs, clams, snails, worms, anemones, and sea cucumbers.

Monkfish, spiny dogfish, conger eels, large bottom-dwelling sharks (such as dusky and sandbar sharks), and other tilefish prey on juvenile tilefish.', 'Ocean', 'Stamina', '65 lb 3 oz,
Angelo Ruvio,
Poorman''s Canyon, New Jersey, USA,
8/8/2012', 'Tilefish WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Tarpon', 'Cuffum, Silver King', 'The Atlantic tarpon can grow to about 4–8 ft long and weigh 60–280 lbs. They have dorsal and anal soft rays and have bluish or greenish backs. Tarpons possess distinctive lateral lines and have shiny, silvery scales that cover most of their bodies, excluding the head. They have large eyes with adipose eyelids and broad mouths with prominent lower jaws that jut out farther than the rest of the face.', 'Megalopidae', 'Megalops atlanticus', 'Vulnerable', 'The Atlantic tarpon is found on the western Atlantic coast from Virginia to Brazil, throughout the coast of the Gulf of Mexico, and throughout the Caribbean. Tarpons are also found along the eastern Atlantic coast from Senegal to South Angola.

Tarpon are able to survive in brackish water, waters of varying pH, and habitats with low dissolved O2 content due to their swim bladders, which they use primarily to breathe. They are also able to rise to the surface and take gulps of air, which gives them a short burst of energy.

The habitats of the tarpon vary greatly with their developmental stages. Stage-one larvae are usually found in clear, warm, oceanic waters, relatively close to the surface. 

Stage-two and -three larvae are found in salt marshes, tidal pools, creeks, and rivers. The habitats are characteristically warm, shallow, dark bodies of water with sandy or mud bottoms. Tarpons commonly ascend rivers into freshwater. As they progress from the juvenile stage to adulthood, they move back to the open waters of the ocean, though many remain in freshwater habitats.

Tarpons prefer water temperatures of 72 to 82°F (22 to 28°C); below 60°F (15.6°C) degrees they become inactive, and temperatures under 40°F (4.5°C) can prove lethal.', 'Anglers seeking tarpon in passes, channels, deep bays and surf areas typically utilize stout tackle with lines testing at least 30 pounds. All sizes of spinning, baitcasting and fly tackle get lots of play for smaller fish. The same types of gear, although of heavier proportions, are also used for big fish on shallow flats. Use at least 15-pound line on spinning and casting gear, and at least a 10-weight fly outfit with minimum 16-pound tippet. Heavy monofilament leaders or tippets are required because of the tarpon’s very rough mouth. Drift fishermen in passes and inlets often prefer live baits which typically consist of small crabs and small fish. All Tarpon will take dead baits, such as a mullet head or half mullet, fished patiently on bottom. For trolling or surfcasting with heavier gear, large jigs, spoons and lipped plugs generally get the call. Casters typically enjoy the most success with swimming plugs, jerk plugs and surface plugs. Fly fishermen rely heavily on scissor-action feather streamers and bulky bucktail streamers

Tarpons jump up out of the water about four times when hooked making them very challenging to catch. These behaviors can also be damaging to anglers before they are hooked as they can also jump into boats and toward wading sportsman without warning.

Tarpon can only be fished recreationally in Florida. The majority of recreational anglers practice catch and release since the fish is not considered to be of any food value. However, anglers can possess them for trophy purposes at the cost of $50.00 per tag, per fish. Without this tag, possession of Tarpon, live or otherwise, is illegal.', 'Tarpons breed offshore in warm, isolated areas. Females have high fecundity and can lay up to 12 million eggs at once. They reach sexual maturity once they are about 75–125 cm in length. Spawning usually occurs in late spring to early summer.

Their three distinct levels of development usually occur in varying habitats. The first stage, the leptocephalus stage, or stage one, is completed after 20–30 days. It takes place in clear, warm oceanic waters, usually within 10–20 m of the surface. The leptocephalus shrinks as it develops into a larva; the most shrunken larva, stage two, develops by day 70. This is due to a negative growth phase followed by a sluggish growth phase. By day 70, the juvenile growth phase, stage three, begins and the fish begins to rapidly grow until it reaches sexual maturity.', 'Stage-one developing Megalops does not forage for food, but instead absorbs nutrients from seawater using integumentary absorption. Stage-two and -three juveniles feed primarily on zooplankton, but also feed on insects and small fish. As they progress in juvenile development, especially those developing in freshwater environments, their consumption of insects, fish, crabs, and grass shrimp increases. Adults are strictly carnivorous and feed on midwater prey; they swallow their food whole and hunt nocturnally.', 'Ocean', 'Aerial Acrobatics', '286 lb 9 oz,
Max Domecq,
Rubane, Guinea-Bissau,
3/20/2003', 'Atlantic Tarpon WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Hake, Silver', 'Whiting, Atlantic Hake, New England Hake', 'Silver hake are silvery in color, brownish on the back and whitish on the belly, with black speckles on the back and black inside the mouth. They have large heads for their size and sharp teeth. They have long pectoral fins and are fast swimmers. 
Silver hake can live as long as 14 years, although few fish older than age 6 have been observed in U.S. waters in recent years. They can grow to be more than 28 inches long and up to 5 pounds.', 'Merlucciidae', 'Merluccius bilinearis', 'Near Threatened', 'Silver hake are found in the Northwest Atlantic Ocean and range primarily from Newfoundland to South Carolina.

In U.S. waters, two stocks have been identified. The northern stock of silver hake inhabits the waters of the Gulf of Maine and Northern Georges Bank, and the southern stock inhabits the waters of Southern Georges Bank and the Mid-Atlantic Bight.

As nocturnal, semi-pelagic predators, silver hake move up in the water column to feed at night, primarily between dusk and midnight. They return to rest on the ocean bottom during the day, preferring sandy, muddy, or pebbly ocean bottoms.

Silver hake migrate in response to seasonal changes in water temperatures, moving toward shallow, warmer waters in the spring.

They spawn in these shallow waters during late spring and early summer and then return to deeper waters in the autumn. Older, larger silver hake prefer deeper waters.

During the summer, portions of both stocks can be found on Georges Bank. During the winter, fish in the northern stock move to deep basins in the Gulf of Maine, while fish in the southern stock move to outer continental shelf and slope waters.

Silver hake are widely distributed, and have been observed at temperature ranges of 2 to 17° C (36 to 63° F) and depth ranges of 11 to 500 meters (36 to 1,640 feet). However, they are most commonly found in temperatures between 7 and 10° C (45 to 50° F).', 'The silver hake, also know as whiting, is one of the less glamorous fish found in the waters of the Atlantic Ocean. Coming into the shallower waters within reach of the recreational anglers only in the coldest months, it is not an important quarry of the sportsfishermen. However, being plentful at a time of year when many other species are not, it is sought by the commercial fishing fleet.', 'Female silver hake are serial spawners, producing and releasing up to three batches of eggs in a single spawning season.
Spawning areas include the coastal region of the Gulf of Maine from Cape Cod to Grand Manan Island, southern and southeastern Georges Bank, and the southern New England area south of Martha’s Vineyard.

Their peak spawning occurs earlier in the south (May to June) than in the north (July to August).

More than half of 2-year-old silver hake and virtually all 3-year-olds are sexually mature.', 'Silver hake are important to the northwest Atlantic ecosystem both as prey and predators. They are voracious predators and feed on fish, crustaceans, and squid.', 'Ocean', 'Subpar Game Qualities', '4 lb 8 oz,
Erik Callahan,
Perkins Cove, Ogunquit, Maine, USA,
8/8/2015', 'Silver Hake WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Bass, Striped', 'Atlantic Striped Bass, Linesider, Pimpfish, Rock, Rock Fish, Striper', 'The Striped Bass is the largest member of the temperate bass family. 

Body coloration is olive-green to blue-gray on the back with silvery to brassy sides and white on the belly. It is easily recognized by the seven or eight prominent black uninterrupted horizontal stripes along the sides. The stripes are often interrupted or broken and are usually absent on young fish of less than six inches. 

The Striper is longer and sleeker and has a larger head than its close and similar looking relative, the White Bass, which rarely exceeds three pounds.

Large Stripers weighing over fifty pounds are commonly caught in freshwater lakes, however the largest of this species are most often taken from the ocean or coastal waterways. The largest recorded striped bass, weighing 125 pounds, was caught off the North Carolina coast in 1891.', 'Moronidae', 'Morone saxatilis', 'Least Concern', 'Striped bass can be found on the Atlantic coast of the United States, from northern Florida to the St. Lawrence estuary in southeastern Canada. This species has been introduced to many inland lakes and reservoirs in the Mid-Atlantic, Midwest, as well as, the Pacific coast of the United States.', 'Striped bass are of significant value for sport fishing, and have been introduced to many waterways outside their natural range. 

A variety of angling methods are used, including trolling, surf casting, topwater presentations, as well as bait casting with live and deceased bait. 

Striped bass will take a number of live and fresh baits, including bunker, clams, eels, sand worms, herring, bloodworms, mackerel, and shad, with the latter being an excellent bait for freshwater fishing as well.

The largest striped bass ever taken by angling was an 81.88-lb (37.14-kg) specimen taken from a boat in Long Island Sound, near the Outer Southwest Reef, off the coast of Westbrook, Connecticut. 

The all-tackle world record fish was taken by Gregory Myerson on the night of August 4, 2011. The fish took a drifted live eel bait, and fought for 20 minutes before being boated by Myerson. A second hook and leader was discovered in the fish''s mouth when it was boated, indicating it had been previously hooked by another angler. The fish measured 54 in length and had a girth of 36 in. 

The International Game Fish Association declared Myerson''s catch the new all-tackle world record striped bass on October 19, 2011.

In addition to now holding the All-Tackle record, Meyerson''s catch also landed him the new IGFA men’s 37-kg (80-lb) line class record for striped bass, which previously stood at 70 lb. 

The previous all-tackle world record fish was a 78.5-lb (35.6-kg) specimen taken in Atlantic City, New Jersey on September 21, 1982 by Albert McReynolds, who fought the fish from the beach for 1 hour 20 minutes after the colossal striper took his Rebel artificial lure.

Recreational bag limits vary by state and province.', 'Striped bass are and anadromous fish species. They spawn in fresh water, and although they have been successfully adapted to freshwater habitat, they naturally spend their adult lives in saltwater. 

Four important bodies of water with breeding stocks of striped bass are the Chesapeake Bay, Massachusetts Bay/Cape Cod, Hudson River, and Delaware River. 

One of the largest breeding areas is the Chesapeake Bay, where populations from Chesapeake and Delaware bays have intermingled. There are very few successful spawning populations of freshwater striped bass whose spawning waters include Lake Texoma, Lake Weiss (Coosa River), the Colorado River and its reservoirs downstream from and including Lake Powell, Lake Mead and the Arkansas River, as well as Lake Marion (South Carolina) that retained a landlocked breeding population when the dam was built. 

Other freshwater fisheries must be restocked with hatchery-produced fish annually. Stocking of striped bass was discontinued at Lake Mead in 1973 once natural reproduction was verified.', 'Striped bass are voracious and opportunistic feeders. Larvae feed on zooplankton while juveniles consume small shrimp and crustaceans, annelid worms, and insects.

Adults feed on a wide variety of other fish species (alewives, herring, smelt, eels, flounders, mummichogs, rock gunnels, sand lance, silver hake and silversides as well as invertebrates (squid, crabs, sea worms and amphipods and crustaceans). Feeding ceases shortly before spawning.', 'Ocean', 'Sight Casting Target', '81 lb 14 oz,
Gregory Myerson,
Long Island Sound, Westbrook, CT, USA,
8/4/2011', 'Striped Bass WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Roosterfish', 'Papagallo, Pex Gallo,', 'Roosterfish have elongated compressed bodies that are bluish gray in color with silvery reflections. They have four dark bars, one between their eyes, one across the rear part of their head, two obliquely curved black bands on their sides, one of which extends down the center of the caudal base. Their head is pointed and features simple teeth. Their first dorsal fin has seven spines the last six of which are very elongated; the second dorsal fin has one spine and 25 rays. Their anal fin base is much shorter than their dorsal fin base. Their caudal fin is deeply forked; they have long and curved pectoral fins that are longer than their pelvic fins.

The distinctive high, comblike dorsal fin of a lit-up roosterfish cutting through green inshore waters, hot on the trail of a live bait or popper, is one of sport fishing’s most memorable sights. Roosters are unique to the eastern Pacific, where they’re caught from Baja into northern South America. Once thought to be a species of jack (Carangidae), roosters are in fact in their own family. They do, however, certainly fight with jacklike stubbornness and power — but add to that fight the ability to jump, which further explains their appeal as game fish. Roosters are fish of beaches and rocky shores. They can reach weights in excess of 100 pounds. The IGFA record of 114 pounds set in 1960 still stands from La Paz, Mexico.', 'Nematistiidae', 'Nematistius pectoralis', 'Not Evaluated', 'Roosterfish are unique to the warmer waters of the East Pacific from Baja California to Peru. They are generally caught within ¼ of a mile of the shoreline, along sandy beaches, rocky points and outcroppings, and near river estuaries. However, they are also taken crashing on bait, mixed in with schools of jack crevalle, more than a mile off the beach.

Roosterfish prefer water of 80º F or warmer in the southern regions, but are very active in 76° water in the northern reaches.

It must be emphasized when roosters are in shallow water, they are actively feeding, and when they get their fill, they return to the safety of deeper water. This is the main reason casting a surface popper to the back side of the waves is effective.

River estuaries build up a sand bar in the dry season, which gets blown out in the summer rain season, but fresh water still leaks through the pervious sand in the other months. Fresh water runoff is loaded with nutrients and creates its own micro eco-system, attracting bait fish, and on up the food chain for game fish - including roosters. This is true along most coast lines of the roosterfish habitat, with the desert areas of Baja being the exception (because they have few rivers or water in those rivers year round). River estuary mouths, along the coast of 90% of the rooster’s habitat are an excellent place to start looking for them.

Plus, when the rain season is in full force, the heavy outflows from the rivers can discolor the water. Even though it is difficult, we have saved the day a few times by working a teaser along the well defined break of the discolored water and the clean water, which can be as much as ¼ mile off the beach. The discolored fresh water may only be 3 or 4 feet thick, and the roosters hide under it ambushing bait swimming along the edge.

When the muddy water is so widespread and just makes it almost impossible to fly fish for roosters, you can still catch them with conventional gear. The muddy water is 3 or 4 feet thick, so by rigging a live bait with a circle hook, or a dead bait with a chin weight and a circle hook, you troll the bait down in the clear water. Using a surface popper helps to attract fish to your trolled bait by the vibrations and racket it makes on the surface. The rooster can’t see the popper, yet will get agitated and goes into the feed mode. Your trolled bait will soon be inhaled.

Often when we “run and gun” trying to find the concentrations of fish, we only hit the river mouths, unless we see birds first, and then we work that area. Birds do not have be diving either. It just takes a few of them sitting on the water, or standing on the shoreline. Either something had happened there earlier, or they know something we don’t, and are just waiting for it to happen. It can pay off big time to work these areas also.

The open beaches often produce an incredible amount of roosters, with nothing on them to justify for structure. There are no bait fish you can see, or birds, but the roosters can be there. Sometimes the beach areas show swirls of sand and darker colored water in a small area, indicative of a submerged tree or maybe some rock structure below. But, usually it is just an open beach with small concentrations of roosters in a stretch of a couple of hundred yards. This is where time on the water and using a method to quickly cover a lot of water pays off.

Rocky points will have roosters also, especially if there are sand beaches on either side. Structure holds bait and they are there to pin the bait up against the rock walls, when the bait escape, they move to the sandy beach alongside the point. And, the roosters follow.

Offshore islands with vertical walls have a lot of roosters, but they are waiting in the 50 to 100 foot deeper water below for a school of bait fish to come along, in order to pin against the rocks, taking away a couple of dimensions of escape. These fish are usually best left to the conventional angler slow trolling a live bait on a down rigger or diving plane. It is very difficult to tease up a rooster from deep water. However, if the birds are crashing, you have to at least give it a try to see what species have driven the bait to the surface. And, if it is not roosters or roosters mixed in with a school of jacks, it can still be a lot of fun on light gear.', 'Roosterfish are a light tackle fisherman''s dream.  Like all fish in the Jack family they fight hard, but unlike some Jacks they do not generally go into rocks event though they often live near rocky areas. Therefore, you can land some pretty big fish on pretty light tackle. An Accurate BX500 reel should handle pretty much any roosterfish. 

Roosterfish readily attack several baits and lures, but are typically much easier to catch on live bait than lures. If you want to maximize your chances you should slow troll a large live baitfish. Roosterfish will sometimes play with the bait for a while, so you have to wait until you are sure they have engulfed the bait before setting the hook. Quality live bait choices are live skipjack tuna in the 3-4lb range, small fish in the jack family and ladyfish if you can catch them.  

Roosterfish are often seen feeding at the surface as the splash around chasing baitfish. Most roosterfish, especially the bigger ones, are generally not easy to land on lures. They will sometimes take poppers that are retrieved rapidly, but more often than not they just follow the lure and then turn away. They will occasionally take trolled Rapala-type plugs but you probably don''t want to rely on that as a first option.', 'The reproduction of roosterfish is not well known. Likely a pelagic spawner, with pelagic eggs and larvae. They may spawn in groups and it is thought that the spawn is seasonal, especially at higher latitudes.', 'Roosterfish generally feed fairly close to shore, sometimes almost beaching themselves as they chase bait fish in the surf. Some big ones are occasionally landed from shore due to this feeding habit.', 'Ocean', 'Fight Dynamics', '114 lb,
Abe Sackheim,
La Paz, Baja California, Mexico
6/1/1960', 'Roosterfish WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Shark, Sand Tiger', 'Spotted Ragged-tooth Shark, Grey Nurse Shark, Sand Tiger Shark, Grey Nurse Shark, Spotted Raggedtooth Shark, Blue Nurse Sand Tiger', 'Despite its name, the sand tiger shark is not related to the tiger shark Galeocerdo cuvier; however, it is a cousin of the great white shark Carcharodon carcharias. Adult sand tigers range from 6.6 ft (2 m) to 10.5 ft (3.2 m) in length and 200.6 lb (91 kg) to 350.5 lb (159 kg) in weight.

The head is pointy, as opposed to round, while the snout is flattened with a conical shape. Its body is stout and bulky and its mouth extends beyond the eyes. The eyes of the sand tiger shark are small, lacking eyelids. A sand tiger usually swims with its mouth open displaying three rows of protruding, smooth-edged, sharp-pointed teeth.

Male sand tigers have gray claspers with white tips located on the underside of their body. The caudal fin is elongated with a long upper lobe (i.e. strongly heterocercal). They have two large, broad-based gray dorsal fins set back beyond the pectoral fins. The sand tiger shark has a grey-brown back and pale underside. Adults tend to have reddish-brown spots scattered, mostly on the hind part of the body. The teeth of these sharks have no transverse serrations (as have many other sharks) but they have a large, smooth main cusp with a tiny cusplet on each side of the main cusp. The upper front teeth are separated from the teeth on the side of the mouth by small intermediate teeth.

The sand tiger is often associated with being vicious or deadly, due to their relatively large size and sharp, protruding teeth that point outward from their jaws, however they are quite docile, and are not a threat to humans. Sand tigers roam the surf, sometimes in close proximity to humans, and there have been only a few instances of unprovoked sand tiger shark attacks on humans which were usually associated with spear fishing, line fishing or shark feeding. As of 2013, the database of Shark Attack Survivors does not list any fatalities due to sand tiger sharks. When the sharks become aggressive, they tend to steal the fish or bait rather than attack humans. Due to its large size and docile temperament, the sand tiger is commonly displayed in aquariums around the world.', 'Odontaspididae', 'Carcharias taurus', 'Vulnerable', 'Historically, the sand tiger shark is regarded as having a broad inshore distribution, primarily in subtropical to warm temperate waters around the main continental landmasses, except in the eastern Pacific off North and South America. In the Western Atlantic, this shark occurs from the Gulf of Maine to Florida (USA), in the northern Gulf of Mexico, around the Bahamas and at Bermuda, and also from southern Brazil to northern Argentina. In the eastern Atlantic it is found from the Mediterranean to the Canary Islands, at the Cape Verde Islands, along the coasts of Senegal and Ghana, and from southern Nigeria to Cameroon. In the western Indian Ocean it ranges from South Africa to southern Mozambique, but does not occur around Madagascar. This species has also been reported from the Red Sea and may occur as far east as India. In the western Pacific, it has been reported from Japan and Australia, but not New Zealand.', 'Only the heaviest sporting outfits will suffice with adult tigers. Like most sharks, chunks of dead fish or cutbait are one of the top choices for bait, but large live baits have been known to work as well.', 'Mating occurs around the months of March and April in the northern hemisphere and during August–October in the southern hemisphere. The courtship and mating of sand tigers has been best documented from observations in large aquaria. 

In Oceanworld, Sydney, the females tended to hover just above the sandy bottom ("shielding") when they were receptive. This prevented males from approaching from underneath towards their cloaca. Often there is more than one male close by with the dominant one remaining close to the female, intimidating others with an aggressive display in which the dominant shark closely follows the tail of the subordinate, forcing the subordinate to accelerate and swim away. The dominant male snaps at smaller fish of other species. The male approaches the female and the two sharks protect the sandy bottom over which they interact. 

Strong interest of the male is indicated by superficial bites in the anal and pectoral fin areas of the female. The female responds with superficial biting of the male. This behavior continues for several days during which the male patrols the area around the female. 

The male regularly approaches the female in "nosing" behavior to "smell" the cloaca of the female. If she is ready, she swims off with the male, while both partners contort their bodies so that the right clasper of the male enters the cloaca of the female. The male bites the base of her right pectoral fin, leaving scars that are easily visible afterwards. 

After one or two minutes, mating is complete and the two separate. Females often mate with more than one male. Females mate only every second or third year. After mating, the females remain behind, while the males move off to seek other areas to feed, resulting in many observations of sand tiger populations comprising almost exclusively females.', 'The sand tiger shark is a nocturnal feeder. The majority of prey items of sand tigers are demersal (i.e. from the sea bottom), suggesting that they hunt extensively on the sea bottom as far out as the continental shelf. 

Bony fish (Teleosts) form about 60% of sand tigers food, the remaining prey comprising sharks and skates. In Argentina, the prey includes mostly demersal fishes, e.g. the striped weakfish (Cynoscion guatucupa). 

The most important elasmobranch prey is the bottom-living smooth-hound shark (Mustelus sp.). Benthic (i.e. free-swimming) rays and skates are also taken. 

Stomach content analysis indicates that smaller sand tigers mainly focus on the sea bottom and as they grow larger they start to take more benthic prey. This perspective of the diet of sand tigers is consistent with similar observations in the north west Atlantic and in South Africa where large sand tigers capture a wider range of shark and skate species as prey, from the surf zone to the continental shelf, indicating the opportunistic nature of sand tiger feeding.

Off South Africa, sand tigers less than 6 ft (2 m) in length prey on fish about a quarter of their own length; however, large sand tigers capture prey up to about half of their own length. The prey items are usually swallowed as three or four chunks.', 'Ocean', 'Strength (as Related to Size)', '350 lb 2 oz,
Mark Thawley,
Charleston Jetty, South Carolina, USA,
4/29/1993', 'Sand Tiger Shark WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Flounder, Summer', 'Flounder, Fluke, Northern Fluke, Hirame', 'Summer flounder are fast growing flat bodied fish, but have a relatively short life, about 12 to 14 years. Males grow to more than 2 feet in length and females grow up to 3 feet. They’re able to reproduce when they reach age 2 or 3 . 

Summer flounder are white below and some shade of brown, gray, or drab above. Flounder are nicknamed “chameleons of the sea” because they’re able to change their coloring to blend in with the texture and color of the bottom where they live. There are several species of flounder with many being either right or left-eyed flatfish (both eyes are on the left side of the body when viewed from above with the dorsal fin facing up). When larvae develop into juveniles, the right eye moves across the top of the head to the left side.', 'Paralichthyidae', 'Paralichthys dentatus', 'Least Concern', 'Summer flounder are found in the Atlantic Ocean from Nova Scotia to the east coast of Florida. In U.S. waters, summer flounder are most common in the mid-Atlantic region from Cape Cod, Massachusetts, to Cape Fear, North Carolina.

Larval summer flounder live in estuaries and coastal lagoons. Juveniles burrow in the sediment in marsh creeks, seagrass beds, mud flats, and open bays, notably Pamlico Sound and Chesapeake Bay. Because this important life stage takes place near heavily populated urban areas, maintaining good water quality is important for successful growth and survival of young summer flounder.

Adults spend most of their lives on or near the seafloor burrowing in the sand. They’re also found in marsh creeks, seagrass beds, and sand flats. Adult summer flounder migrate inshore and offshore seasonally with changes in water temperature. In the winter and early spring, they’re found offshore along the outer edge of the continental shelf. In late spring and early summer, they move inshore into shallow coastal waters and estuaries. Summer flounder migrate back offshore in the fall.', 'In areas that have a clean sandy bottom, slip a free sliding 1 to 2 ounce No Roll tear drop shaped sinker onto the line of your favorite rod and reel.  Using a swivel, tie on twenty to thirty inches of 30 pound test monofilament leader line tipped with a 2/0 to 3/0 hook.  The idea here is to cast a lip hooked live mud minnow or finger mullet into the choke point gaps.  Allow the sinker to settle on the bottom, after a few minutes slowly raise the sinker off the bottom while retrieving three or four feet of line.  Once again allow the sinker to settle on the bottom thus pulling the bait down into the striking range of the Flounder.  Slowly walking the bait back toward you in this manner covers more ground and increases the chances of a strike.  This method is most effective when retrieving the bait against the current so, if possible, set up accordingly. 

Flounder fishing tips for fishing over grassy areas or a sparsely debris covered bottom which might cause a bottom fishing rig to get hung up include using a 1 to 2 ounce jig tipped with live lip hooked minnow or tail hooked shrimp.  This baited jig must be fished so it is retrieved swimming close to the bottom within the striking range of a Flounder.  This method takes a little practice and can work equally will if the jig is rigged with a soft plastic lure.

Flounder fishing tips change somewhat in the Spring because these fish, while still offshore, will move onto near shore reefs in preparation for a return into the estuaries.  These near shore areas are in relatively deep water generally 40 feet or more.  The best bet here is to use a medium to heavy rod.  Use a bottom rig to fish straight down under the boat.  Fishing straight down under the boat often helps from constantly getting hung up, especially if slowly drifting over the site.  A heaver sinker is required to get the bait down to the bottom quickly, generally 6 ounces or more, but otherwise the leader line is about the same as discussed above.  The ideal bait is live mud minnows which can be caught with a cast net before you head offshore.  Keep in mind that these fish are schooled up so odds are if you catch one there are many other Flounder around.

As summer approaches and water temperatures warm, the Flounder will once again move into the inshore bays and channels as well as along the beaches.  Look for areas that hold bait fish or shrimp.  Use periods of low tide to scout for potholes in the sand created by feeding Flounder before they were forced to seek deeper water because of the dropping tide.  Also, look for areas offset from strong flowing currents which hold relatively calm water.  Bait fish will often school in these areas and Flounder will take advantage of these spots.  Plus, do not over look docks, edges of jetties, or other structures that may hold bait.  Bottom fishing rigs and jigs work well in the summer.

One last Flounder fishing tip about the end of summer Flounder migration.  Because these fish move into the shallows at night to feed, using a spotlight for nighttime Flounder gigging has become a popular method for harvesting these tasty fish.', 'Summer flounder spawn in the fall and early winter when they migrate offshore. They spawn several times throughout the spawning season.

Spawning peaks in October and November when water temperatures change and autumn plankton is most productive. The combination of these elements improves the chance of survival for larval summer flounder.

Depending on their size, females have between 460,000 and more than 4 million eggs. They release the eggs into the water column and the eggs hatch in waters of the continental shelf. Newly hatched larvae move with the currents toward coastal areas, where they develop into juveniles.', 'Summer flounder eat a mixed diet of fish and invertebrates throughout their life.

Larval and post-larval flounder feed on zooplankton (tiny floating animals) and small crustaceans. Juveniles eat crustaceans and fish.

Adults are opportunistic feeders, eating whatever food is convenient at the time, and feed mostly on fish and crustaceans.

Summer flounder lay on the ocean floor concealed, partly by sand and partly by their coloration, and wait for their prey to swim by. When suitable prey appears, flounder ambush them.

Larval and juvenile summer flounder are preyed upon until they grow large enough to fend for themselves. Predators include spiny dogfish, monkfish, cod, hakes, sea raven, longhorn sculpin, and fourspot flounder. Large sharks, rays, and monkfish prey on adult summer flounder.', 'Ocean', 'Strength (as Related to Size)', '22 lb 7 oz,
Capt. Charles Nappi,
Montauk, New York, USA,
9/15/1975', 'Summer Flounder WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Flounder, Winter', 'Flounder, Sole, Lemon Sole, Georges Bank Founder, Blackback Flounder', 'Winter flounder have an oval shape and a thick body. Their eyes are on the right side of their body. They have a straight lateral line and dark coloring. Their coloring often varies with their habitat, ranging from muddy to slightly reddish brown, olive green, or dark slate, to an almost black upper side. Their underside is white, and their dorsal and anal fins are often tinged with pink, red, or yellow.', 'Pleuronectidae', 'Pseudopleuronectes americanus', 'Not Evaluated', 'Winter flounder are found in estuaries and on the continental shelf of the Northwest Atlantic, from the Gulf of St. Lawrence, Canada to North Carolina. They are most common north of Delaware Bay.

Winter flounder get their name because of their migrations. In the winter, adults migrate from offshore areas where they feed to inshore bays and estuaries where they spawn.

While inshore, they live on muddy sand, clean sand, clay, and pebbly or gravelly bottom habitats.

They often bury their whole body, except for their eyes, in bottom sediments. Larvae and some 1-year-olds live in the estuaries where they were born. Juveniles prefer sand or sand-silt bottoms with a wide range of salinity and temperature.', 'Early spring through May usually is the target time for winter flounder, but these fish will sometimes linger a bit longer in the bays. The first thing to consider is a sunny day, with an outgoing tide. Probably the last two or three hours of the out going and the beginning of the incoming tide are the best generally because of the warmer water flowing and the small baits that these toothless fish feed on are being washed off the flats into the channels and channel slopes.

Soft muddy bottoms of bays and creeks are the prime fish holding locations. Water depth fished here locally should be in the 8 to 11 foot range, but this is a matter of trial and error to locate the holes that are holding the greatest concentration of fish. As the water warms and spawning is done with , the fish will start to move closer to the inlets and then offshore.

A chum pot is an absolute  requirement. In fact many use 2 chum pots at the same time. You will want to move or jiggle the chum pot from time to time to stir the bottom up and create a greater flow of chum. Some will also attach a plumber''s plunger to the end of a long pole and periodically plunge and stir the bottom up. A mushroom style weight of 5-8 ounces (decoy anchor) attached to a cord can be used in the same way to stir the bottom, as well as a sash weight. Don''t be stingy with the chum. The more you have the greater the chances of increasing the catch. The chum will consist of ground up clams, ground up mussels, grass shrimp, a mixture of whole kernel frozen or canned corn and cooked rice flavored with clams, squid, or most any oily addition to increase the odor. Most bait shops will have frozen chum logs  of mussel and clam to fit into the chum pots.

Baits will be primarily bloodworms, sand worms, grass shrimp, strips of mussel or clam. Baits should be small, probably no longer than 2 inches in length, with 1/2 or more of this length dangling free off the hook. Remember that these fish – even the two pounders – have very small mouths so baits and gear should be sized accordingly.

Anchoring techniques are somewhat critical, because the boat should be as stationary as possible. Bridling, often is best and the use of two anchors is highly recommended. Flounder Fishing at the beginning of the season on a nice sunny day in March and April can be a great way to start the fishing season plus the bonus of catching some of the tastiest fish that swim in our waters.', 'Winter flounder live 15 to 18 years and grow to more than 2 feet in length. 

They spawn during the winter and spring in shallow inshore waters, often returning to the same areas where they were born to spawn. Females usually produce between 500,000 and 1.5 million eggs. They deposit their eggs on sandy bottoms and algal mats at night, usually about 40 times every spawning season.

Newly hatched larvae have one eye on each side of the head. Five to six weeks after they hatch, larvae settle to the bottom to begin their transformation into juveniles. After weeks of adapting to living on the bottom, their left eye migrates to the right side of their body and their metamorphosis is complete.

The growth and survival rates of larvae and juveniles depend on several factors, including temperature, salinity, water quality, and the availability of food.', 'Winter flounder feed during the day because they depend on sight to locate prey. Their small mouths limit what they can eat. They feed on small invertebrates, shrimp, clams, and worms.

Fish (mainly striped bass, bluefish, toadfish, and summer flounder), birds, invertebrates, winter skate, and marine mammals prey on larval and juvenile winter flounder.

Atlantic cod, spiny dogfish, and monkfish prey on adults.', 'Ocean', 'Strength (as Related to Size)', '7 lb,
Dr. Einar Grell,
Fire Island, New York, USA,
5/8/1986', 'Winter Flounder WR');
