-- Import batch from saltwater_batch_01.json
-- Total records: 10

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Shark, Whitetip Reef', 'Brown Milbert''s Sand Bar Shark, Brown Shark, Nigano Shark, Oceanic White-Tipped Whaler, Silvertip Shark', 'A relatively small species, few whitetip reef sharks are longer than 5.2 ft (1.6 m). The maximum length this species attains is often given as 6.9 ft (2.1 m), though this was originally based on visual observations and may be dubious. The maximum reported weight is 40 lb (18.3 kg). The whitetip reef shark has a slim body and a short, broad head. The snout is flattened and blunt, with large flaps of skin in front of the nares that are furled into tubes. The eyes are small and oval with vertical pupils and prominent ridges above, and are often followed by a small notch. The mouth has a distinct downward slant (imparting a disgruntled expression to the shark), with short furrows at the corners. There are 42–50 tooth rows in the upper jaw and 42–48 tooth rows in the lower jaw. Each tooth has a single narrow, smooth-edged cusp at the center, flanked by a pair of much smaller cusplets.

The first dorsal fin is positioned well back on the body, closer to the pelvic than the pectoral fins. The second dorsal and anal fins are large, about half to three-quarters as high as the first dorsal fin. The broad, triangular pectoral fins originate at or slightly before the level of the fifth gill slit. There is no ridge between the first and second dorsal fins. The lower lobe of the caudal fin is half the length of the upper, which has a strong notch near the tip. The dermal denticles are small and overlapping, usually with 7 horizontal ridges, giving the skin a smooth feel. The coloration is grayish to brownish above and white below, with a pattern of scattered small, dark spots unique to each individual. The tips of the first dorsal fin and upper caudal fin lobe, and sometimes also the second dorsal fin and lower caudal fin lobe, are bright white.', 'Carcharhinidae', 'Carcharhinus longimanus', 'Vulnerable', 'The Whitetip Reef Shark is distributed widely across the entire Indo-Pacific region. It was once thought to have formerly existed in the Atlantic Ocean, based on fossil teeth found in North Carolina dating to the Miocene epoch. However, more recent research indicates that the teeth belonged to a mackerel shark, and that this species has never colonized the Atlantic.

In the Indian Ocean, it occurs from northern KwaZulu-Natal, South Africa to the Red Sea and the Indian subcontinent, including Madagascar, Mauritius, the Comoros, the Aldabra Group, the Seychelles, Sri Lanka, and the Chagos Archipelago. In the western and central Pacific, it occurs from off southern China, Taiwan, and the Ryukyu Islands, to the Philippines, Southeast Asia, and Indonesia, to northern Australia, and is also found around numerous islands in Melanesia, Micronesia, and Polynesia, as far as Hawaii to the north and the Pitcairn Islands to the southeast. In the eastern Pacific, it occurs from Costa Rica to Panama, and off the Galápagos Islands.

Associated almost exclusively with coral reef habitats, whitetip reef sharks are most often encountered around coral heads and ledges with high vertical relief, and additionally over sandy flats, in lagoons, and near drop-offs to deeper water. They prefer very clear water and rarely swim far from the bottom. This species is most common at a depth of 26–131 ft (8–40 m).

On occasion, whitetips may enter water less than 3 ft (1 m) deep, and there is an exceptional record of a whitetip reef shark being captured from a depth of 1,080 ft (330 m) in the Ryukyu Islands.', 'Whitetip sharks are small in size, but will strike baits, lures and flies fairly aggressively.', 'Like other members of its family, the whitetip reef shark is viviparous; once the developing embryos exhaust their supply of yolk, the yolk sac is converted into a placental connection through which the mother delivers nourishment for the remainder of gestation. Mature females have a single functional ovary, on the left side, and two functional uteruses. The reproductive cycle is biennial.

Mating is initiated when up to five males follow closely behind a female and bite at her fins and body, possibly cued by pheromones indicating the female''s readiness. Each male attempts to seize the female by engulfing one of her pectoral fins; at times two males might grasp a female on both sides simultaneously. Once engaged, the sharks sink to the bottom, whereupon the male (or males) rotate(s) one of his claspers forward, inflates the associated siphon sac (a subcutaneous abdominal organ that takes in seawater that is used to flush sperm into the female), and attempts to make contact with the female''s vent. In many cases, the female resists by pressing her belly against the bottom and arching her tail; this may reflect mate choice on her part. The male has a limited time in which to achieve copulation, as while he is holding the female''s pectoral fin in his mouth he is being deprived of oxygen. On the other hand, if the female is willing, the pair settles side-by-side with their heads pressed against the bottom and their bodies at an upward angle.

After a gestation period of 10–13 months, females give birth to litters of 1–6 (usually 2–3) pups. The number of offspring is not correlated with female size; each female produces an estimated average of 12 pups over the course of her lifetime. Parturition occurs from May to August (autumn and winter) in French Polynesia, in July (summer) off Enewetak Atoll, and in October (summer) off Australia. Females give birth while swimming, making violent twists and turns of their bodies; each pup takes under an hour to fully emerge. The newborns measure 52–60 cm (20–24 in) long and have relatively longer caudal fins than adults. This shark develops slowly compared to other requiem sharks; newborns grow at a rate of 16 cm (6.3 in) per year while adults grow as a rate of 2–4 cm (0.79–1.57 in) per year. Sexual maturity is reached at a length of around 1.1 m (3.6 ft) and an age of 8–9 years, though mature males as small as 95 cm (37 in) long have been recorded from the Maldives, suggesting regional variation in maturation size. On the Great Barrier Reef, males live to 14 years and females to 19 years; the maximum lifespan of this shark may be upwards of 25 years.', 'With its slender, lithe body, the whitetip reef shark specializes in wriggling into narrow crevices and holes in the reef and extracting prey inaccessible to other reef sharks. Alternatively, it is rather clumsy when attempting to take food suspended in open water. This species feeds mainly on bony fishes, including eels, squirrelfishes, snappers, damselfishes, parrotfishes, surgeonfishes, triggerfishes, and goatfishes, as well as octopus, spiny lobsters, and crabs.

The whitetip reef shark is highly responsive to the olfactory, acoustic, and electrical cues given off by potential prey, while its visual system is attuned more to movement and/or contrast than to object details. It is especially sensitive to natural and artificial low-frequency sounds in the 25–100 Hz range, which evoke struggling fish.

Whitetip reef sharks hunt primarily at night, when many fishes are asleep and easily taken. After dusk, groups of sharks methodically scour the reef, often breaking off pieces of coral in their vigorous pursuit of prey. Multiple sharks may target the same prey item, covering every exit route from a particular coral head. Each shark hunts for itself and in competition with the others in its group. Unlike blacktip reef sharks and grey reef sharks, whitetip reef sharks do not become more excited when feeding in groups and are unlikely to be stirred into a feeding frenzy. 

Despite their nocturnal habits, whitetip reef sharks will hunt opportunistically in daytime. Off Borneo, this species gathers around reef drop-offs to feed on food brought up by the rising current. Off Hawaii, they follow Hawaiian monk seals (Monachus schauinslandi) and attempt to steal their catches. A whitetip reef shark can survive for six weeks without food.', 'Ocean', 'Strength of/Willingness to Strike', '40 lb 4 oz,
Dr. Jack Kamerman,
Isla Coiba, Panama,
8/8/1979', 'Whitetip Reef Shark');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Spearfish, Longbill', 'Atlantic Longbill Spearfish, Atlantic Spearfish, Atlantic Lognbill, Longbill', 'The longbill spearfish is a blueish black color from above, and silvery-white and brown on the sides to white underneath. The pectorals are blackish-brown and the dorsal fins are dark blue. The upper jay is prolonged into a spear and its cross section is round. Longbill spearfish are found offshore in deep water.', 'Istiophoridae', 'Tetrapturus pfluegeri', 'Least Concern', 'The longbill spearfish is known to occur in the northwest Atlantic from New Jersey to Venezuela, including the Gulf of Mexico.', 'The best method for catching longbill spearfish is saltwater trolling. Fishing methods are the same as for other billfish, but with lighter tackle. Most are taken incidentally. Top baits for longbows are saltwater live bait, squid and trolling lures.', 'Longbill spearfish are uncommon.  Available data indicate that this spearfish matures at 2 years of age and rarely lives past 4 to 5 years.', 'Longbill spearfish are pelagic and feed at or near the surface, mainly on fishes and squid.', 'Ocean', 'Aerial Acrobatics', '127 lb 13 oz,
Paul Cashmore,
Puerto Rico, Gran Canaria, Canary Islands, Spain,
5/20/1999', 'Longbill Spearfish WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record)
VALUES ('Salt', 'Sturgeon, White', 'California White Sturgeon, Columbia Sturgeon, Oregon Sturgeon, Pacific Sturgeon, Sacramento Sturgeon', 'The white sturgeon has a slender, long body, head, and mouth. This fish has no scales; instead, it has large bony scutes that serve as a form of armor. Its 11–14 dorsal scutes are all anterior to the dorsal fin, and 38–48 lateral scutes and 9–12 ventral scutes are on each side. The dorsal color of a white sturgeon is gray, pale olive, or gray-brown. The fins are a dusky, opaque gray. The underside is a clean white. It has four barbels, used for sensing food, near its large, toothless mouth.

Sturgeons are classified as a bony fish, but actually are more cartilaginous than bony, their internal bone structure being more like a shark''s. Sturgeon have changed very little since they first appeared over 175 million years ago and as such have the appearance of being prehistoric.', 'Acipenseridae', 'Acipenser transmontanus', 'Least Concern', 'The white sturgeon lives on the bottom of slow-moving rivers, bays, and estuarine areas, including the brackish water at the mouths of large rivers. Other sturgeon spend most of their time in a marine environment, only coming into rivers to spawn. They are well-adapted to finding food drifting by with their excellent sense of smell and taste. When the food supply is insufficient, sturgeon have been known to move into shallow water to eat freshwater clams.', 'Fishing for the white sturgeon is limited to Oregon and California primarily in north america. Current sport fishing regulations as imposed by the Oregon Department of Fish and Wildlife state that sturgeon may only be kept if measuring between 38 and 54 inches (96.5–137 cm) from the nose to the tail fork. 

In most years, anglers'' regulations change frequently to limit the number of fish caught. Once the annual quota is reached, retention of sturgeon is no longer allowed. 

Also, one may only use a single-point barbless hook. Bait used for sturgeon is mostly its natural prey including shad, anchovies, shrimp, and smelt, however, more unusual baits are sometimes used -these baits include cheese, anchovies, pickled squid, dog food, and cat food.', 'During the spawning season, the white sturgeon moves to clean, fast-moving areas of rivers, such as just below rapids, with gravel or larger rocks along the bottom.

White sturgeon spawn many times in their lives. As they age, the females spawn less often, but produce more eggs in each spawning. In the late spring or early summer, they congregate in areas of rivers with a heavy current, gravel bottom, and a water temperature of 58 to 66°F (14 to 19°C). The fish broadcast spawn in these areas, with males releasing sperm as the outnumbered females release 100,000 to a million eggs. The fertilized eggs then sink and adhere to the gravel at the bottom. The eggs are brown in color and hatch in about a week, depending on water temperature. Female white sturgeon do not spawn every year.

Upon hatching, the larvae are around 0.5 in (1.3 cm) long, with a tadpole-like appearance. They drift downstream with the current until they reach a suitable habitat. When the rearing habitat is reached, the larvae typically take around 25 days for the yolk sac to be absorbed. About a month after hatching, the sturgeon have a full set of fins, rays, and scutes. As small juveniles, they feed on insects, small fish, and small crustaceans. Maturity is reached between 5 and 11 years, depending on the gender of the fish and the temperature of the water.

White sturgeon can live to be over 100 years old. The rate of growth is dependent on water temperature. Typically, they reach six feet long around 25 years of age, showing that these fish do not grow as quickly as many other fish. They are anadromous, meaning they spawn in fresh water and migrate to salt water to mature. Sturgeon may migrate in and out of salt water many times in their lives. However, since the building of many dams along the Columbia and Snake Rivers, the populations above the dams have become landlocked.

Unexpected social behavior has been observed in white sturgeon of the lower Columbia River. Up to 60,000 sturgeon massed in a dense "sturgeon ball" at the base of the Bonneville Dam in early 2008. Scientists do not know what the reason for the behavior was, but predator avoidance is one theory.', 'White sturgeon are well-adapted to finding food drifting by with their excellent sense of smell and taste. When the food supply is insufficient, sturgeon have been known to move into shallow water to eat freshwater clams.

A sturgeon''s taste buds are located on the outside of its mouth. This, along with the barbels, allows it to see if a possible food source is edible before sucking it up into its mouth. As adults, the white sturgeon''s diet somewhat varies. This is dependent upon the river systems in which it lives. 

In the Columbia River system, dead fish, crustaceans, and mollusks are all popular prey. Lampreys, primitive eel-like fish, come into rivers to spawn at the same time as the white sturgeon, and are a popular food source in the moment. 

Smelt are another abundant food around spawning time. Shad come into the Columbia River system in throngs of several million each spring. The extremely large shad runs are often cited as an example of why the lower Columbia River has such a large population of sturgeon. Like the smelt, these fish often die, and the remains are an easy meal for sturgeon.', 'Ocean', 'Stamina', '468 lb,
Joey Pallotta, III,
Benicia, California, USA,
7/9/1983');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, avg_adult_weight_lbs, avg_adult_length_inches, known_for, world_record, world_record_link)
VALUES ('Salt', 'Bonefish', 'Banana,Bananafish, Indo-Pacific Bonefish, Ladyfish, Round Jaw, Salmon Peel, Tarpon, Tenny, Tenpounder', 'One of the most distinctive characteristics of the bonefish is the inferior mouth and conical nose that protrudes a third of its length beyond the mandible. The body is slender, round, and compressed, more so in large specimens than in young adults. The dorsal profile is more convex than the ventral profile. The first few rays of the dorsal fin are higher than the following rays and this lends a somewhat triangular shape to the dorsal fin when erect. The caudal fin is deeply forked, with the upper lobe slightly larger than the lower. 

Bonefish appear blue-greenish above, with bright silver scales on the sides and below. Dark streaks run in between the rows of scales, predominantly on the dorsal side of the body. The dorsal and caudal fins have dusky margins. Bonefish have no spines. Juvenile bonefish exhibit a series of nine dark crossbands on their backs. These bands extend nearly to the lateral line, with the third band crossing at the origin of the dorsal fin. Bands four and five are found under the posterior base of the dorsal fin. As the juvenile bonefish age the bands begin to disappear with the posterior bands the first to fade. Beyond about 3 inches (7.5 cm) the dark longitudinal streaks characteristic of the adults begin to appear and the last of the crossbands become obscured. 

Granular teeth, forming specialized dental plates, cover the tongue and upper jaw of the bonefish. Similar grinders are also present in the throat. The bonefish uses these modified teeth to grind its mollusk and crustacean prey. 

The IGFA all-tackle record of 19 pounds has held since 1962, when it was caught from the surf off South Africa (though not A. vulpes — another species).', 'Albulidae', 'Albula vulpes', 'Near Threatened', 'Bonefish are predominately a coastal species, commonly found in intertidal flats, mangrove areas, river mouths, and deeper adjacent waters. The flats vary in composition from sand or grass to rocky substrates. 

Bonefish can tolerate the oxygen-poor water they sometimes encounter in coastal habitats by inhaling air into a lung-like air bladder. Bonefish typically school, sometimes in groups of up to 100 individuals. Studies in the Bahamas using ultrasonic telemetry demonstrated the daily patterns of bonefish consist of a movement to shallow water during the rising tide, and a retreat into deeper water during a falling tide. Bonefish are also known to move from particular sites (creek, channel, bay, etc.) after inhabiting the location for a maximum period of several days. Over the long-term movements between such "favorite" sites seem to occur without any discernable pattern. During summer months, larger individuals tend to remain in deep water, rarely moving onto the flats; they reappear in autumn, as water temperatures grow cooler.', 'Spinning tackle with a smooth drag is the most popular gear for bonefish though fly fishing ranks highly as well. Spinning tackle is used chiefly for casting leaded jigs or live bait such as shrimp or crabs.

As a rule of thumb, try to cash the lure about 3 ft from your target. If however a school is on the move or fidgeting in a steady, level swim, the lure must be presented well ahead of them (20-30 ft) and retrieved very slowly.

When casting spinning lures, the disparity between tone tide or school and the next is sometimes great. There are times when you can’t toss a small leaded jig within 10 ft of a bonefish without it busting for the deep so the 3 ft rule doesn’t always apply.

Stalking bonefish requires some pretty extensive experience. The beginner fishing without a guide will invariably mistake the tails of ground sharks or the wing tips of small rays for bonefish signs. The technique of poling a skiff is too much for the novice to master on a short vacation as well. As such, wading is often the most desirable method for both physical and cost reasons however beginners are well-advised to start with a guided craft. Many of the top guides are booked months if not a year in advance so plan your bonefish angling ahead of time!', 'Bonefish spawning occurs year round. Sexual maturity is reached at two years and near ripe females may be as small as 9 inches (25 cm). 

In the Florida Keys, bonefish spawn in deep water where currents can easily disperse the developing eggs and larvae to other locations. 

Bonefish are less reproductively active during the hotter summer months, while spawning peaks from November through June. 

Bonefish possess a leptocephalus larval stage, a reproductive strategy seen elsewhere only amongst the closely related tarpons and eels. 

The transformation from the transparent, ribbon-like leptocephalus to juvenile bonefish occurs in three distinct stages. Early stage 1 leptocephali lack dorsal, anal, and pectoral fins and are small, usually less than about 30mm. Late in stage 1 the nascent dorsal and anal fins appear and the larvae approaches its maximum size of approximately 63mm. At this length the larvae begins a rapid metamorphosis in which the entire body shrinks for 10-12 days until it reaches half its original length. During this transformation (stage II) the anal and dorsal fins move forward and the snout projects noticeably beyond the mandible. The subsequent appearance of scales, the lateral line, and the onset of an overall appearance of that of a miniature bonefish mark the transformation to a fry (stage III). 

Pigmentation and crossbands appear at about 4 cm in length, followed by the appearance of longitudinal stripes and the disappearance of the crossbands.', 'The bonefish uses modified granular teeth which form specialized dental plates that cover the tongue and jaw to grind its mollusk and crustacean prey. Similar grinders are also present in the throat. 

The bonefish uses its conical snout to dig through the benthos to root up its prey, which it crushes and grinds with its powerful pharyngeal teeth. Bonefish feed on benthic worms, fry, crustaceans, and mollusks, often in water less than 12 inches (30 cm) in depth.', 'Ocean', 15, 32, 'Sight Casting Target', '16 lb,
Jerry Lavenstein,
Bimini, Bahamas,
2/25/1971', 'Bonefish WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Shark, Thresher', 'Thrasher Shark, Common Thresher Shark, Fox Shark,
Grayfish, Sea Fox, Slasher, Swingletail, Swiveltail, Thintail Thresher,
Whip-Tailed Shark, Zorro Thresher Shark, Renard, Faux, Zorro', 'Thresher sharks are large lamniform sharks of the family Alopiidae found in all temperate and tropical oceans of the world; the family contains four species, all within the genus Alopias. 

Named for their exceptionally long, thresher-like heterocercal tail or caudal fins (which can be as long as the total body length), thresher sharks are fairly slender, with small dorsal fins and large, recurved pectoral fins. 

With the exception of the bigeye thresher, these sharks have relatively small eyes positioned to the forward of the head. Coloration ranges from brownish, bluish or purplish gray dorsally with lighter shades ventrally.

The three species can be roughly distinguished by the main color of the dorsal surface of the body. Common threshers are dark green, bigeye threshers are brown and pelagic threshers are generally blue. Lighting conditions and water clarity can affect how any one shark appears to an observer, but the color test is generally supported when other features are examined.', 'Alopiidae', 'Alopias vulpinus', 'Vulnerable', 'In the open ocean the Thresher Shark is commonly found from
the surface down to depths of at least 336m (1,100ft). Some sources claim maximum depths of 550m (1,800ft) but these reports are difficult to verify. 

The species is most abundant 40–75 miles from land in temperate regions as it gives birth inshore and the pups stay in shallow, coastal waters, only venturing further into the open ocean when closer to maturity. 

It has been noted that the Thresher
Shark segregates by size and sex. In the Gulf of Cadiz and waters
off northeast Morocco, near-term female dominated schools move
shoreward in spring, presumably to give birth. Towards the end of
spring neonates and gravid females dominate with no adult males found.

Like other Lamnid sharks, the Thresher Shark has a ‘rete mirable’
systems that allows it to maintain its body temperature above that
of the surrounding water. 

This is a rare trait among
fishes, only the mackerel sharks (Lamnidae), tunas (Thunnini) and
billfishes (Xiphiidae, Istiophoridae) having evolved this ability
(Weng and Block, 2004). This adaptation allows the shark to range much further into the temperate regions than similar cold-blooded species and explains its relative abundance along the temperate Atlantic coasts of Europe and the U.S.A. (Martin, 1992)', 'They’re stubborn fighters, capable of uncanny bursts of speed, and can make spectacular leaps into the air.', 'Reproduction appears to be annual, with mating in the northeast Atlantic taking place in midsummer.

The Thresher Sharks is ovoviviparous, meaning that the young develop within the mothers body in a primitive uterus. 

They are nourished by yolk-filled egg capsules that are
continually produced by the mother for the unborn young to consume. This is known as oophagy or oviphagy and is a form intrauterine (within-the-womb) cannibalism. The gestation period appears to be 9 months and it has been suggested that, as the rete mirable system warms the uteri, development is hastened in the Alopidae and Lamnidae sharks. 

The average litter size is between 2 and 4 pups although
the maximum recorded is 7. These pups are born already measuring
114-160cm (3.7-5.2ft).', 'The Thresher Shark has developed an unusual method of hunting. Working either alone or in small groups, it bunches up small to medium sized schooling fish then stuns and disorientates them using its tail. The shark then eats the dazed fish. 

Similar behavior has been recorded in whales, dolphins and some other fish, however none of these are so highly adapted to this method of
feeding. 

Apart from schooling fish such as mackerels, bluefishes and needlefishes, the Thresher Shark is known to feed on squid, octopi, crustaceans, and has been recorded using its tail to kill seabirds.', 'Ocean', 'Stamina', '767 lb 3 oz,
D.L. Hannah
Bay of Islands, New Zealand,
2/26/1983', 'Thresher Shark WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Kahawai', 'Giant Kahawai, Kermadec Kahawai, Northern Kahawai, Australian Salmon, Australian Herring', 'The kawawai is a streamlined, in-shore, pelagic species. It is a firm, silvery fish ranging from grey-blue to blue-green on top and silver below. They have rows of black spots along their flanks. While they can grow up to around 30in (75 cm) and 20lb (9kg), they average around 15-20in (40-50cm) and 2-3lb (1-2kg).

The kahawai (or Australian salmon) is unique to Australia and New Zealand. It resembles a trout or salmon in shape and appearance, but is of no relation. It and when properly bled can make for great eating. It is particularly good smoked.', 'Arripidae', 'Arripis trutta', 'Not Evaluated', 'Kahawai are found off the southern coast of Australia from western Victoria to New Zealand, including the islands of Tasmania, Lord Howe, and Norfolk.

Kahawai and other Australian salmon stay within the upper layers of relatively shallow (1–80 m), open and clear coastal waters (although the western Australian salmon may prefer deeper water). The turbulent surf zone of beaches, rocky reefs, bays, and brackish waters such as estuaries are also frequented, and some species may also enter rivers. Juveniles inhabit estuaries and mangroves, as well as sheltered bays with soft bottoms carpeted with seagrasses. Adults undertake seasonal migrations over vast distances, moving into deeper water during winter months. The evolutionary history of the species of Arripis has been shaped by changes to oceanographic conditions and land-bridges that occurred during glacial cycles.', 'Kahawai is the traditional maori name which when translated means "brave" or "strong" (kaha) water (wai). This in reference to the kahawi''s tendency to jump and fight when caught. In New Zealand it is often caught in abundance at river mouths and is a highly popular sports fish that is widely regarded to "punch above its weight" in terms of challenge to land.

It can often be caught on a spinning or surf casting reel, although it is not unheard of for fishermen to use lighter lines and fly fishing rods for a real challenge.

The kahawai is often associated with the white fronted tern, as the bird often congregates above the bait balls associated with a shoal of kahawai hunting. As such the tern is colloquially known as the "kahawai bird"', 'Although their reproduction is poorly studied, all Australian salmon including kahawai are known to be "pelagic spawners"; that is, they spawn in open water during the austral spring, releasing a large number of tiny (1 mm in diameter), smooth spherical eggs made buoyant by lipid droplets. The eggs (and later the larvae), which possess an unsegmented yolk, become part of the zooplankton, drifting at the mercy of the currents until the larvae develop and settle. The young Australian salmon then spend the first two to five years in sheltered coastal bays, inlets, and estuaries until they become sexually mature and begin to move into more open waters. Relatively long-lived fishes, Australian salmon may attain an age of 26 years for kahawai and 7–9 years in other species.

All species are oceanic spawners. Reports of A. trutta being anadromous and spawning in freshwater are not correct; this may be due to confusion with sea-run specimens of exotic brown trout, (Salmo trutta), or anadromous populations of native spotted galaxias, (Galaxias truttaceus).

A. georgianus is thought – due to females retaining both ripe and unripe eggs – to be "partial spawners"; that is, they may spawn over a long period with no real peaks. In contrast, A. trutta and A. truttaceus are thought to be "serial batch spawners", completing their spawning season after a series of small "burst" spawnings.', 'Kahawai form immense schools with hundreds to thousands of individuals, as both adults and juveniles. They are carnivorous and feed primarily on small fish, such as pilchard (Clupeidae); crustaceans such as krill (Euphausiacea), copepods, and other zooplankton (the latter comprising the bulk of the juvenile diets). The zoobenthos is also sampled to some extent, with primarily shellfish, crabs, and annelid worms eaten. The Australian salmon are very fast swimmers, and are sometimes seen mingling with ostensibly similar species of carangids, such as trevally; this is an example of mutualism.

Together with the carangids, Australian salmon feed en masse by co-operatively bullying baitfish up to the surface; this herding technique is exploited by seabirds which are quickly attracted to, and feed upon, the foaming mass of fish at the surface. This commensal relationship between the Australian salmon and the birds is noted to be especially strong in such species as the white-fronted tern, (Sterna striata), fluttering shearwater, (Puffinus gavia), and Buller''s shearwater, (Puffinus bulleri). The baitfish made available by the Australian salmon''s herding behaviour may also be important to the reproductive success of winter-nesting birds; the decline of the Australians salmon stocks has evoked concern for these bird species, some of which – such as the fairy tern, (Sterna nereis) – are endangered.', 'Ocean', 'Fight Dynamics', '19 lb 4 oz,
Stephen Muller,
Currarong, Australia,
4/9/1994', 'Kahawai WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, avg_adult_weight_lbs, avg_adult_length_inches, known_for, world_record, world_record_link)
VALUES ('Salt', 'Jack, Bluefin Trevally', 'Bluefin Jack, Bluefin Kingfish, Bluefinned Crevalle, Blue Ulua, Omilu, Spotted Trevally', 'The bluefin trevally is a species of large, widely distributed marine fish classified in the jack family, Carangidae. Bluefin trevally are easily recognized by their electric blue fins, tapered snout and numerous blue and black spots on their sides. Juveniles lack these obvious colors, and must be identified by more detailed anatomical features such as fin ray and scute counts. The species grows to a maximum known length of 46 inches and a weight of 95 pounds, however is rare above 32 inches.

It is similar in shape to a number of other large jacks and trevallies, having an oblong, compressed body with the dorsal profile slightly more convex than the ventral profile, particularly anteriorly. This slight convexity leads to the species having a much more pointed snout than most other members of Caranx. 

The dorsal fin is in two parts, the first consisting of 8 spines and the second of 1 spine followed by 21 to 24 soft rays. The anal fin consists of 2 anteriorly detached spines followed by 1 spine and 17 to 20 soft rays. The pelvic fins contain 1 spine and 20 soft rays. The caudal fin is strongly forked, and the pectoral fins are falcate, being longer than the length of the head. 

The lateral line has a pronounced and moderately long anterior arch, with the curved section intersecting the straight section below the lobe of the second dorsal fin. The curved section of the lateral line contains 55-70 scales while the straight section contains 0 to 10 scales followed by 27 to 42 strong scutes. The chest is completely covered in scales. 

The upper jaw contains a series of strong outer canines with an inner band of smaller teeth, while the lower jaw contains a single row of widely spaced conical teeth. The species has 25 to 29 gill rakers in total and there are 24 vertebrae present. The eye is covered by a moderately weakly developed adipose eyelid, and the posterior extremity of the jaw is vertically under or just past the anterior margin of the eye. Despite their wide range, the only geographical variation in the species is the depth of the body in smaller specimens.

The upper body of the bluefin trevally is a silver-brassy colour, fading to silvery white on the underside of the fish, often with blue hues. After they reach lengths greater than 16 cm, blue-black spots appear on the upper flanks of the fish, with these becoming more prolific with age. There is no dark spot on the operculum. The species takes its name from the colour of its dorsal, anal and caudal fins, which are a diagnostic electric blue. The pelvic and pectoral fins are white, with the pectoral fin having a yellow tinge. Juvenile fish do not have the bright blue fins, instead have dark fins with the exception of a yellow pectoral fin. Some juvenile fish have also been recorded as having up to five dark vertical bars on their sides.

The IGFA all-tackle world record is 29 pounds, 3 ounces from Clipperton Atoll (2012); however, Fishbase.org suggests they get larger — much larger, citing a maximum published weight of nearly 100 pounds.', 'Carangidae', 'Caranx melampygus', 'Not Evaluated', 'The bluefin trevally is distributed throughout the tropical waters of the Indian and Pacific Oceans, ranging from Eastern Africa in the west to Central America in the east, including Japan in the north and Australia in the south. 

This species inhabits both inshore environments such as bays, lagoons and shallow reefs, as well as deeper offshore reefs, atolls and bomboras. Juveniles prefer shallower, protected waters, even entering estuaries for short periods in some locations.', 'Bluefin inhabit nearshore reefs and enter harbors, reef channels and lagoons as well. 

Like other species in the jack family, they aggressively strike lures, jigs, flies and bait and offer one of the toughest pound for pound fights to the end.', 'The bluefin trevally reproduces at different periods throughout its range, and reaches sexual maturity at 30–40 cm in length and around 2 years of age. It is a multiple spawner, capable of reproducing up to 8 times per year, releasing up to 6 million eggs per year in captivity', 'The bluefin trevally is a strong predatory fish, with a diet dominated by fish and supplemented by cephalopods and crustaceans as an adult. Juveniles consume a higher amount of small crustaceans, but transfer to a more fish based diet as they grow. The species displays a wide array of hunting techniques ranging from aggressive midwater attacks, reef ambushes and foraging interactions with other larger species, snapping up any prey items missed by the larger animal.', 'Ocean', 95, 46, 'Stamina', '29 lb 3oz,
Kathleen J. Rounds,
Clipperton Atoll, Mexico,
4/13/2012', 'Bluefin Trevally WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Jack, California Yellowtail', 'Yellowtail Amberjack, Asian Yellowtail,
Southern Yellowtail, Kingy, Cape Yellowtail, Forktail, Mossback, White Salmon', 'The body of the California yellowtail is elongated, fusiform and compressed. The upper and lower body profiles are similar and the snout is long and pointed with the mouth ending under front edge of pupil 

The California yellowtail is most often blue on the upper back with sides and belly coloration ranging from silvery to white. The California yellowtail presents  a narrow yellow-bronze stripe along the middle of body running down the lateral line and arching over the pectoral region, becoming yellow posteriorly on most fins including the tail. Juvenile present with numerous narrow dark bars (a little wider than pale interspaces) that do not extend onto the dorsal and anal fins.', 'Carangidae', 'Seriola lalandi dorsalis', 'Not Evaluated', 'The yellowtail''s range is circumglobal, in subtropical waters. It can be found near Catalina Island, San Clemente Island, and Santa Monica Bay, as well as in Mexican waters such as Baja California Peninsula and Gulf of California, congregating at certain areas in mass numbers like Cedros Island and Benitos Island. 

During the summer months yellowtails can also be found in association with floating kelp paddies off the coast of southern California and Baja California. 

Yellowtail populations have also been found in waters off South Africa, the Walter Shoals, Amsterdam Island, Japan, Australia, New Zealand, New Caledonia, Hawaii, Rapa, Pitcairn Island, Jeju Island, and Easter Island. In the Eastern Pacific, they can be found in waters off British Columbia, as well as from Canada to Chile. They are usually found around offshore islands, rocky reefs, and kelp beds. They are also found in increasing numbers off the Islands of the Tristan Da Cunha archipelago in the South Atlantic.', 'Angling for yellowtail requires tackle heavy enough to insure a fair chance of landing the fish. Yellowtail like to head for rocks or kelp as soon as they''re hooked so line should test 20-30 pounds, hooks should be small (size 6 or 4) but strong, and the angler must make sure the fish is played out before it nears the pier and the pilings otherwise tangling is likely inevitably ending in a broken line. 

Although an assortment of lures work well when fishing for California Yellowtail on boats, almost all of the pier-caught yellowtail are taken on live bait. The most effective live and cut baits are small jack mackerel, Pacific mackerel or Pacific sardines.', 'California yellowtail spawn in warm waters 100–300 miles off the California coast and return in May or June until September or December. They spawn slowly, but may live in excess of 30 years. 

Spawning usually begins at three years of age. One major spawning ground is at Cedros Island, where large numbers of 15- to 20-pound yellowtail can be caught. Yellowtail are aggressive towards other fish. 

They will often feed more frequently during spawning, which makes them an easy target for commercial fishing boats. They are currently not on the endangered list.', 'The California Yellowtail is carnivorous and feeds on a variety of fish. Mackerel, sardines, anchovies, squid, and crab are common in the yellowtail''s diet. Often, the California Yellowtail are found in schools feeding at the surface of the water, but also feed deeper down in the water column.', 'Ocean', 'Stamina', '109 lb 2 oz,
Masakazu Taniwaki,
Ohara, Chiba, Japan,
10/24/2009', 'Yellowtail WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Jack, Crevalle', 'Trevallies, Jackfish, Crevally Jack, Common Jack, Black-tailed Trevally, Couvalli, Jack, Black Cavalli, Yellow Cavalli', 'The crevalle jack''s color ranges from brassy green to blue or bluish-black dorsally, becoming silvery white or golden ventrally. A dark spot is often present on the pectoral fin, with a similar dark to dusky spot present on the upper margin of the operculum. Juveniles have around five dark vertical bands on their sides, with these fading at adulthood. The first dorsal fin, pectoral and pelvic fins range from white to dusky, occasionally with golden tinges throughout. The anal fin lobe is bright yellow, with the remainder of the fin ranging from golden to dusky, while the underside of the caudal peduncle often being yellow in adults. The caudal fin itself is also golden to dusky, with the lower lobe often brighter yellow than the upper, with both the lobes often having a black trailing edge.

The crevalle jack is one of the largest members of Caranx, growing to a known maximum length of  50 in (125 cm) and a weight of 70 lb (32 kg), although it is generally uncommon at lengths greater than 65 cm. Unverified reports of fish over 60 in (150 cm) may also be attributable to this species. The crevalle jack is morphologically similar to a number of other deep-bodied carangids, having an elongate, moderately compressed body with the dorsal profile more convex than the ventral profile, particularly anteriorly. The eye is covered by a well-developed adipose eyelid, and the posterior extremity of the jaw is vertically under or past the posterior margin of the eye.The dorsal fin is in two parts, the first consisting of eight spines and the second of one spine followed by 19 to 21 soft rays. The anal fin consists of two anteriorly detached spines followed by one spine and 16 or 17 soft rays. The pelvic fins contain one spine and five soft rays, while the pectoral fins contain 20 or 21 soft rays. The caudal fin is strongly forked, and the pectoral fins are falcate, being longer than the length of the head. The lateral line has a pronounced and moderately long anterior arch, with the curved section intersecting the straight section midway below the second dorsal fin. The straight section contains 23 to 35 very strong scutes, with bilateral keels present on the caudal peduncle. The chest is devoid of scales with the exception of a small patch of scales in front of the pelvic fins. The upper jaw contains a series of strong outer canines with an inner band of smaller teeth, while the lower jaw contains a single row of teeth. The species has 35 to 42 gill rakers in total and 25 vertebrae are present.', 'Carangidae', 'Caranx hippos', 'Least Concern', 'The Crevalle Jack lives in both inshore and offshore habitats, with larger adults preferring deeper waters than juveniles. In the inshore environment, crevalle jack inhabit shallow flats, sandy bays, beaches, seagrass beds, shallow reef complexes and lagoons, which may be open or landocked, and may be composites of the aforementioned environments. The species is also known to enter brackish waters, with some individuals known to penetrate far upstream; however, like most euryhaline species, they generally do not penetrate very far upriver.

The water salinities where the species has been reported from range from 0% to 49%, indicating the species can adapt to a wide range of waters. Studies in West Africa found marked differences in the sex ratios of populations in brackish waters, with females very rarely seen in such environments once they are mature.Research in the coastal waters of Ghana suggests the availability of food is the primary control on the species distribution in inshore waters.

Adults that move offshore generally do not leave continental shelf waters, however still penetrate to depths of 350 m, and possibly deeper. These individuals live on the outer shelf edges, sill reefs and upper slopes of the deep reef, and tend to be more solitary than juveniles.`20] Adults have also been sighted around the large oil rig platforms throughout the Gulf of Mexico, where they use the man-made structure like a reef to hunt prey. The larvae and young juveniles of the species live pelagically offshore along the continental shelf and slope, and are also known to congregate around oil platforms, as well as natural floating debris such as sargassum mats.', 'The crevalle jack is a fierce, stubborn, and dynamic gamefish for trolling, casting, or still-fishing with live or cut bait.

One of several things in the crevalle’s favor is the fact that it’s a first-class light-tackle fish which can be caught on fly, plug, or spinning gear.', 'The crevalle jack reaches sexual maturity at different lengths in males and females, with estimates suggesting males reach maturity at 21 in (55 cm) and four to five years of age, and females at 26 in (66 cm) and five to six years of age.

Reproduction is thought to occur year round in most areas, although there are peaks in activity. South of Florida, this period is between March and September, in Cuba it is April and May, while in Jamaica no definitive peak has yet been identified. The species also has a protracted spawning in Ghana, although a peak in activity occurs between October and January. Juveniles are also present in lagoons year round in this location, indicating year round spawning and recruitment. 

The place of spawning also appears to be variable, with the act occurring offshore south of Florida, while in Colombia and Belize, they have been observed spawning over inshore reefs and bays. 

Large aggregations of crevalle jack form prior to spawning, with these schools containing upward of 1000 individuals. Pairs break off from the school to spawn, with one individual turning a much darker color during this exchange. Once spawning has occurred, the pair rejoins the main school.

Fecundity in the species has been estimated as up to one million eggs, with these being pelagic, and spherical in shape. They have a diameter of 0.7 to 0.9 mm, and contain a pigmented yolk and one yellow oil globule with dark pigments. The larvae have been extensively described in the scientific literature, although the sequence of fin formation is still not well known. Defining features of the larval crevalle jack include a relatively deep body, heavily pigmented head and body, and more detailed meristic characteristics, with flexion occurring at 4 to 5 mm in length.', 'The crevalle jack is a powerful predatory fish which predominantly takes other small fishes as prey at all stages of its life, with various invertebrates generally being of secondary importance to its diet.

Several studies conducted on the species'' diet over its range have found other aspects of its diet vary widely, including the specific types of prey the species takes and the change in diet with age. The most detailed of these studies was conducted in the Southern USA, which showed the species diet comprised between 74% and 94% fish. The remainder of the diet was various prawns, shrimps, crabs, molluscs and stomatopods. The types of fish taken varied throughout the range, with members of Clupeidae, Sparidae, Carangidae and Trichiuridae all taken in variable amounts, usually with members of one family dominating the local diet. 

The percentage of various invertebrates also was highly variable, with penaeid shrimps, portunid crabs, stomatopods and squid being of importance to different populations. The study also indicated young crevalle jack predominantly take clupeids, adding sparids and later carangids to their diets as they grow larger.The larger individuals also took much higher amounts of invertebrates, and also small quantities of seagrass, indicating larger fish are more opportunistic.This general change in diet with age also seems spatially variable, with young crevalle jack in both Maryland and Puerto Rica consuming almost exclusively crustaceans, including shrimps, crabs (and juvenile tarpon) in Maryland and harpacticoid copepods in Puerto Rico before moving to fish-dominated diets later in life. Research in Ghana shows a pattern somewhat intermediate to the previous two locations; adults take larger fish, predominantly Engraulis guineensis and Sardinella eba, while juvenile fish take smaller fishes such as Epiplatys sexfasciatus or juvenile caridian and penaeid shrimps.

The widely variable diet of the species throughout its life stages led authors in the 1950s and 1960s to conclude the species was indiscriminate in its feeding habits, eating whatever was locally available. The diets of the populations in both the southern USA and Ghana also varied quite markedly by season and year, which led the authors of both these studies to agree with these earlier conclusions. Recent laboratory studies, however, have shown the species may have preferences for certain sizes of prey. In these experiments, the fish were presented with a range of size classes of the same prey species, Menidia beryllina, with the results showing they prefer to take the smallest size class possible, which contrasts with more aggressive predators, such as bluefish. Both adults and juveniles feed throughout the day, generally becoming inactive at night. During some feeding periods recorded in Ghana, digestion in the species was so rapid that food becomes unidentifiable within four to five hours of consumption. The crevalle jack is also an important prey species itself, taken by larger fish, such as billfish and sharks, as well as seabirds. As well as being preyed on during its adult stage, the spawn of the crevalle jack is known to be eaten by planktivorous organisms, including whale sharks in the Caribbean.', 'Ocean', 'Stamina', '66 lb 2 oz,
Carlos Alberto Leal Simoes,
Barra Do Dande, Angola,
6/1/2010', 'Crevalle Jack WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Jack, Giant Trevally', 'Barrier Trivially, Giant Kingfish, GT, Lowly Trivially, Ulua,', 'The giant trevally is distinguished by its steep head profile, strong tail scutes, and a variety of other more detailed anatomical features. It is normally a silvery color with occasional dark spots, but males may be black once they mature. It is the largest fish in the genus Caranx with the IGFA world record weighing in at an amazing 160 pounds, 7 ounces caught in Japanese waters in 2006.', 'Carangidae', 'Caranx ignobilis', 'Not Evaluated', 'The giant trevally is distributed throughout the tropical waters of the Indo-Pacific region, with a range stretching from South Africa in the west to Hawaii in the east, including Japan in the north and Australia in the south.', 'One of the largest members of the jack (Carangidae) family, giant trevally (widely known as GT) are quite simply one of toughest fish on rod and reel in the world.', 'The species reproduces in the warmer months, with peaks differing by region. Spawning occurs at specific stages of the lunar cycle, when large schools congregate to spawn over reefs and bays, with reproductive behavior observed in the wild. The fish grows relatively fast, reaching sexual maturity at a length of around 23 in (60 cm) and around three years of age.', 'The giant trevally is a powerful apex predator in most of its habitats, and is known to hunt individually and in schools. The species predominantly takes various fish as prey, although crustaceans, cephalopods and mollusks make up a considerable part of their diets in some regions. The species has some quite novel hunting strategies, including shadowing monk seals to pick off escaping prey, as well as using sharks to ambush prey.', 'Ocean', 'Stamina', '160 lb 7 oz,
Keiki Hamasaki,
Tokara, Kagoshima, Japan
5/22/2006', 'Giant Trevally WR');
