-- Import batch from saltwater_batch_09.json
-- Total records: 7

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Shark, Great Hammerhead', 'Great Hhammerhead Shark, Squat-headed Hammerhead Shark', 'The hammerhead shark ranges from 3.0 to 19.7 ft (0.9 to 6 m) in length and weigh from 6.6 to 1,278.7 lb (3 to 580 kg). They are usually light gray and have a greenish tint. Their bellies are white which allows them to blend into the ocean when viewed from the bottom and sneak up on their prey. Their heads have lateral projections which give them a hammer-like shape.

Hammerheads have disproportionately small mouths and seem to do a lot of bottom-hunting. They are also known to form schools during the day, sometimes in groups of over 100. In the evening, like other sharks, they become solitary hunters.', 'Sphyrnidae', 'Sphyrna mokarran', 'Endangered', 'Circumtropical in distribution, the great hammerhead is found in coastal warm temperate and tropical waters within 40°N - 37°S latitude. In the western Atlantic Ocean, it ranges from North Carolina (US) south to Uruguay, including the Gulf of Mexico and Caribbean regions, while in the eastern Atlantic Ocean, this species ranges from Morocco to Senegal, including the Mediterranean Sea.

Distribution of the great hammerhead includes the Indian Ocean and the Indo-Pacific region from Ryukyu Island to New Caledonia and French Polynesia. The eastern Pacific range is from southern Baja, California (US) through Mexico, south to Peru. The great hammerhead is considered a highly migratory species.

This large coastal/semi-oceanic shark is found far offshore to depths of around 100 ft (300 m) as well as in shallow coastal areas such as over continental shelves and lagoons. The great hammerhead migrates seasonally, moving poleward to cooler waters during the summer months.', 'Only the heaviest of sporting gear will stand a chance against these bad boys. 80 lb test will be your minimum with weights of 130 lb test being recommended. 

Great hammerhead sharks will take large fresh dead baitfish and cutbait, but it is more easily hooked on oversized live baits.', 'Reproduction occurs only once a year for hammerhead sharks, and usually occurs with the male shark biting the female shark violently until she agrees to mate with him.

The hammerhead sharks exhibit a viviparous mode of reproduction with females giving birth to live young. Like other sharks, fertilization is internal with the male transferring sperm to the female through one of two intromittent organs called claspers. 

The developing embryos are first sustained by a yolk sac. When the supply of yolk is exhausted, the depleted yolk sac transforms into a structure analogous to a mammalian placenta (called a "yolk sac placenta" or "pseudoplacenta"), through which the mother delivers sustenance until birth. Once the baby sharks are born, they are not taken care of by the parents in any way. There is usually a litter of 12 to 15 pups; except for the Great Hammerhead which births litters of 20 to 40 pups. These baby sharks huddle together and swim toward warmer water until they are old enough and large enough to survive on their own.

In 2007, the bonnethead shark was found to be capable of asexual reproduction via automictic parthenogenesis, in which a female''s ovum fuses with a polar body to form a zygote without the need for a male. This was the first shark known to do this.', 'Hammerhead sharks are known to eat a large range of prey including fish, squid, octopus, crustaceans, and other sharks. Stingrays are a particular favorite. These sharks are often found swimming along the bottom of the ocean, stalking their prey. Their unique head is used as a weapon when hunting down prey. The hammerhead shark uses its head to pin down stingrays and eats the ray when the ray is weak and in shock.

The Great Hammerhead, tending to be larger and more aggressive than most hammerheads, occasionally engage in cannibalism, as they are known to eat other hammerhead sharks, including their own young.', 'Ocean', 'Stamina', '1280 lb,
Bucky Dennis,
Boca Grande, Florida, USA,
5/23/2006', 'Great Hammerhead Shark WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Shark, Scalloped Hammerhead', 'Bronze Hammerhead, KidneyHeaded
Shark, Southern Hammerhead, Requin-Marteau Halicorne', 'The most distinctive feature of the Scalloped Hammerhead Shark is the prominent median indentation on the leading edge of the
cephalophoil. It is distinguished from the Great Hammerhead Shark, Sphyrna mokarran, by the shallower indentations halfway between the median indentation and the edge of the head and also by the smaller first dorsal fin. This first dorsal fin is moderately falcate and originates over or slightly behind the pectoral fin bases. The pelvic fins are non-falcate. The second dorsal and anal fins have long free rear tips, on the second dorsal fin this nearly reaches the upper caudal origin. The posterior anal margin is deeply notched.

Dorsolaterally it is brownish grey to bronze or olive, ventrally it is pale yellow to white. Juveniles have dark tips to the pectoral, lower caudal and second dorsal fin tips. Adults may have dusky tips to the pectoral fins (Bester, Unknown).', 'Sphyrnidae', 'Sphyrna lewini', 'Endangered', 'The Scalloped Hammerhead Shark is a virtually circumglobal species in tropical and warm temperate coastal waters. In the east Atlantic it is known from the Mediterranean to Senegal and Zaire.

The Scalloped Hammerhead Shark occurs over continental and
insular shelves from the surface to at least 275m. It has been
observed close inshore and is known to enter estuarine habitats.
Adults can occur singly, in pairs or in small groups while young
sharks are known live in large schools. Schools of small Scalloped
Hammerhead Sharks have been observed migrating towards the
poles during the warmer months and returning when the water
cools. In other areas such as the East China Sea, resident populations exist. It is thought that these schools segregate by sex, during certain times and certain places at least', 'Being a middleweight of the shark family, it makes a good candidate for medium tackle. Like most sharks, chunks of dead fish or cutbait are one of the top choices for bait.', 'Female Scalloped Hammerhead Sharks mature at a total length of around 250cm, males smaller at around 180cm. During the 9–10 month gestation period the embryos are nourished through a yolk-sac placenta. Parturition occurs during the summer months with litters of 12–38 pups produced, each measuring 38–45cm total length. These pups initially tend to stay in inshore nursery grounds, the best studied being Kaneohe Bay, Oahu, Hawaii.', 'Primarily a piscivore, the Scalloped Hammerhead Shark also takes a wide variety of invertebrates. Known food items include sardines and herring, anchovies, ten-pounders, conger eels, milkfish, sea
catfish, silversides, halfbeaks, mullet, lizardfish, barracuda, bluefish, mackerel, jacks, porgies, mojarras, cardinal fishes, goatfish, grunts, damselfishes, parrotfishes, wrasses, butterfly fishes, surgeonfish, gobies, flatfish, sharpnose sharks (Rhizoprionodon spp.), the Blacktip Reef Shark (Carcharhinus melanopterus), angelsharks (Squatina spp.), stingrays, squid, octopi, cuttlefishes, sea snails, shrimp, mantis shrimp, crabs, lobsters and isopods.', 'Ocean', 'Speed', '353 lb,
Rick Gunion,
Key West, Florida, USA,
4/19/2004', 'Scalloped Hammerhead WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Shark, Spiny Dogfish', 'Dogfish Shark, Cape Dogfish, Cape Shark, Spring Dogfish, Spiked Dogfish, Grayfish, Spur Dog, Piked Dogfish', 'Spiny dogfish are slim, with a narrow, pointed snout and characteristic white spots. They are gray above and white below. They have two dorsal fins with ungrooved large spines. Males grow up to 3.3 feet, and females grow up to 4 feet.', 'Squalidae', 'Squalus acanthias', 'Vulnerable', 'Spiny dogfish are found in the North Atlantic and North Pacific Oceans, mostly in the temperate and subarctic areas. In the Northwest Atlantic, they are found from Labrador to Florida and are most abundant between Nova Scotia and Cape Hatteras. 

Spiny dogfish live inshore and offshore, usually near the bottom but also in mid-water and at the surface. They swim in large schools and migrate seasonally with changes in water temperature. Much of the population travels north in the spring and summer and south in the fall and winter. Some spiny dogfish remain in northern waters throughout the year and move offshore during the winter.', 'Dogfish will take many different kinds of bait. Clam is one of the most popular natural baits but cut mackerel and herring are just as productive. A simple basic bottom rig with a 3-8 ounce sinker is sufficient for bottom fishing with bait. 

Spiny dogfish can also be caught by jigging, just ask any codfisherman. Using artificial jigs is more effective if there are schools of baitfish in the area such as herring or mackerel. 

Unfortunately, dogfish don''t put up much of a fight on rod & reel, unless your lucky enough to foul hook one in tail.', 'Like all sharks, dogfish grow slowly, mature late in life, and live a long time (35 to 40 years).

Females grow larger and mature later than males—they’re first able to reproduce at age 12 compared to males at age 6. They spawn in winter in offshore waters.

Females have between two and 12 eggs per spawning season. The eggs are fertilized internally and, after a gestation period of 18 to 24 months, female dogfish bear live young (an average of six pups).', 'Spiny dogfish are opportunistic feeders, preying on whatever is most available.

Smaller spiny dogfish tend to feed primarily on crustaceans, while larger dogfish like to eat jellyfish, squid, and schooling fish.

Dogfish are preyed upon by cod, red hake, goosefish, other spiny dogfish, larger sharks, seals, and orcas.', 'Ocean', 'Subpar Game Qualities', '15 lb 12 oz,
Horst Muller,
Kenmare Bay, Co. Kerry, Ireland,
5/26/1989', 'Spiny Dogfish Shark WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Shark, Zebra', 'Leopard Shark, Variegated Shark', 'The zebra shark (Stegostoma fasciatum) is a species of carpet shark and the sole member of the family Stegostomatidae. The zebra shark has a cylindrical body with a large, slightly flattened head and a short, blunt snout. The eyes are small and placed on the sides of the head; the spiracles are located behind them and are as large or larger. The last 3 of the 5 short gill slits are situated over the pectoral fin bases, and the fourth and fifth slits are much closer together than the others. Each nostril has a short barbel and a groove running from it to the mouth. The mouth is nearly straight, with three lobes on the lower lip and furrows at the corners. There are 28–33 tooth rows in the upper jaw and 22–32 tooth rows in the lower jaw; each tooth has a large central cusp flanked by two smaller ones.

There are five distinctive ridges running along the body in adults, one along the dorsal midline and two on the sides. The dorsal midline ridge merges into the first dorsal fin, placed about halfway along the body and twice the size of the second dorsal fin. The pectoral fins are large and broad; the pelvic and anal fins are much smaller but larger than the second dorsal fin. The caudal fin is almost as long as the rest of the body, with a barely developed lower lobe and a strong ventral notch near the tip of the upper lobe. The zebra shark attains a length of 8.2 ft (2.5 m), with an unsubstantiated record of 11 ft (3.5 m). Males and females are not dimorphic in size.

The color pattern in young sharks is dark brown above and light yellow below, with vertical yellow stripes and spots. As the shark grows to 20–35 in (50–90 cm) long, the dark areas begin to break up, changing the general pattern from light-on-dark stripes to dark-on-light spots. There is substantial variation in pattern amongst adults, which can be used to identify particular individuals. In 1964, a partially albino zebra shark completely lacking spots was discovered in the Indian Ocean. The shark, a 6.2 ft (1.9 m) long mature female, was unusual in that albino animals rarely survive long in the wild due to their lack of crypsis.', 'Stegostomatidae', 'Stegostoma fasciatum', 'Vulnerable', 'The zebra shark occurs in the tropical waters of the Indo-Pacific region, from South Africa to the Red Sea and the Persian Gulf (including Madagascar and the Maldives), to India and Southeast Asia (including Indonesia, the Philippines, and Palau), northward to Taiwan and Japan, eastward to New Caledonia and Tonga, and southward to northern Australia.

Bottom-dwelling in nature, the zebra shark is found from the intertidal zone to a depth of 203 ft (62 m) over the continental and insular shelves. Adults and large juveniles frequent coral reefs, rubble, and sandy areas. 

Zebra sharks sometimes cross oceanic waters to reach isolated seamounts. Movements of up to 87 mi (140 km) have been recorded for individual sharks. However, genetic data indicates that there is little exchange between populations of zebra sharks, even if their ranges are contiguous.

During the day, zebra sharks are sluggish and usually found resting on the sea bottom, sometimes using their pectoral fins to prop up the front part of their bodies and facing into the current with their mouths open to facilitate respiration. Reef channels are favored resting spots, since the tightened space yields faster, more oxygenated water.

Zebra sharks become more active at night or when food becomes available. They are strong and agile swimmers, propelling themselves with pronounced anguilliform (eel-like) undulations of the body and tail. In a steady current, they have been seen hovering in place with sinuous waves of their tails.', 'Zebra sharks are not typically targeted by anglers and are typically caught by accident when fishing on the bottom in the evening hours using live or cut bait of either fish or crabs.', 'The courtship behavior of the zebra shark consists of the male following the female and biting vigorously at her pectoral fins and tail, with periods in which he holds onto her pectoral fin and both sharks lie still on the bottom. On occasion this leads to mating, in which the male curls his body around the female and inserts one of his claspers into her cloaca. Copulation lasts for two to five minutes. 

The zebra shark is oviparous, with females laying large egg capsules measuring 17 cm (6.7 in) long, 8 cm (3.1 in) wide, and 5 cm (2.0 in) thick. The egg case is dark brown to purple in color, and has hair-like fibers along the sides that secure it to the substrate. The adhesive fibers emerge first from the female''s vent; the female circles vertical structures such as reef outcroppings to entangle the fibers, so as to anchor the eggs. Females have been documented laying up to 46 eggs over a 112-day period. Eggs are deposited in batches of around four. Reproductive seasonality in the wild is unknown.', 'The zebra shark feeds primarily on shelled mollusks, though it also takes crustaceans, small bony fishes, and possibly sea snakes. The slender, flexible body of this shark allows it to wriggle into narrow holes and crevices in search of food, while its small mouth and thickly muscled buccal cavity allow it to create a powerful suction force with which to extract prey. 

The zebra shark may be preyed upon by larger fishes and marine mammals. Known parasites of the zebra shark include four species of tapeworms in the genus Pedibothrium.', 'Ocean', 'Subpar Game Qualities', '44 lb 7 oz,
Maria de la Luz Johnson,
San Diego Bay, California, USA,
12/31/2011', 'Zebra Shark WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Shark, Leopard', 'Cat Shark', 'The leopard shark has a moderately stout body, with a short, rounded snout. There are well-developed, triangular flaps of skin in front of the nares. The eyes are large and oval, with a nictitating membrane (a protective third eyelid). The line of the mouth is strongly curved. There are furrows at the corners of the mouth extending onto both jaws, with those on the lower jaw almost long enough to meet at the midline. The tooth rows number 41–55 in the upper jaw and 34–45 in the lower jaw; each tooth has a slightly oblique, smooth-edged cusp in the center and 1–2 small cusplets on either side. These teeth are arranged into a flat, "pavement"-like surface with overlapping ridges.', 'Triakidae', 'Triakis semifasciata', 'Least Concern', 'The leopard shark occurs in the cool to warm-temperate continental waters of the northeastern Pacific Ocean, from Coos Bay, Oregon to Mazatlán, Mexico, including the Gulf of California. It favors muddy or sandy flats within enclosed bays and estuaries, and may also be encountered near kelp beds and rocky reefs, or along the open coast. Numbers have been known to gather near discharges of warm effluent from power plants. Leopard sharks generally swim close to the bottom and are most abundant from the intertidal zone to a depth of 4 m (13 ft), though they may be found as deep as 91 m (299 ft). Many leopard sharks, particularly in the north, leave their coastal habitats in winter and return in early spring. A study in Tomales Bay in northern California determined that they depart when the water temperature drops below 10–12°C (50–54°F); one tagged shark was found to have swum some 140 km (87 mi) south.

While a few leopard sharks have been documented traveling hundreds of kilometers, most individuals tend to remain in a localized area for much of their lives. This low level of dispersal has led to genetic divergence across its range. Seven discrete gene pools have been identified along the Californian coast between Humboldt Bay and San Diego. Of these, the Humboldt Bay subpopulation is perhaps the most isolated, with the sharks there maturing at a larger size and producing fewer offspring than those from other areas. By contrast, the area around Los Angeles represents a genetic transitional zone between subpopulations whose boundaries are more diffuse. Off Baja California, the leopard sharks on the Pacific side are probably distinct from those in the northern Gulf of California.', 'Leopard sharks are not sought after by most anglers and are typically a byproduct of fishing for other fish on or near the bottom.', 'Leopard sharks are ovoviviparous, without a yolk-sac placenta and typically birth 4 to 29 pups per litter.', 'The leopard shark is primarily an opportunistic feeder on bottom-dwelling animals with some littoral prey taken also; invertebrates are somewhat more important in its diet than fish prey. Crabs, shrimps, bony fish, fish eggs, clam necks and innkeeper worms are the most important prey items of leopard sharks.', 'Ocean', 'Subpar Game Qualities', '44 lb 7 oz,
Maria de la Luz Johnson,
San Diego Bay, California, USA,
12/31/2011', 'Leopard Shark WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, fishing_techniques, spawning_habits_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Swordfish', 'A`u, Broadbill, Broadbill Swordfish, Espada, Emperado, Mekajiki, Shutome, Sword Fish', 'The swordfish is an offshore species with a variable black to grayish blue to brown to metallic purple, or bronze back.
Its sides are dusky with an underbelly of off/dirty white. The swordfish has large eyes and a long flat, sword-like upper jaw. It lacks scales, teeth, and pelvic fins and has a single keel on each side of its body in front of the tail. The first dorsal fin is high, rigid sloping quickly to short.

Swordfish are one of the fastest and largest predators in the ocean. Their streamlined body allows them to swim at high speeds, up to 50 mph. They grow rapidly, reaching a maximum length of 14 feet and almost 1,200 pounds (although the average size caught in the fishery is 50–200 pounds).', 'Xiphiidae', 'Xiphias gladius', 'Least Concern', 'The swordfish is a worldwide offshore species found in temperate and tropic waters and is known to frequent depths of 400 to 500 fathoms, but has also has been observed basking at the surface.', 'The top swordfish bait has been said to be large, rigged natural squid, but rigged baitfish will work too. Many swordfish as large as 400 lb or more have been caught by anglers driving deep baits at neight in recent years.

Classic techniques stemming from the mid-Atlantic to New England include pulling rigged baits in front of sighted fish as they “tailed” at the surface.', 'Swordfish spawn numerous times throughout the year near the surface of warm tropical and sub-tropical waters. In cooler waters, they spawn several times during the spring and summer.

Swordfish are productive, and their eggs are fertilized externally and float at the sea surface where they incubate for about 2 1/2 days. Swordfish live for about 9 years.', 'Swordfish feed on a variety of fish and invertebrates such as squid. They capture their prey by slashing their bills back and forth, stunning or injuring the prey in the process.

They have developed unique characteristics, such as special eye muscles and a heat exchange system that allow them to swim in deep cold water in search of prey.

Swordfish feed at the top of the food chain and are rarely preyed upon by other animals, but juvenile swordfish are sometimes eaten by sharks and larger predatory fish.', 'Ocean', 'Stamina', '1182 lb,
Louis Marron,
Iquique, Chile,
5/7/1953', 'Swordfish WR');

INSERT INTO fish_species (class, common_name, environmental_status, known_for)
VALUES ('Salt', 'Bass, Barred Sand', 'Not Evaluated', '00 Choose');
