-- Saltwater Fish Import Batch 4 of 9
-- Contains 10 records

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, baits_and_techniques, spawning_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Sailfish, Pacific ', 'Bayonet Fish, Billfish, Boohoo, Indian Sail Fish, Indian Sailfish, Indo-pacific Sailfish, Japanese Sailfish, Peacock Fish, Sail Fish, Sailfin, Spike Fish', 'The Indo-Pacific sailfish is dark blue on top, brown-blue laterally and silvery white underbelly. The upper jaw is elongated in the form of a spear. The first dorsal fin is greatly enlarged in the form of a sail, with many black cones. Its front is squared off and highest at its midpoint. The pelvic fins are very narrow, reaching almost to the anus. The body is covered with embedded scales that are blunt at end and the lateral line is curved above pectoral fin, then straight to base of tail. They have a large and sharp bill, which they use for hunting.', 'Istiophoridae', 'Istiophorus platypterus', 'Least Concern', 'Sailfish range throughout warm waters of the Pacific and Indian oceans. I. platypterus tends to run considerably larger in size than does its Atlantic counterpart, with 100-plus-pound fish being run of the mill. The fishery off Guatemala is known to be a leading sailfishery in the world, with some charter boats enjoying dozens of shots in a day. Malaysia’s burgeoning sailfishing in the Sea of China off Kuala Lumpur is another fishery with often-astonishing numbers. The world record has held since 1947: a 221-pounder taken off Ecuador.', 'Sailfish like all bill fish are a fantastic game/sport fish and deserve the respect of all anglers!

Light to medium lever drag trolling outfits or spinning combos are best suited for targeting sail fish in most situations. Rods and reels capable of holding large capacities of  6 – 10kg line are most commonly used and are attached to wind on leaders of around 80 – 120lb in breaking strain.

Live and fresh dead baits such as gar fish, small mullet, queen fish and mackerel are all ideal baits for targeting sails with small to medium soft headed, skirted lures also proving to be quite effective on the species. Popular hook styles include the Gamakatsu salt water fly hook in a 10/0 for dead baits and skirted lures with small, thin gauge circle hooks also growing in popularity for both live and dead bait presentations.

Try to ensure all baits, lures and tackle used are of premium quality, there are no second chances when it comes to billfish!

Most pelagic game fish species prefer low or high tide changes and new moon phases.', 'The Indo-Pacific sailfish seems to spawn throughout the year in tropical and subtropical waters of the Pacific with peak spawning occurring in the respective local summer seasons. Spawning occurs with males and females swimming in pairs or with two or three males chasing a single female (probably a mating behavior). The ripe ovarian eggs are about 0.85 mm in diameter and have a single oil globule;

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, baits_and_techniques, spawning_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Spearfish, Mediterranean', 'Longbill Spearfish, Spearfish, Roundscale Spearfish', 'The Mediterranean spearfish (Tetrapturus belone) body moderately slender, bill fairly short and round in crosssection, nape almost straight and only gently sloping up to dorsal fin origin. Pectoral fins very short, about equal to post-orbital part of head;

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, baits_and_techniques, spawning_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Spearfish, Shortbill ', 'Shortbill, Hebi', 'The Shortbill Spearfish has a narrow, very elongated very compressed body. It is dark blue dorsally and silver ventrally with touches of brown on their sides. The first dorsal fin is dark blue, while their other fins are brown or dark brown. The anal fin base has tinges of silvery white. They have a very short spear extending from their upper jaw, which is less than 15% of their total length. 

Shortfall Spearfish have small eyes and a mid-sized mouth equipped with small teeth. They have two anal fins, the first with 12 to 15 rays and the second with 6 to 8 rays. They have two dorsal fins, the first with 45 to 50 rays and forming a triangular peak at the front with the rest of the fin being relatively high and greater than the body depth;

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, baits_and_techniques, spawning_lifecycle, diet_feeding_habits, water_body_type, avg_adult_weight, avg_adult_length, known_for, world_record, world_record_link)
VALUES ('Salt', 'Shark, Great White', 'Great White, White Pointer, White Shark, White Death', 'The great white shark is a species of large lamniform shark which can be found in the coastal surface waters of all the major oceans. The great white shark is mainly known for its size, with mature individuals growing up to 21 ft (6.4 m) in length although reports have been published of great white sharks measuring over 26 ft (8 m ), and 7,328 lb (3,324 kg) in weight. This shark reaches its maturity around 15 years of age and was previously believed to have a life span of over 30 years. The true lifespan of great white sharks is far longer;

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, baits_and_techniques, spawning_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Shark, Shortfin Mako', 'Mako, Short-finned Mako, Blue Pointer,
Mackerel Shark, Blue Dynamite, Bonito Shark, Taupe Bleu', 'The shortfin mako shark is a fairly large species of shark. An average adult specimen measures around 10 ft (3.2 m) in length and weigh from 132–298 lb (60–135 kg). The shortfin mako shark is cylindrical in shape, with a vertically elongated tail. This species exhibits countershading, with brilliant metallic blue coloration dorsally and white ventrally. The line of demarcation between blue and white on the body is distinct. The underside of the snout and the area around the mouth are white. Larger specimens tend to possess darker coloration that extends onto parts of the body that would be white in smaller individuals. The juvenile mako differs in that it has a clear blackish stain on the tip of the snout. The longfin mako shark very much resembles the shortfin mako shark, but has larger pectoral fins, dark rather than pale coloration around the mouth and larger eyes. The presence of only one lateral keel on the tail and the lack of lateral cusps on the teeth distinguish the makos from the closely related porbeagle sharks of the genus Lamna.

The shortfin mako shark is the fastest species of shark. Its speed has been recorded at 25 mph (40 km/h) with bursts of up to 74 km/h (46 mph). This speed aids in leaping, with heights of approximately 9 m (30 ft) having been recorded. These characteristics have made the shortfin mako a highly sought-after game fish worldwide. Some cases of shortfin mako jumping into a boat after having been hooked have been reported.', 'Lamnidae', 'Isurus oxyrinchus', 'Vulnerable', 'The shortfin mako has a wide distribution. It is found in tropical and temperate waters throughout the world''s oceans. In North America it ranges from California to Chile in the Pacific and from the Grand Banks to the hump of Brazil, including the Gulf of Mexico and the Caribbean Sea in the Atlantic. 

The shortfall mako is commonly seen in offshore waters from Cape Cod to Cape Hatteras. In the eastern Atlantic the shortfin mako ranges from Norway to South Africa, including the Mediterranean and it is found throughout the Indian Ocean from South Africa to Australia. In the western Pacific it ranges from Japan to New Zealand and in the central Pacific it occurs from the Aleutian Islands to the Society Islands.

The shortfin mako is a true pelagic species with a primarily anti-tropical distribution. However, they will enhabit the cooler, deeper waters of tropical regions. With the ability to elevate body temperature, makos are able to maintain themselves in temperatures of 41-52°F (5-11°C). In this sense the makos are somewhat "warm-blooded," meaning that heat in their blood is conserved within the body and not lost through the gills. They have been recorded at depths of around 2500 ft (740 m). However, shortfin makos prefer water temperatures between 60-70°F. It has been hypothesized this species migrates seasonally to warmer waters. This theory has been supported by tag and release studies.

These studies have also shown that while shortfin makos follow warm water, they do so within the confines of a specific geographical area. Consequently, there seems to be limited genetic flow between these geographically distinct populations. Very little is known about the social habits of the shortfin mako, except that it is a solitary shark.', 'Mako fishing is a predominate activity around the world. As one of the fastest species in the water they offer acrobatic flips, fast runs, and heavy fights that entertain anglers. 

Makos are traditionally hooked through the use of chum and baitcasters however fly fishing for this shark has become more popular, particularly in San Diego. 

For many years mass commercial boats hunted this species for restaurant catch but through the efforts of many local fishing companies and national organizations like Orvis this practice has been deterred.', 'The shortfin mako shark is a yolk-sac ovoviviparous shark, giving birth to live young. Developing embryos feed on unfertilized eggs (oophagy) within the uterus during the 15 to 18 month gestation period. 

Shortfin mako embryos do not engage in sibling cannibalism unlike the sand tiger shark (Carcharias taurus). The four to 18 surviving young are born live in the late winter and early spring at a length of about 28 in (70 cm). Females may rest for 18 months after birth before mating again. Shortfin mako sharks bear young on average every three years.', 'The shortfin mako shark feeds mainly upon cephalopods and bony fish including mackerels, tunas, bonitos, and swordfish, but it may also eat other sharks, porpoises, sea turtles, and seabirds. 

Shorfin makos hunt by lunging vertically up in the water column (often breaking the surface) tearing off chunks of their preys'' flanks and fins. Makos swim below their prey, so they can see what is above and have a high probability of reaching their prey before they notice.

In Ganzirri and Isola Lipari, Sicily, shortfin makos have been found with amputated swordfish bills impaled into their head and gills, suggesting swordfish seriously injure and likely kill them. In addition, this location, and the late spring and early summer timing, corresponding to the swordfish''s spawning cycle, suggests they hunt while the swordfish are most vulnerable, typical of many predators.', 'Ocean', 'Speed', '1221 lb,
Luke Sweeney,
Chatham, Massachusetts, USA,
7/21/2001', 'Mako Shark  WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, baits_and_techniques, spawning_lifecycle, diet_feeding_habits, water_body_type, avg_adult_weight, known_for, world_record, world_record_link)
VALUES ('Salt', 'Opah', 'Moonfish', 'Opahs are deeply keeled, compressed, discoid fish with conspicuous coloration. The body is a deep red-orange grading to rosy on the belly, with white spots covering the flanks. Both the median and paired fins are a bright vermilion red. The large eyes stand out, as well, ringed with golden yellow. The body is covered in minute cycloid scales and its silvery, iridescent guanine coating is easily abraded.

Opahs closely resemble in shape the unrelated butterfish (family Stromateidae). Both have falcated (curved) pectoral fins and forked, emarginated(notched) caudal fins. Aside from being significantly larger than butterfish, opahs have enlarged, falcated pelvic fins with about 14 to 17 rays, which distinguish them from superficially similar carangids—positioned thoracically;

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, baits_and_techniques, spawning_lifecycle, diet_feeding_habits, water_body_type, avg_adult_weight, avg_adult_length, known_for, world_record, world_record_link)
VALUES ('Salt', 'Barramundi', 'Asian Sea Bass', 'The Barramundi has an elongated body form with a large, slightly oblique mouth and an upper jaw extending behind the eye. The lower edge of the preoperculum is serrated with a strong spine at its angle;

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, baits_and_techniques, spawning_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Tripletail, Atlantic', 'Atlantic Tripletail, Black Grunt, BlackPerch, Bouyfish, Conchy Leaf, Dusky Tripletail, Dusky Triple-tail, Flasher, Sleepfish, Steamboat, Triple Tail, Tripletail, triple-tail', 'The Atlantic tripletail has scales that extend onto its dorsal, caudal and anal fins and a head profile that concaves as it ages. It has a compressed, but deep body, with a triangle-shaped head. The eyes are small, but the mouth is large. The bases of the dorsal and anal fins are scaled and the pectoral fins are shorter than the pelvic fins. The name "tripletail" is given because of the fish''s three rounded fins: dorsal, caudal, and anal.

Juvenile Atlantic tripletails are colored a mottled yellow, brown, and black. Adults are jet black. When it lies on its side at the surface, the tripletail is sometimes confused for a floating mangrove leaf. The juveniles have white pectoral fins and a white margin on their caudal fins. Adult tripletails have varied mottled color patterns which range from dark brown to reddish brown, often with a tint of gray. 

The Atlantic tripletail grows to 35 in (89 cm) in length and weighs up to 41 lb.
', 'Lobotidae', 'Lobotes surinamensis', 'Least Concern', 'The Atlantic tripletail is the only fish in the Lobotidae family that can be found in the Atlantic Ocean. It is, however, distributed across tropical seas especially the Indonesia region.

In US waters, Atlantic tripletail are found from Massachusetts and Bermuda to Argentina, the eastern Atlantic and Mediterranean Sea, from Madeira Island to the Gulf of Guinea, the eastern Pacific from Costa Rica to Peru, and the western Pacific from Japan to Fiji and Tuvalu. 

Tripletail are rarely found north of the Chesapeake Bay in US waters. They are found on the Gulf Coast from April to October and then migrate to warmer waters during winter. In the spring, tripletails concentrate just offshore of two particular spots: Port Canaveral, Florida (March–June) and Jekyll Island, Georgia (April–July).

Atlantic tripletails are found coastally in most, but not all, tropical and subtropical seas. They are semimigratorial and pelagic. Normally solitary, they have been known to form schools. They can be found in bays, sounds, and estuaries during the summer. Juveniles are usually found swimming under patches of Sargassum algae. In the Gulf of Mexico, adults are usually found in open water, but can also be found in passes, inlets, and bays near river mouths. Large adults are sometimes found near the surface over deep, open water, although always associated with floating objects. Young fishes are also often found in or near shipwrecks, beams or supports, jetties, flotsam and sea buoys. Fry are usually found in waters that exceed 84°F (29°C), greater than 3.3‰ salinity, and more than 230 feet (70 m) deep.

Tripletails are well known for their unusual behavior of floating just beneath the surface with one side exposed, mimicking a leaf or floating debris. This is thought to be a feeding strategy because of the locality of their prey items and the floating structures associated with this behavior. The behavior has resulted in a rapidly increasing incidence of recreational fishermen sight-fishing for the floating tripletails, resulting in severe bag and length restrictions in Florida and Georgia to ensure future populations.', 'Spinning and baitcasting gear provides is the go to and most spectacular sport fishing in regards to landing tripletails. Saltwater outfits with lines up to 30 lb test are not out of place for a big fish in tight spots.

Fly fishermen try their luck with spot fishing and typically use streamer flies. Plastic lures, bucktail jigs and mirror plugs are also highly effective.

The best natural baits are live shrimp and small live fish. Strip baits and dead shrimp are also acceptable for hungry tripletail.

', 'Spawning primarily occurs in the summer along both the Atlantic and the U. Gulf of Mexico coasts, with peaks during July and August. Large congregations of tripletails during the summer months in the inshore and nearshore waters of coastal Georgia suggest this area is a critical estuarian spawning habitat for the species. Larval Atlantic tripletails go though four levels of development;

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, baits_and_techniques, spawning_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Snapper, Cubera', 'Canteen Snapper, Cuban Snapper, Gray Snapper', 'The cuber snapper is typically dark brown or gray in color, sometimes having a reddish tinge. Despite its specific name, which translates to "blue-fin," the fins have only a slight tinge of blue. It has a broad-based triangular tooth patch on the roof of the mouth without a posterior extension. The cuber snapper has extremely strong canine teeth in both jaws very strong. One pair of canines are enlarged and visible even when the mouth is closed

The dorsal fins of the cuber snapper are connected and consist of 10 spines, followed by 14 rays. The anal fin is roundish and consists of 8 rays. There are 5-7 gill rakers on the lower limb of the first branchial arch. The pectoral fins do not quite reach to the origin of the anal fin. The eyes are dark red and the body ranges from gray to greenish, often tinged with red. its closest look-alike may be the gray, or "mangrove" snapper.', 'Lutjanidae', 'Lutjanus cyanopterus', 'Vulnerable', 'The cubera snapper is a subtropical species distributed across the western Atlantic, Nova Scotia in Canada and Bermuda, to the mouth of the Amazon, Brazil. It also rarely appears in the north of Florida and in the Gulf of Mexico.

The species is reef-associated, living inshore or nearshore, over rocky ledges and overhangs. It normally occurs at depths ranging from 60 to 180 ft (18 to 55 m). 

The young fish typically inhabit inshore mangrove areas and seagrass beds that offer protection from predators. Small cubera snappers are also known to enter estuaries, and tidal reaches of streams and freshwater canals', 'Cubera are generally found in deeper waters closer to the main drop around 250 plus feet and can be caught on live baits, dead baits and lures. 

It''s a practice in some areas to actually use whole live lobsters to target cuberas as that seems to be their primary food.

Anglers often hook cuber incidentally. Slightly smaller Pacific cubera can lurk over shallower reefs where they will explode on large poppers.', 'The cubera snapper aggregates to spawn from May to September in the waters of the Caribbean during full-moon. In Belize, it aggregates during March to September within a confined area and consistent time (near sunset). 

During peak season and during the full moon from April to July between 4000 and 10000 fish aggregate to spawn. The aggregations normally take place on outer reef slopes, reef promontories and sandy drop-off areas of the shelf edge. In Puerto Rico, cubera snapper spawn on deep reefs 115-135 feet (35-40m). The snapper has also been seen to aggregate to spawn on artificial habitat in the United States. During spawning, hundreds to thousands of individuals may aggregate over deep areas. The eggs hatch within a day of fertilization, producing pelagic larvae that are dispersed by the currents.  

The cubera snapper is also known to spawn with other snapper species (i.e. dog snapper [L. Jocu], gray snapper [L. griseus], sharing both locations and peak spawning times', 'An aggressive, carnivorous fish, the cubera snapper feeds primarily on fishes and crabs. The strong canines allow mature cubera to feed on large crustaceans including lobsters and crabs. Feeding grounds are typically located near the bottom in rocky reef areas or adjacent to other structures.', 'Ocean', 'Stamina', '124 lb 12 oz,
Marion Rose,
Garden Bank, Louisiana, USA,
6/23/2007', 'Cubera Snapper WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, baits_and_techniques, spawning_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Snapper, Gray', ' Gray Snapper, Gray Silk, Mangrove Snapper, Mangrove Pargue, Mango Snapper, Pargue, Black Pargue, Black Snapper, Lawyer, Silk, Snapper', 'The gray snapper has a relatively slender body, a large mouth, and a pointed snout. The anal fin is rounded and the pectoral fins short, not reaching the anal fin. Young cubera snapper (Lutjanus cyanopterus) may be easily confused with gray snapper and careful comparison of the vomerine teeth (found on the roof of the mouth) of either species is the most reliable means of discerning the two. Adult cuberas however, are among the very largest of snapper species, obtaining lengths as great as 5 feet (1.5m) and weights of 125lbs (55.5kg) and such specimens are not likely to be confused for gray snapper! Male and female gray snapper are externally indiscernible.

Although the general ground color for this species may vary, especially so in the case of juveniles, in general the body and fins of gray snappers are gray to green with a reddish tinge. Evident on the sides of the fish are rows of small reddish to orange spots. The median fins are darker than the paired fins, often edged with yellow or white and the pectoral fins are colorless. The back edge of the anal fin is rounded. There is no black spot on the side of body. Young gray snappers have a prominent dark stripe from the snout through the eye and a less conspicuous blue stripe on the cheek, below the eye. They may also at times show a lateral pattern of narrow pale bars on the body. The fins of juveniles are reddish-orange with dark edges.

Both jaws have a narrow band of villiform (fine, densely packed hair-like) teeth, while the upper jaw contains four strong canine teeth, two of which are enlarged and easy to see.

The gray snapper is one of the smaller snappers, rarely exceeding 18 inches (45 cm) in length, and is almost always less than 10 pounds. Maximum size is 24 inches and 10lbs. Sexual maturity is obtained after about 2 years of age, at lengths of 7-13 inches (18-33 cm) and the estimated maximum age for this snapper is 25 years.', 'Lutjanidae', 'Lutjanus griseus', 'Least Concern', 'The gray snapper is found in the western Atlantic Ocean from Massachusetts to Bermuda, southward to Brazil, including Bermuda, Bahamas, West Indies, Gulf of Mexico and Caribbean Sea. It is especially abundant around the coastline of Florida.

Gray snappers reside in coastal as well as offshore waters from very shallow areas to depths of 585 feet (180m). Large aggregations of this snapper are frequently observed amongst coral reefs, rocky areas, estuaries, and mangrove habitats. Adults of the species tend to remain in the same area for long periods once established and tagging studies have shown little movement for periods of time as great as 4 years. However, within such a range the species exhibits daily activity patterns associated with nocturnal feeding and diurnal schooling. Young gray snapper live inshore in areas such as seagrass beds as well as soft and sand-bottom areas but may be found in a variety of habitats and a number of inshore habitats are important nurseries for this species. Both adults and juveniles have been found in freshwater lakes and rivers in south Florida, a clear indication that the species is tolerant of a broad range of salinity levels.', 'For shallow fishing, spinning and light bait casting rigs are typically best. Good baits include live shrimp live minnows, fielder crabs, cut shrimp, cut squid and cut baitfish. Many inshore snappers are also caught on artificial lures and flies, particularly along mangrove shorelines or around snags.

Offshore, heavier spinning and baitcasting tackle or light ocean tackle are typically called upon. It is best to keep lines at the 20 lb test range, but sometimes eve 10 or 12 lb test will get the job done, but will offer more of a challenge.', 'Spawning occurs from April to November with a peak during the summer months, and is influenced by the lunar cycle. Individual snappers may spawn multiple times during the course of the reproductive season. Gray snapper spawn in aggregations during the times surrounding the full moon. The species is a broadcast spawner of demersal eggs from which hatch sparsely pigmented larvae approximately 20 hours post-fertilization. The yolk sac is absorbed within the first 45 hours, after which the larvae must actively feed amongst the plankton. Although little is known about larval snappers in general, most appear to be planktonic at lengths less than 10mm. The post-larval gray snapper typically settle into suitable estuarine habitats such as seagrass beds and mangroves, although they are known from a variety of habitats. Estuarine nursery areas offer rich sources of food as well as protection from predators. The pre-juvenile and juvenile snapper feed by day until they achieve a size of approximately 80mm around which time they move into shallow rocky areas and the coastal reefs where they are commonly found as adults.', 'Gray snapper are opportunistic predators. Larvae feed on zooplankton including copepods and amphipods. Juvenile gray snappers feed by day among seagrass beds, mainly on crustaceans and fish and to a lesser degree polychaete worms and molluscs. Foraging nocturnally, adult gray snapper prey upon small fishes, shrimps, crabs, gastropods, and cephalopods.', 'Ocean', 'Fight Dynamics', '18 lb 10 oz,
Tim Champagne,
Cocodrie, Louisiana, USA,
7/22/2015', 'Gray Snapper WR');

-- Verify batch import
SELECT COUNT(*) as total_salt FROM fish_species WHERE class = 'Salt';
