-- Saltwater Fish Import Batch 1 of 9
-- Contains 10 records

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, baits_and_techniques, spawning_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Shark, Whitetip Reef', 'Brown Milbert''s Sand Bar Shark, Brown Shark, Nigano Shark, Oceanic White-Tipped Whaler, Silvertip Shark', 'A relatively small species, few whitetip reef sharks are longer than 5.2 ft (1.6 m). The maximum length this species attains is often given as 6.9 ft (2.1 m), though this was originally based on visual observations and may be dubious. The maximum reported weight is 40 lb (18.3 kg). The whitetip reef shark has a slim body and a short, broad head. The snout is flattened and blunt, with large flaps of skin in front of the nares that are furled into tubes. The eyes are small and oval with vertical pupils and prominent ridges above, and are often followed by a small notch. The mouth has a distinct downward slant (imparting a disgruntled expression to the shark), with short furrows at the corners. There are 42–50 tooth rows in the upper jaw and 42–48 tooth rows in the lower jaw. Each tooth has a single narrow, smooth-edged cusp at the center, flanked by a pair of much smaller cusplets.

The first dorsal fin is positioned well back on the body, closer to the pelvic than the pectoral fins. The second dorsal and anal fins are large, about half to three-quarters as high as the first dorsal fin. The broad, triangular pectoral fins originate at or slightly before the level of the fifth gill slit. There is no ridge between the first and second dorsal fins. The lower lobe of the caudal fin is half the length of the upper, which has a strong notch near the tip. The dermal denticles are small and overlapping, usually with 7 horizontal ridges, giving the skin a smooth feel. The coloration is grayish to brownish above and white below, with a pattern of scattered small, dark spots unique to each individual. The tips of the first dorsal fin and upper caudal fin lobe, and sometimes also the second dorsal fin and lower caudal fin lobe, are bright white.', '	Carcharhinidae', 'Carcharhinus longimanus', 'Vulnerable', 'The Whitetip Reef Shark is distributed widely across the entire Indo-Pacific region. It was once thought to have formerly existed in the Atlantic Ocean, based on fossil teeth found in North Carolina dating to the Miocene epoch. However, more recent research indicates that the teeth belonged to a mackerel shark, and that this species has never colonized the Atlantic.

In the Indian Ocean, it occurs from northern KwaZulu-Natal, South Africa to the Red Sea and the Indian subcontinent, including Madagascar, Mauritius, the Comoros, the Aldabra Group, the Seychelles, Sri Lanka, and the Chagos Archipelago. In the western and central Pacific, it occurs from off southern China, Taiwan, and the Ryukyu Islands, to the Philippines, Southeast Asia, and Indonesia, to northern Australia, and is also found around numerous islands in Melanesia, Micronesia, and Polynesia, as far as Hawaii to the north and the Pitcairn Islands to the southeast. In the eastern Pacific, it occurs from Costa Rica to Panama, and off the Galápagos Islands.

Associated almost exclusively with coral reef habitats, whitetip reef sharks are most often encountered around coral heads and ledges with high vertical relief, and additionally over sandy flats, in lagoons, and near drop-offs to deeper water. They prefer very clear water and rarely swim far from the bottom. This species is most common at a depth of 26–131 ft (8–40 m).

On occasion, whitetips may enter water less than 3 ft (1 m) deep, and there is an exceptional record of a whitetip reef shark being captured from a depth of 1,080 ft (330 m) in the Ryukyu Islands.', 'Whitetip sharks are small in size, but will strike baits, lures and flies fairly aggressively. 
', 'Like other members of its family, the whitetip reef shark is viviparous;

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, baits_and_techniques, spawning_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Spearfish, Longbill', 'Atlantic Longbill Spearfish, Atlantic Spearfish, Atlantic Lognbill, Longbill', 'The longbill spearfish is a blueish black color from above, and silvery-white and brown on the sides to white underneath. The pectorals are blackish-brown and the dorsal fins are dark blue. The upper jay is prolonged into a spear and its cross section is round. Longbill spearfish are found offshore in deep water.', '	Istiophoridae', 'Tetrapturus pfluegeri', 'Least Concern', 'The longbill spearfish is known to occur in the northwest Atlantic from New Jersey to Venezuela, including the Gulf of Mexico.', 'The best method for catching longbill spearfish is saltwater trolling. Fishing methods are the same as for other billfish, but with lighter tackle. Most are taken incidentally. Top baits for longbows are saltwater live bait, squid and trolling lures.', 'Longbill spearfish are uncommon.  Available data indicate that this spearfish matures at 2 years of age and rarely lives past 4 to 5 years.', 'Longbill spearfish are pelagic and feed at or near the surface, mainly on fishes and squid.', 'Ocean', 'Aerial Acrobatics', '127 lb 13 oz,
Paul Cashmore,
Puerto Rico, Gran Canaria, Canary Islands, Spain,
5/20/1999	', 'Longbill Spearfish WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, baits_and_techniques, spawning_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record)
VALUES ('Salt', 'Sturgeon, White', 'California White Sturgeon, Columbia Sturgeon, Oregon Sturgeon, Pacific Sturgeon, Sacramento Sturgeon', 'The white sturgeon has a slender, long body, head, and mouth. This fish has no scales;

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, baits_and_techniques, spawning_lifecycle, diet_feeding_habits, water_body_type, avg_adult_weight, avg_adult_length, known_for, world_record, world_record_link)
VALUES ('Salt', 'Bonefish', 'Banana,Bananafish, Indo-Pacific Bonefish, Ladyfish, Round Jaw, Salmon Peel, Tarpon, Tenny, Tenpounder', 'One of the most distinctive characteristics of the bonefish is the inferior mouth and conical nose that protrudes a third of its length beyond the mandible. The body is slender, round, and compressed, more so in large specimens than in young adults. The dorsal profile is more convex than the ventral profile. The first few rays of the dorsal fin are higher than the following rays and this lends a somewhat triangular shape to the dorsal fin when erect. The caudal fin is deeply forked, with the upper lobe slightly larger than the lower. 

Bonefish appear blue-greenish above, with bright silver scales on the sides and below. Dark streaks run in between the rows of scales, predominantly on the dorsal side of the body. The dorsal and caudal fins have dusky margins. Bonefish have no spines. Juvenile bonefish exhibit a series of nine dark crossbands on their backs. These bands extend nearly to the lateral line, with the third band crossing at the origin of the dorsal fin. Bands four and five are found under the posterior base of the dorsal fin. As the juvenile bonefish age the bands begin to disappear with the posterior bands the first to fade. Beyond about 3 inches (7.5 cm) the dark longitudinal streaks characteristic of the adults begin to appear and the last of the crossbands become obscured. 

Granular teeth, forming specialized dental plates, cover the tongue and upper jaw of the bonefish. Similar grinders are also present in the throat. The bonefish uses these modified teeth to grind its mollusk and crustacean prey. 

The IGFA all-tackle record of 19 pounds has held since 1962, when it was caught from the surf off South Africa (though not A. vulpes — another species).', 'Albulidae', 'Albula vulpes', 'Near Threatened', 'Bonefish are predominately a coastal species, commonly found in intertidal flats, mangrove areas, river mouths, and deeper adjacent waters. The flats vary in composition from sand or grass to rocky substrates. 

Bonefish can tolerate the oxygen-poor water they sometimes encounter in coastal habitats by inhaling air into a lung-like air bladder. Bonefish typically school, sometimes in groups of up to 100 individuals. Studies in the Bahamas using ultrasonic telemetry demonstrated the daily patterns of bonefish consist of a movement to shallow water during the rising tide, and a retreat into deeper water during a falling tide. Bonefish are also known to move from particular sites (creek, channel, bay, etc.) after inhabiting the location for a maximum period of several days. Over the long-term movements between such "favorite" sites seem to occur without any discernable pattern. During summer months, larger individuals tend to remain in deep water, rarely moving onto the flats;

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, baits_and_techniques, spawning_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Shark, Thresher', 'Thrasher Shark, Common Thresher Shark, Fox Shark,
Grayfish, Sea Fox, Slasher, Swingletail, Swiveltail, Thintail Thresher,
Whip-Tailed Shark, Zorro Thresher Shark, Renard, Faux, Zorro', 'Thresher sharks are large lamniform sharks of the family Alopiidae found in all temperate and tropical oceans of the world;

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, baits_and_techniques, spawning_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Kahawai', 'Giant Kahawai, Kermadec Kahawai, Northern Kahawai, Australian Salmon, Australian Herring', 'The kawawai is a streamlined, in-shore, pelagic species. It is a firm, silvery fish ranging from grey-blue to blue-green on top and silver below. They have rows of black spots along their flanks. While they can grow up to around 30in (75 cm) and 20lb (9kg), they average around 15-20in (40-50cm) and 2-3lb (1-2kg).

The kahawai (or Australian salmon) is unique to Australia and New Zealand. It resembles a trout or salmon in shape and appearance, but is of no relation. It and when properly bled can make for great eating. It is particularly good smoked.', 'Arripidae', 'Arripis trutta', 'Not Evaluated', 'Kahawai are found off the southern coast of Australia from western Victoria to New Zealand, including the islands of Tasmania, Lord Howe, and Norfolk.

Kahawai and other Australian salmon stay within the upper layers of relatively shallow (1–80 m), open and clear coastal waters (although the western Australian salmon may prefer deeper water). The turbulent surf zone of beaches, rocky reefs, bays, and brackish waters such as estuaries are also frequented, and some species may also enter rivers. Juveniles inhabit estuaries and mangroves, as well as sheltered bays with soft bottoms carpeted with seagrasses. Adults undertake seasonal migrations over vast distances, moving into deeper water during winter months. The evolutionary history of the species of Arripis has been shaped by changes to oceanographic conditions and land-bridges that occurred during glacial cycles.
', 'Kahawai is the traditional maori name which when translated means "brave" or "strong" (kaha) water (wai). This in reference to the kahawi''s tendency to jump and fight when caught. In New Zealand it is often caught in abundance at river mouths and is a highly popular sports fish that is widely regarded to "punch above its weight" in terms of challenge to land.

It can often be caught on a spinning or surf casting reel, although it is not unheard of for fishermen to use lighter lines and fly fishing rods for a real challenge.

The kahawai is often associated with the white fronted tern, as the bird often congregates above the bait balls associated with a shoal of kahawai hunting. As such the tern is colloquially known as the "kahawai bird"', 'Although their reproduction is poorly studied, all Australian salmon including kahawai are known to be "pelagic spawners";

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, baits_and_techniques, spawning_lifecycle, diet_feeding_habits, water_body_type, avg_adult_weight, avg_adult_length, known_for, world_record, world_record_link)
VALUES ('Salt', 'Jack, Bluefin Trevally', 'Bluefin Jack, Bluefin Kingfish, Bluefinned Crevalle, Blue Ulua, Omilu, Spotted Trevally', 'The bluefin trevally is a species of large, widely distributed marine fish classified in the jack family, Carangidae. Bluefin trevally are easily recognized by their electric blue fins, tapered snout and numerous blue and black spots on their sides. Juveniles lack these obvious colors, and must be identified by more detailed anatomical features such as fin ray and scute counts. The species grows to a maximum known length of 46 inches and a weight of 95 pounds, however is rare above 32 inches.

It is similar in shape to a number of other large jacks and trevallies, having an oblong, compressed body with the dorsal profile slightly more convex than the ventral profile, particularly anteriorly. This slight convexity leads to the species having a much more pointed snout than most other members of Caranx. 

The dorsal fin is in two parts, the first consisting of 8 spines and the second of 1 spine followed by 21 to 24 soft rays. The anal fin consists of 2 anteriorly detached spines followed by 1 spine and 17 to 20 soft rays. The pelvic fins contain 1 spine and 20 soft rays. The caudal fin is strongly forked, and the pectoral fins are falcate, being longer than the length of the head. 

The lateral line has a pronounced and moderately long anterior arch, with the curved section intersecting the straight section below the lobe of the second dorsal fin. The curved section of the lateral line contains 55-70 scales while the straight section contains 0 to 10 scales followed by 27 to 42 strong scutes. The chest is completely covered in scales. 

The upper jaw contains a series of strong outer canines with an inner band of smaller teeth, while the lower jaw contains a single row of widely spaced conical teeth. The species has 25 to 29 gill rakers in total and there are 24 vertebrae present. The eye is covered by a moderately weakly developed adipose eyelid, and the posterior extremity of the jaw is vertically under or just past the anterior margin of the eye. Despite their wide range, the only geographical variation in the species is the depth of the body in smaller specimens.

The upper body of the bluefin trevally is a silver-brassy colour, fading to silvery white on the underside of the fish, often with blue hues. After they reach lengths greater than 16 cm, blue-black spots appear on the upper flanks of the fish, with these becoming more prolific with age. There is no dark spot on the operculum. The species takes its name from the colour of its dorsal, anal and caudal fins, which are a diagnostic electric blue. The pelvic and pectoral fins are white, with the pectoral fin having a yellow tinge. Juvenile fish do not have the bright blue fins, instead have dark fins with the exception of a yellow pectoral fin. Some juvenile fish have also been recorded as having up to five dark vertical bars on their sides.

The IGFA all-tackle world record is 29 pounds, 3 ounces from Clipperton Atoll (2012);

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, baits_and_techniques, spawning_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Jack, California Yellowtail', 'Yellowtail Amberjack, Asian Yellowtail,
Southern Yellowtail, Kingy, Cape Yellowtail, Forktail, Mossback, White Salmon', 'The body of the California yellowtail is elongated, fusiform and compressed. The upper and lower body profiles are similar and the snout is long and pointed with the mouth ending under front edge of pupil 

The California yellowtail is most often blue on the upper back with sides and belly coloration ranging from silvery to white. The California yellowtail presents  a narrow yellow-bronze stripe along the middle of body running down the lateral line and arching over the pectoral region, becoming yellow posteriorly on most fins including the tail. Juvenile present with numerous narrow dark bars (a little wider than pale interspaces) that do not extend onto the dorsal and anal fins.



', 'Carangidae', 'Seriola lalandi dorsalis', 'Not Evaluated', 'The yellowtail''s range is circumglobal, in subtropical waters. It can be found near Catalina Island, San Clemente Island, and Santa Monica Bay, as well as in Mexican waters such as Baja California Peninsula and Gulf of California, congregating at certain areas in mass numbers like Cedros Island and Benitos Island. 

During the summer months yellowtails can also be found in association with floating kelp paddies off the coast of southern California and Baja California. 

Yellowtail populations have also been found in waters off South Africa, the Walter Shoals, Amsterdam Island, Japan, Australia, New Zealand, New Caledonia, Hawaii, Rapa, Pitcairn Island, Jeju Island, and Easter Island. In the Eastern Pacific, they can be found in waters off British Columbia, as well as from Canada to Chile. They are usually found around offshore islands, rocky reefs, and kelp beds. They are also found in increasing numbers off the Islands of the Tristan Da Cunha archipelago in the South Atlantic. ', 'Angling for yellowtail requires tackle heavy enough to insure a fair chance of landing the fish. Yellowtail like to head for rocks or kelp as soon as they''re hooked so line should test 20-30 pounds, hooks should be small (size 6 or 4) but strong, and the angler must make sure the fish is played out before it nears the pier and the pilings otherwise tangling is likely inevitably ending in a broken line. 

Although an assortment of lures work well when fishing for California Yellowtail on boats, almost all of the pier-caught yellowtail are taken on live bait. The most effective live and cut baits are small jack mackerel, Pacific mackerel or Pacific sardines.', 'California yellowtail spawn in warm waters 100–300 miles off the California coast and return in May or June until September or December. They spawn slowly, but may live in excess of 30 years. 

Spawning usually begins at three years of age. One major spawning ground is at Cedros Island, where large numbers of 15- to 20-pound yellowtail can be caught. Yellowtail are aggressive towards other fish. 

They will often feed more frequently during spawning, which makes them an easy target for commercial fishing boats. They are currently not on the endangered list.', 'The California Yellowtail is carnivorous and feeds on a variety of fish. Mackerel, sardines, anchovies, squid, and crab are common in the yellowtail''s diet. Often, the California Yellowtail are found in schools feeding at the surface of the water, but also feed deeper down in the water column.', 'Ocean', 'Stamina', '109 lb 2 oz,
Masakazu Taniwaki,
Ohara, Chiba, Japan,
10/24/2009', 'Yellowtail WR');

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, baits_and_techniques, spawning_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Jack, Crevalle ', 'Trevallies, Jackfish, Crevally Jack, Common Jack, Black-tailed Trevally, Couvalli, Jack, Black Cavalli, Yellow Cavalli', 'The crevalle jack''s color ranges from brassy green to blue or bluish-black dorsally, becoming silvery white or golden ventrally. A dark spot is often present on the pectoral fin, with a similar dark to dusky spot present on the upper margin of the operculum. Juveniles have around five dark vertical bands on their sides, with these fading at adulthood. The first dorsal fin, pectoral and pelvic fins range from white to dusky, occasionally with golden tinges throughout. The anal fin lobe is bright yellow, with the remainder of the fin ranging from golden to dusky, while the underside of the caudal peduncle often being yellow in adults. The caudal fin itself is also golden to dusky, with the lower lobe often brighter yellow than the upper, with both the lobes often having a black trailing edge.

The crevalle jack is one of the largest members of Caranx, growing to a known maximum length of  50 in (125 cm) and a weight of 70 lb (32 kg), although it is generally uncommon at lengths greater than 65 cm. Unverified reports of fish over 60 in (150 cm) may also be attributable to this species. The crevalle jack is morphologically similar to a number of other deep-bodied carangids, having an elongate, moderately compressed body with the dorsal profile more convex than the ventral profile, particularly anteriorly. The eye is covered by a well-developed adipose eyelid, and the posterior extremity of the jaw is vertically under or past the posterior margin of the eye.The dorsal fin is in two parts, the first consisting of eight spines and the second of one spine followed by 19 to 21 soft rays. The anal fin consists of two anteriorly detached spines followed by one spine and 16 or 17 soft rays. The pelvic fins contain one spine and five soft rays, while the pectoral fins contain 20 or 21 soft rays. The caudal fin is strongly forked, and the pectoral fins are falcate, being longer than the length of the head. The lateral line has a pronounced and moderately long anterior arch, with the curved section intersecting the straight section midway below the second dorsal fin. The straight section contains 23 to 35 very strong scutes, with bilateral keels present on the caudal peduncle. The chest is devoid of scales with the exception of a small patch of scales in front of the pelvic fins. The upper jaw contains a series of strong outer canines with an inner band of smaller teeth, while the lower jaw contains a single row of teeth. The species has 35 to 42 gill rakers in total and 25 vertebrae are present.', 'Carangidae', 'Caranx hippos', 'Least Concern', 'The Crevalle Jack lives in both inshore and offshore habitats, with larger adults preferring deeper waters than juveniles. In the inshore environment, crevalle jack inhabit shallow flats, sandy bays, beaches, seagrass beds, shallow reef complexes and lagoons, which may be open or landocked, and may be composites of the aforementioned environments. The species is also known to enter brackish waters, with some individuals known to penetrate far upstream;

INSERT INTO fish_species (class, common_name, also_known_as, description, family, species, environmental_status, habitat, baits_and_techniques, spawning_lifecycle, diet_feeding_habits, water_body_type, known_for, world_record, world_record_link)
VALUES ('Salt', 'Jack, Giant Trevally', 'Barrier Trivially, Giant Kingfish, GT, Lowly Trivially, Ulua, ', 'The giant trevally is distinguished by its steep head profile, strong tail scutes, and a variety of other more detailed anatomical features. It is normally a silvery color with occasional dark spots, but males may be black once they mature. It is the largest fish in the genus Caranx with the IGFA world record weighing in at an amazing 160 pounds, 7 ounces caught in Japanese waters in 2006.', 'Carangidae', 'Caranx ignobilis', 'Not Evaluated', 'The giant trevally is distributed throughout the tropical waters of the Indo-Pacific region, with a range stretching from South Africa in the west to Hawaii in the east, including Japan in the north and Australia in the south.', 'One of the largest members of the jack (Carangidae) family, giant trevally (widely known as GT) are quite simply one of toughest fish on rod and reel in the world.', 'The species reproduces in the warmer months, with peaks differing by region. Spawning occurs at specific stages of the lunar cycle, when large schools congregate to spawn over reefs and bays, with reproductive behavior observed in the wild. The fish grows relatively fast, reaching sexual maturity at a length of around 23 in (60 cm) and around three years of age.', 'The giant trevally is a powerful apex predator in most of its habitats, and is known to hunt individually and in schools. The species predominantly takes various fish as prey, although crustaceans, cephalopods and mollusks make up a considerable part of their diets in some regions. The species has some quite novel hunting strategies, including shadowing monk seals to pick off escaping prey, as well as using sharks to ambush prey.', 'Ocean', 'Stamina', '160 lb 7 oz,
Keiki Hamasaki,
Tokara, Kagoshima, Japan
5/22/2006
', 'Giant Trevally WR');

-- Verify batch import
SELECT COUNT(*) as total_salt FROM fish_species WHERE class = 'Salt';
